/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 55 (tensor id: 640)
-/
import denote.gpt_ly4_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_55 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [989, 638, 639], outs := [640] },
  ]

def pm_goal_55 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [2225, 638, 639], outs := [2229] },
    { rank := 1, op := "OpName.FW_layernorm", ins := [2226, 638, 639], outs := [2230] },
    { rank := 2, op := "OpName.FW_layernorm", ins := [2227, 638, 639], outs := [2231] },
    { rank := 3, op := "OpName.FW_layernorm", ins := [2228, 638, 639], outs := [2232] },
  ]

def sm_goal_55InitShapes : List (Tid × Shape) := [
  (638, [32]),
  (639, [32]),
  (989, [1, 8, 32]),
]

def sm_goal_55InitEnv : ShapeEnv := shapeEnvOfList sm_goal_55InitShapes

def pm_goal_55InitShapes : List (Tid × Shape) := [
  (638, [32]),
  (639, [32]),
  (2225, [1, 2, 32]),
  (2226, [1, 2, 32]),
  (2227, [1, 2, 32]),
  (2228, [1, 2, 32]),
]

def pm_goal_55InitEnv : ShapeEnv := shapeEnvOfList pm_goal_55InitShapes

def goal_55_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285]
def goal_55_cut_initGoals : List LineageGoal := initGoals ++ goal_55_prereqs

def goal_55_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_55 pm_goal_55 goal_55 sm_goal_55InitEnv pm_goal_55InitEnv goal_55_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

