/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 257 (tensor id: 903)
-/
import denote.gpt_ly4_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_257 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [567], outs := [903, 907], params := [2] },
  ]

def pm_goal_257 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [1117], outs := [3413, 1501], params := [2] },
    { rank := 1, op := "OpName.FW_multiref", ins := [1118], outs := [3419, 1502], params := [2] },
    { rank := 2, op := "OpName.FW_multiref", ins := [1119], outs := [3425, 1503], params := [2] },
    { rank := 3, op := "OpName.FW_multiref", ins := [1120], outs := [3431, 1504], params := [2] },
    { rank := 0, op := "OpName.AllToAllPrim", ins := [3413, 3419, 3425, 3431], outs := [1141], params := [2, 1] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [3413, 3419, 3425, 3431], outs := [1142], params := [2, 1] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [3413, 3419, 3425, 3431], outs := [1143], params := [2, 1] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [3413, 3419, 3425, 3431], outs := [1144], params := [2, 1] },
  ]

def sm_goal_257InitShapes : List (Tid × Shape) := [
  (567, [1, 8, 32]),
]

def sm_goal_257InitEnv : ShapeEnv := shapeEnvOfList sm_goal_257InitShapes

def pm_goal_257InitShapes : List (Tid × Shape) := [
  (1117, [1, 8, 8]),
  (1118, [1, 8, 8]),
  (1119, [1, 8, 8]),
  (1120, [1, 8, 8]),
]

def pm_goal_257InitEnv : ShapeEnv := shapeEnvOfList pm_goal_257InitShapes

def goal_257_prereqs : List LineageGoal := [goal_2, goal_3, goal_4]
def goal_257_cut_initGoals : List LineageGoal := initGoals ++ goal_257_prereqs

def goal_257_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_257 pm_goal_257 goal_257 sm_goal_257InitEnv pm_goal_257InitEnv goal_257_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

