/- AUTO-GENERATED by bridge_emitter (FAMILY-A: multi-tp, 0 mid, per-rank op).
   goal_65: SM=FW_transpose([650])->653;
   PM=4xFW_transpose(per-rank inputs)->[653] multi-tps gatherDim=None.
   prereqs=[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 61, 62, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285, 291] (len 73). Inputs sourced from: 650<-ts:62, 2369<-tp:62, 2370<-tp:62, 2371<-tp:62, 2372<-tp:62. -/
import denote.gpt_ly4_regen.BridgeKit
import denote.gpt_ly4_regen.SpikeBridge
import denote.gpt_ly4_regen.Goal62Bridge
import denote.gpt_ly4_regen.Goal257Bridge
import denote.gpt_ly4_regen.Goal259Bridge
import denote.gpt_ly4_regen.Goal261Bridge
import denote.gpt_ly4_regen.Goal263Bridge
import denote.gpt_ly4_regen.Goal265Bridge
import denote.gpt_ly4_regen.Goal267Bridge
import denote.gpt_ly4_regen.Goal269Bridge
import denote.gpt_ly4_regen.Goal271Bridge
import denote.gpt_ly4_regen.Goal273Bridge
import denote.gpt_ly4_regen.Goal275Bridge
import denote.gpt_ly4_regen.Goal277Bridge
import denote.gpt_ly4_regen.Goal279Bridge
import denote.gpt_ly4_regen.Goal281Bridge
import denote.gpt_ly4_regen.Goal283Bridge
import denote.gpt_ly4_regen.Goal285Bridge
import denote.gpt_ly4_regen.Goal291Bridge
import denote.gpt_ly4_regen.Goal_65

set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.style.nativeDecide false
set_option linter.unusedSimpArgs false
set_option linter.style.commandStart false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unusedVariables false
set_option linter.style.show false
set_option linter.style.emptyLine false
set_option linter.style.setOption false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false

namespace TrainVerify.Denote.GeneratedGoals
open TrainVerify.Denote TrainVerify.Denote.Generated

-- ========== mini sm_goal_65 computes 653 (FW_transpose) ==========
theorem denote_sm_goal_65_653 (s : Store) :
    denoteGraph sm_goal_65 s 653 = transposeAxes 2 3 (s 650) := by
  simp only [sm_goal_65, denoteGraph, List.foldl]
  rw [applyNode_fw_transposeAxes_out]

-- ========== SM self-frame ==========
theorem sm_frame_653_self (initSM : Store) :
    denoteGraph sm initSM 653 = denoteGraph sm_goal_65 (denoteGraph sm initSM) 653 := by
  rw [denote_sm_goal_65_653]
  rw [sm_val initSM 71 653 (by native_decide) (by native_decide)]
  rw [show sm.nodes[71]'(by native_decide)
      = { rank := 0, op := "OpName.FW_transpose", ins := [650], outs := [653], params := [2, 3] }
      from by native_decide]
  rw [applyNode_fw_transposeAxes_out]
  rw [sm_prefix_eq initSM 71 650 (by native_decide)]

-- ========== pm_full (mid tensors) ==========
theorem pm_full_g65_2413 (initPM : Store) :
    denoteGraph pm initPM 2413
      = allToAllPrimWithDims pm.numRanks 0 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1 := by
  rw [pm_val initPM 461 2413 (by native_decide) (by native_decide)]
  rw [show pm.nodes[461]'(by native_decide)
      = { rank := 0, op := "OpName.AllToAllPrim", ins := ((List.range 4).map (fun r => 2369 + r)), outs := [2413], params := [3, 1] }
      from by native_decide]
  rw [applyNode_allToAllPrimWithDims_out]
  simp only [List.range, List.range.loop, List.map]
  rw [pm_prefix_eq initPM 461 2369 (by native_decide),
      pm_prefix_eq initPM 461 2370 (by native_decide),
      pm_prefix_eq initPM 461 2371 (by native_decide),
      pm_prefix_eq initPM 461 2372 (by native_decide)]

theorem pm_full_g65_2414 (initPM : Store) :
    denoteGraph pm initPM 2414
      = allToAllPrimWithDims pm.numRanks 1 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1 := by
  rw [pm_val initPM 462 2414 (by native_decide) (by native_decide)]
  rw [show pm.nodes[462]'(by native_decide)
      = { rank := 1, op := "OpName.AllToAllPrim", ins := ((List.range 4).map (fun r => 2369 + r)), outs := [2414], params := [3, 1] }
      from by native_decide]
  rw [applyNode_allToAllPrimWithDims_out]
  simp only [List.range, List.range.loop, List.map]
  rw [pm_prefix_eq initPM 462 2369 (by native_decide),
      pm_prefix_eq initPM 462 2370 (by native_decide),
      pm_prefix_eq initPM 462 2371 (by native_decide),
      pm_prefix_eq initPM 462 2372 (by native_decide)]

theorem pm_full_g65_2415 (initPM : Store) :
    denoteGraph pm initPM 2415
      = allToAllPrimWithDims pm.numRanks 2 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1 := by
  rw [pm_val initPM 463 2415 (by native_decide) (by native_decide)]
  rw [show pm.nodes[463]'(by native_decide)
      = { rank := 2, op := "OpName.AllToAllPrim", ins := ((List.range 4).map (fun r => 2369 + r)), outs := [2415], params := [3, 1] }
      from by native_decide]
  rw [applyNode_allToAllPrimWithDims_out]
  simp only [List.range, List.range.loop, List.map]
  rw [pm_prefix_eq initPM 463 2369 (by native_decide),
      pm_prefix_eq initPM 463 2370 (by native_decide),
      pm_prefix_eq initPM 463 2371 (by native_decide),
      pm_prefix_eq initPM 463 2372 (by native_decide)]

theorem pm_full_g65_2416 (initPM : Store) :
    denoteGraph pm initPM 2416
      = allToAllPrimWithDims pm.numRanks 3 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1 := by
  rw [pm_val initPM 464 2416 (by native_decide) (by native_decide)]
  rw [show pm.nodes[464]'(by native_decide)
      = { rank := 3, op := "OpName.AllToAllPrim", ins := ((List.range 4).map (fun r => 2369 + r)), outs := [2416], params := [3, 1] }
      from by native_decide]
  rw [applyNode_allToAllPrimWithDims_out]
  simp only [List.range, List.range.loop, List.map]
  rw [pm_prefix_eq initPM 464 2369 (by native_decide),
      pm_prefix_eq initPM 464 2370 (by native_decide),
      pm_prefix_eq initPM 464 2371 (by native_decide),
      pm_prefix_eq initPM 464 2372 (by native_decide)]

theorem pm_full_g65_2417 (initPM : Store) :
    denoteGraph pm initPM 2417
      = transposeAxes 2 3 (denoteGraph pm initPM 2413) := by
  rw [pm_val initPM 465 2417 (by native_decide) (by native_decide)]
  rw [show pm.nodes[465]'(by native_decide)
      = { rank := 0, op := "OpName.FW_transpose", ins := [2413], outs := [2417], params := [2, 3] }
      from by native_decide]
  rw [applyNode_fw_transposeAxes_out]
  rw [pm_prefix_eq initPM 465 2413 (by native_decide)]

theorem pm_full_g65_2418 (initPM : Store) :
    denoteGraph pm initPM 2418
      = transposeAxes 2 3 (denoteGraph pm initPM 2414) := by
  rw [pm_val initPM 466 2418 (by native_decide) (by native_decide)]
  rw [show pm.nodes[466]'(by native_decide)
      = { rank := 1, op := "OpName.FW_transpose", ins := [2414], outs := [2418], params := [2, 3] }
      from by native_decide]
  rw [applyNode_fw_transposeAxes_out]
  rw [pm_prefix_eq initPM 466 2414 (by native_decide)]

theorem pm_full_g65_2419 (initPM : Store) :
    denoteGraph pm initPM 2419
      = transposeAxes 2 3 (denoteGraph pm initPM 2415) := by
  rw [pm_val initPM 467 2419 (by native_decide) (by native_decide)]
  rw [show pm.nodes[467]'(by native_decide)
      = { rank := 2, op := "OpName.FW_transpose", ins := [2415], outs := [2419], params := [2, 3] }
      from by native_decide]
  rw [applyNode_fw_transposeAxes_out]
  rw [pm_prefix_eq initPM 467 2415 (by native_decide)]

theorem pm_full_g65_2420 (initPM : Store) :
    denoteGraph pm initPM 2420
      = transposeAxes 2 3 (denoteGraph pm initPM 2416) := by
  rw [pm_val initPM 468 2420 (by native_decide) (by native_decide)]
  rw [show pm.nodes[468]'(by native_decide)
      = { rank := 3, op := "OpName.FW_transpose", ins := [2416], outs := [2420], params := [2, 3] }
      from by native_decide]
  rw [applyNode_fw_transposeAxes_out]
  rw [pm_prefix_eq initPM 468 2416 (by native_decide)]

-- ========== denote_pm (final tps [653]) ==========
theorem denote_pm_goal_65_653 (s : Store) :
    denoteGraph pm_goal_65 s 653 = allGatherPrimDimN 1 4 0 [transposeAxes 2 3 (allToAllPrimWithDims 4 0 [s 2369, s 2370, s 2371, s 2372] 3 1), transposeAxes 2 3 (allToAllPrimWithDims 4 1 [s 2369, s 2370, s 2371, s 2372] 3 1), transposeAxes 2 3 (allToAllPrimWithDims 4 2 [s 2369, s 2370, s 2371, s 2372] 3 1), transposeAxes 2 3 (allToAllPrimWithDims 4 3 [s 2369, s 2370, s 2371, s 2372] 3 1)] := by
  simp only [pm_goal_65, denoteGraph, List.foldl]
  rw [applyNode_allGatherPrimDimN_out]
  simp only [List.map]
  try (set_option maxHeartbeats 800000 in congr 1)

-- ========== pm_frame (final tps) ==========
theorem pm_frame_653_self (initPM : Store) :
    denoteGraph pm initPM 653
      = allGatherPrimDimN 1 4 0 [transposeAxes 2 3 (allToAllPrimWithDims 4 0 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1), transposeAxes 2 3 (allToAllPrimWithDims 4 1 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1), transposeAxes 2 3 (allToAllPrimWithDims 4 2 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1), transposeAxes 2 3 (allToAllPrimWithDims 4 3 [denoteGraph pm initPM 2369, denoteGraph pm initPM 2370, denoteGraph pm initPM 2371, denoteGraph pm initPM 2372] 3 1)] := by
  rw [pm_val initPM 469 653 (by native_decide) (by native_decide)]
  rw [show pm.nodes[469]'(by native_decide)
      = { rank := 0, op := "OpName.AllGatherPrim", ins := ((List.range 4).map (fun r => 2417 + r)), outs := [653], params := [1] }
      from by native_decide]
  rw [applyNode_allGatherPrimDimN_out_thm]
  simp only [List.range, List.range.loop, List.map]
  rw [pm_prefix_eq initPM 469 2417 (by native_decide),
      pm_prefix_eq initPM 469 2418 (by native_decide),
      pm_prefix_eq initPM 469 2419 (by native_decide),
      pm_prefix_eq initPM 469 2420 (by native_decide)]
  rw [pm_full_g65_2420, pm_full_g65_2419, pm_full_g65_2418, pm_full_g65_2417, pm_full_g65_2416, pm_full_g65_2415, pm_full_g65_2414, pm_full_g65_2413]
  rw [show pm.numRanks = 4 from by native_decide]

-- ========== helper: hInitCut separate lemma (heartbeat workaround) ==========
lemma goal_65_hInitCut_helper (Ssm Spm : Store)
    (hinitC : InitGoalsHold pm.numRanks initGoals Ssm Spm)
    (hg2 : InitGoalHolds pm.numRanks goal_2 Ssm Spm)
    (hg3 : InitGoalHolds pm.numRanks goal_3 Ssm Spm)
    (hg4 : InitGoalHolds pm.numRanks goal_4 Ssm Spm)
    (hg5 : InitGoalHolds pm.numRanks goal_5 Ssm Spm)
    (hg6 : InitGoalHolds pm.numRanks goal_6 Ssm Spm)
    (hg7 : InitGoalHolds pm.numRanks goal_7 Ssm Spm)
    (hg8 : InitGoalHolds pm.numRanks goal_8 Ssm Spm)
    (hg9 : InitGoalHolds pm.numRanks goal_9 Ssm Spm)
    (hg10 : InitGoalHolds pm.numRanks goal_10 Ssm Spm)
    (hg11 : InitGoalHolds pm.numRanks goal_11 Ssm Spm)
    (hg12 : InitGoalHolds pm.numRanks goal_12 Ssm Spm)
    (hg13 : InitGoalHolds pm.numRanks goal_13 Ssm Spm)
    (hg14 : InitGoalHolds pm.numRanks goal_14 Ssm Spm)
    (hg15 : InitGoalHolds pm.numRanks goal_15 Ssm Spm)
    (hg16 : InitGoalHolds pm.numRanks goal_16 Ssm Spm)
    (hg17 : InitGoalHolds pm.numRanks goal_17 Ssm Spm)
    (hg18 : InitGoalHolds pm.numRanks goal_18 Ssm Spm)
    (hg19 : InitGoalHolds pm.numRanks goal_19 Ssm Spm)
    (hg20 : InitGoalHolds pm.numRanks goal_20 Ssm Spm)
    (hg21 : InitGoalHolds pm.numRanks goal_21 Ssm Spm)
    (hg22 : InitGoalHolds pm.numRanks goal_22 Ssm Spm)
    (hg23 : InitGoalHolds pm.numRanks goal_23 Ssm Spm)
    (hg24 : InitGoalHolds pm.numRanks goal_24 Ssm Spm)
    (hg25 : InitGoalHolds pm.numRanks goal_25 Ssm Spm)
    (hg26 : InitGoalHolds pm.numRanks goal_26 Ssm Spm)
    (hg27 : InitGoalHolds pm.numRanks goal_27 Ssm Spm)
    (hg28 : InitGoalHolds pm.numRanks goal_28 Ssm Spm)
    (hg29 : InitGoalHolds pm.numRanks goal_29 Ssm Spm)
    (hg30 : InitGoalHolds pm.numRanks goal_30 Ssm Spm)
    (hg31 : InitGoalHolds pm.numRanks goal_31 Ssm Spm)
    (hg32 : InitGoalHolds pm.numRanks goal_32 Ssm Spm)
    (hg33 : InitGoalHolds pm.numRanks goal_33 Ssm Spm)
    (hg34 : InitGoalHolds pm.numRanks goal_34 Ssm Spm)
    (hg35 : InitGoalHolds pm.numRanks goal_35 Ssm Spm)
    (hg36 : InitGoalHolds pm.numRanks goal_36 Ssm Spm)
    (hg37 : InitGoalHolds pm.numRanks goal_37 Ssm Spm)
    (hg38 : InitGoalHolds pm.numRanks goal_38 Ssm Spm)
    (hg39 : InitGoalHolds pm.numRanks goal_39 Ssm Spm)
    (hg40 : InitGoalHolds pm.numRanks goal_40 Ssm Spm)
    (hg41 : InitGoalHolds pm.numRanks goal_41 Ssm Spm)
    (hg42 : InitGoalHolds pm.numRanks goal_42 Ssm Spm)
    (hg43 : InitGoalHolds pm.numRanks goal_43 Ssm Spm)
    (hg44 : InitGoalHolds pm.numRanks goal_44 Ssm Spm)
    (hg45 : InitGoalHolds pm.numRanks goal_45 Ssm Spm)
    (hg46 : InitGoalHolds pm.numRanks goal_46 Ssm Spm)
    (hg47 : InitGoalHolds pm.numRanks goal_47 Ssm Spm)
    (hg48 : InitGoalHolds pm.numRanks goal_48 Ssm Spm)
    (hg49 : InitGoalHolds pm.numRanks goal_49 Ssm Spm)
    (hg50 : InitGoalHolds pm.numRanks goal_50 Ssm Spm)
    (hg51 : InitGoalHolds pm.numRanks goal_51 Ssm Spm)
    (hg52 : InitGoalHolds pm.numRanks goal_52 Ssm Spm)
    (hg53 : InitGoalHolds pm.numRanks goal_53 Ssm Spm)
    (hg54 : InitGoalHolds pm.numRanks goal_54 Ssm Spm)
    (hg55 : InitGoalHolds pm.numRanks goal_55 Ssm Spm)
    (hg57 : InitGoalHolds pm.numRanks goal_57 Ssm Spm)
    (hg61 : InitGoalHolds pm.numRanks goal_61 Ssm Spm)
    (hg62 : InitGoalHolds pm.numRanks goal_62 Ssm Spm)
    (hg257 : InitGoalHolds pm.numRanks goal_257 Ssm Spm)
    (hg259 : InitGoalHolds pm.numRanks goal_259 Ssm Spm)
    (hg261 : InitGoalHolds pm.numRanks goal_261 Ssm Spm)
    (hg263 : InitGoalHolds pm.numRanks goal_263 Ssm Spm)
    (hg265 : InitGoalHolds pm.numRanks goal_265 Ssm Spm)
    (hg267 : InitGoalHolds pm.numRanks goal_267 Ssm Spm)
    (hg269 : InitGoalHolds pm.numRanks goal_269 Ssm Spm)
    (hg271 : InitGoalHolds pm.numRanks goal_271 Ssm Spm)
    (hg273 : InitGoalHolds pm.numRanks goal_273 Ssm Spm)
    (hg275 : InitGoalHolds pm.numRanks goal_275 Ssm Spm)
    (hg277 : InitGoalHolds pm.numRanks goal_277 Ssm Spm)
    (hg279 : InitGoalHolds pm.numRanks goal_279 Ssm Spm)
    (hg281 : InitGoalHolds pm.numRanks goal_281 Ssm Spm)
    (hg283 : InitGoalHolds pm.numRanks goal_283 Ssm Spm)
    (hg285 : InitGoalHolds pm.numRanks goal_285 Ssm Spm)
    (hg291 : InitGoalHolds pm.numRanks goal_291 Ssm Spm) :
    InitGoalsHold pm_goal_65.numRanks goal_65_cut_initGoals Ssm Spm := by
  have hnr : pm_goal_65.numRanks = pm.numRanks := by native_decide
  rw [hnr]
  simp only [InitGoalsHold] at hinitC ⊢
  simp only [goal_65_cut_initGoals, goal_65_prereqs, List.forall_mem_append,
    List.forall_mem_cons, List.forall_mem_nil, and_true]
  exact ⟨hinitC, hg2, hg3, hg4, hg5, hg6, hg7, hg8, hg9, hg10, hg11, hg12, hg13, hg14, hg15, hg16, hg17, hg18, hg19, hg20, hg21, hg22, hg23, hg24, hg25, hg26, hg27, hg28, hg29, hg30, hg31, hg32, hg33, hg34, hg35, hg36, hg37, hg38, hg39, hg40, hg41, hg42, hg43, hg44, hg45, hg46, hg47, hg48, hg49, hg50, hg51, hg52, hg53, hg54, hg55, hg57, hg61, hg62, hg257, hg259, hg261, hg263, hg265, hg267, hg269, hg271, hg273, hg275, hg277, hg279, hg281, hg283, hg285, hg291, List.forall_mem_nil _⟩

-- ========== Assembly: goal_65_cut_to_full ==========
theorem goal_65_cut_to_full (h : goal_65_stmt_cut) : goal_65_stmt := by
  intro initSM initPM hSM hPM hInit
  set Ssm := denoteGraph sm initSM with hSsm
  set Spm := denoteGraph pm initPM with hSpm
  have hg2 := goal_2_intermediate initSM initPM hSM hPM hInit
  have hg3 := goal_3_intermediate initSM initPM hSM hPM hInit
  have hg4 := goal_4_intermediate initSM initPM hSM hPM hInit
  have hg5 := goal_5_intermediate initSM initPM hSM hPM hInit
  have hg6 := goal_6_intermediate initSM initPM hSM hPM hInit
  have hg7 := goal_7_intermediate initSM initPM hSM hPM hInit
  have hg8 := goal_8_intermediate initSM initPM hSM hPM hInit
  have hg9 := goal_9_intermediate initSM initPM hSM hPM hInit
  have hg10 := goal_10_intermediate initSM initPM hSM hPM hInit
  have hg11 := goal_11_intermediate initSM initPM hSM hPM hInit
  have hg12 := goal_12_intermediate initSM initPM hSM hPM hInit
  have hg13 := goal_13_intermediate initSM initPM hSM hPM hInit
  have hg14 := goal_14_intermediate initSM initPM hSM hPM hInit
  have hg15 := goal_15_intermediate initSM initPM hSM hPM hInit
  have hg16 := goal_16_intermediate initSM initPM hSM hPM hInit
  have hg17 := goal_17_intermediate initSM initPM hSM hPM hInit
  have hg18 := goal_18_intermediate initSM initPM hSM hPM hInit
  have hg19 := goal_19_intermediate initSM initPM hSM hPM hInit
  have hg20 := goal_20_intermediate initSM initPM hSM hPM hInit
  have hg21 := goal_21_intermediate initSM initPM hSM hPM hInit
  have hg22 := goal_22_intermediate initSM initPM hSM hPM hInit
  have hg23 := goal_23_intermediate initSM initPM hSM hPM hInit
  have hg24 := goal_24_intermediate initSM initPM hSM hPM hInit
  have hg25 := goal_25_intermediate initSM initPM hSM hPM hInit
  have hg26 := goal_26_intermediate initSM initPM hSM hPM hInit
  have hg27 := goal_27_intermediate initSM initPM hSM hPM hInit
  have hg28 := goal_28_intermediate initSM initPM hSM hPM hInit
  have hg29 := goal_29_intermediate initSM initPM hSM hPM hInit
  have hg30 := goal_30_intermediate initSM initPM hSM hPM hInit
  have hg31 := goal_31_intermediate initSM initPM hSM hPM hInit
  have hg32 := goal_32_intermediate initSM initPM hSM hPM hInit
  have hg33 := goal_33_intermediate initSM initPM hSM hPM hInit
  have hg34 := goal_34_intermediate initSM initPM hSM hPM hInit
  have hg35 := goal_35_intermediate initSM initPM hSM hPM hInit
  have hg36 := goal_36_intermediate initSM initPM hSM hPM hInit
  have hg37 := goal_37_intermediate initSM initPM hSM hPM hInit
  have hg38 := goal_38_intermediate initSM initPM hSM hPM hInit
  have hg39 := goal_39_intermediate initSM initPM hSM hPM hInit
  have hg40 := goal_40_intermediate initSM initPM hSM hPM hInit
  have hg41 := goal_41_intermediate initSM initPM hSM hPM hInit
  have hg42 := goal_42_intermediate initSM initPM hSM hPM hInit
  have hg43 := goal_43_intermediate initSM initPM hSM hPM hInit
  have hg44 := goal_44_intermediate initSM initPM hSM hPM hInit
  have hg45 := goal_45_intermediate initSM initPM hSM hPM hInit
  have hg46 := goal_46_intermediate initSM initPM hSM hPM hInit
  have hg47 := goal_47_intermediate initSM initPM hSM hPM hInit
  have hg48 := goal_48_intermediate initSM initPM hSM hPM hInit
  have hg49 := goal_49_intermediate initSM initPM hSM hPM hInit
  have hg50 := goal_50_intermediate initSM initPM hSM hPM hInit
  have hg51 := goal_51_intermediate initSM initPM hSM hPM hInit
  have hg52 := goal_52_intermediate initSM initPM hSM hPM hInit
  have hg53 := goal_53_intermediate initSM initPM hSM hPM hInit
  have hg54 := goal_54_intermediate initSM initPM hSM hPM hInit
  have hg55 := goal_55_intermediate initSM initPM hSM hPM hInit
  have hg57 := goal_57_intermediate initSM initPM hSM hPM hInit
  have hg61 := goal_61_intermediate initSM initPM hSM hPM hInit
  have hg62 := goal_62_intermediate initSM initPM hSM hPM hInit
  have hg257 := goal_257_intermediate initSM initPM hSM hPM hInit
  have hg259 := goal_259_intermediate initSM initPM hSM hPM hInit
  have hg261 := goal_261_intermediate initSM initPM hSM hPM hInit
  have hg263 := goal_263_intermediate initSM initPM hSM hPM hInit
  have hg265 := goal_265_intermediate initSM initPM hSM hPM hInit
  have hg267 := goal_267_intermediate initSM initPM hSM hPM hInit
  have hg269 := goal_269_intermediate initSM initPM hSM hPM hInit
  have hg271 := goal_271_intermediate initSM initPM hSM hPM hInit
  have hg273 := goal_273_intermediate initSM initPM hSM hPM hInit
  have hg275 := goal_275_intermediate initSM initPM hSM hPM hInit
  have hg277 := goal_277_intermediate initSM initPM hSM hPM hInit
  have hg279 := goal_279_intermediate initSM initPM hSM hPM hInit
  have hg281 := goal_281_intermediate initSM initPM hSM hPM hInit
  have hg283 := goal_283_intermediate initSM initPM hSM hPM hInit
  have hg285 := goal_285_intermediate initSM initPM hSM hPM hInit
  have hg291 := goal_291_intermediate initSM initPM hSM hPM hInit
  have hinitC := initGoals_preserved initSM initPM hInit
  have hnr : pm_goal_65.numRanks = pm.numRanks := by native_decide
  have h650_smsh : (Ssm 650).shape = [1, 4, 8, 8] := by
    have h := hg62.1; simp only [goal_62] at h; exact h
  have h62tp := hg62.2.1
  simp only [goal_62, List.map, List.cons.injEq, and_true] at h62tp
  obtain ⟨h2369_pmsh, h2370_pmsh, h2371_pmsh, h2372_pmsh⟩ := h62tp
  have hSM65 : StoreShapesHold Ssm sm_goal_65InitEnv := by
    intro tid sh hsh
    rw [sm_goal_65InitEnv] at hsh
    have hmem := mem_of_shapeEnvOfList_eq_some hsh
    simp only [sm_goal_65InitShapes, List.mem_cons, List.not_mem_nil, or_false,
               Prod.mk.injEq] at hmem
    rcases hmem with ⟨rfl, rfl⟩
    · exact h650_smsh
  have hPM65 : StoreShapesHold Spm pm_goal_65InitEnv := by
    intro tid sh hsh
    rw [pm_goal_65InitEnv] at hsh
    have hmem := mem_of_shapeEnvOfList_eq_some hsh
    simp only [pm_goal_65InitShapes, List.mem_cons, List.not_mem_nil, or_false,
               Prod.mk.injEq] at hmem
    rcases hmem with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact h2369_pmsh
    · exact h2370_pmsh
    · exact h2371_pmsh
    · exact h2372_pmsh

  have hInitCut : InitGoalsHold pm_goal_65.numRanks goal_65_cut_initGoals Ssm Spm :=
    goal_65_hInitCut_helper Ssm Spm hinitC hg2 hg3 hg4 hg5 hg6 hg7 hg8 hg9 hg10 hg11 hg12 hg13 hg14 hg15 hg16 hg17 hg18 hg19 hg20 hg21 hg22 hg23 hg24 hg25 hg26 hg27 hg28 hg29 hg30 hg31 hg32 hg33 hg34 hg35 hg36 hg37 hg38 hg39 hg40 hg41 hg42 hg43 hg44 hg45 hg46 hg47 hg48 hg49 hg50 hg51 hg52 hg53 hg54 hg55 hg57 hg61 hg62 hg257 hg259 hg261 hg263 hg265 hg267 hg269 hg271 hg273 hg275 hg277 hg279 hg281 hg283 hg285 hg291
  have hcut := h Ssm Spm hSM65 hPM65 hInitCut
  have hsmf : Ssm 653 = denoteGraph sm_goal_65 Ssm 653 := by
    rw [hSsm]; exact sm_frame_653_self initSM
  have hpm653 : Spm 653 = denoteGraph pm_goal_65 Spm 653 := by
    rw [denote_pm_goal_65_653]; rw [hSpm]; exact pm_frame_653_self initPM
  rw [hnr] at hcut
  simp only [goal_65, List.map] at hcut ⊢
  rw [hsmf, hpm653]
  exact hcut

theorem goal_65_intermediate (initSM initPM : Store)
    (hSM : StoreShapesHold initSM smInitEnv) (hPM : StoreShapesHold initPM pmInitEnv)
    (hInit : InitGoalsHold pm.numRanks initGoals initSM initPM) :
    InitGoalHolds pm.numRanks goal_65 (denoteGraph sm initSM) (denoteGraph pm initPM) := by
  have hfull : goal_65_stmt := goal_65_cut_to_full prove_goal_65_cut
  have := hfull initSM initPM hSM hPM hInit
  simpa [InitGoalHolds, goal_65] using this

end TrainVerify.Denote.GeneratedGoals
