/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 32 (tensor id: 609)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_32 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [965, 608], outs := [609] },
  ]

def pm_goal_32 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [1721, 608], outs := [1725] },
    { rank := 1, op := "OpName.FW_linear", ins := [1722, 608], outs := [1726] },
    { rank := 2, op := "OpName.FW_linear", ins := [1723, 608], outs := [1727] },
    { rank := 3, op := "OpName.FW_linear", ins := [1724, 608], outs := [1728] },
    { rank := 0, op := "OpName.AllGatherPrim", ins := [1725, 1726, 1727, 1728], outs := [609], params := [1] },
  ]

def sm_goal_32InitShapes : List (Tid × Shape) := [
  (608, [32, 32]),
  (965, [1, 8, 32]),
]

def sm_goal_32InitEnv : ShapeEnv := shapeEnvOfList sm_goal_32InitShapes

def pm_goal_32InitShapes : List (Tid × Shape) := [
  (608, [32, 32]),
  (1721, [1, 2, 32]),
  (1722, [1, 2, 32]),
  (1723, [1, 2, 32]),
  (1724, [1, 2, 32]),
]

def pm_goal_32InitEnv : ShapeEnv := shapeEnvOfList pm_goal_32InitShapes

def goal_32_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_277]
def goal_32_cut_initGoals : List LineageGoal := initGoals ++ goal_32_prereqs

def goal_32_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_32 pm_goal_32 goal_32 sm_goal_32InitEnv pm_goal_32InitEnv goal_32_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

