/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 202 (tensor id: 832)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_202 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_contiguous", ins := [833, 658], outs := [832] },
  ]

def pm_goal_202 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.AllToAllPrim", ins := [2533, 2534, 2535, 2536], outs := [2553], params := [1, 3] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [2533, 2534, 2535, 2536], outs := [2554], params := [1, 3] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [2533, 2534, 2535, 2536], outs := [2555], params := [1, 3] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [2533, 2534, 2535, 2536], outs := [2556], params := [1, 3] },
    { rank := 0, op := "OpName.ChunkPrim", ins := [833], outs := [2570], params := [3] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [833], outs := [2572], params := [3] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [833], outs := [2574], params := [3] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [833], outs := [2576], params := [3] },
    { rank := 0, op := "OpName.BW_contiguous", ins := [2570, 2553], outs := [2569] },
    { rank := 1, op := "OpName.BW_contiguous", ins := [2572, 2554], outs := [2571] },
    { rank := 2, op := "OpName.BW_contiguous", ins := [2574, 2555], outs := [2573] },
    { rank := 3, op := "OpName.BW_contiguous", ins := [2576, 2556], outs := [2575] },
    { rank := 0, op := "OpName.AllToAllPrim", ins := [2569, 2571, 2573, 2575], outs := [2546], params := [3, 1] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [2569, 2571, 2573, 2575], outs := [2548], params := [3, 1] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [2569, 2571, 2573, 2575], outs := [2550], params := [3, 1] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [2569, 2571, 2573, 2575], outs := [2552], params := [3, 1] },
  ]

def sm_goal_202InitShapes : List (Tid × Shape) := [
  (658, [1, 8, 4, 8]),
  (833, [1, 8, 4, 8]),
]

def sm_goal_202InitEnv : ShapeEnv := shapeEnvOfList sm_goal_202InitShapes

def pm_goal_202InitShapes : List (Tid × Shape) := [
  (833, [1, 8, 4, 8]),
  (2533, [1, 2, 4, 8]),
  (2534, [1, 2, 4, 8]),
  (2535, [1, 2, 4, 8]),
  (2536, [1, 2, 4, 8]),
]

def pm_goal_202InitEnv : ShapeEnv := shapeEnvOfList pm_goal_202InitShapes

def goal_202_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_105, goal_106, goal_203, goal_204, goal_206, goal_207, goal_210, goal_212, goal_213, goal_215, goal_216, goal_219, goal_221, goal_223, goal_225, goal_226, goal_227, goal_228, goal_229, goal_230, goal_231, goal_232, goal_233, goal_234, goal_235, goal_236, goal_237, goal_238, goal_239, goal_241, goal_242, goal_245, goal_247, goal_248, goal_250, goal_251, goal_254, goal_256, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_287, goal_289, goal_291, goal_293, goal_295, goal_296, goal_297, goal_298, goal_299, goal_300, goal_301, goal_302, goal_303, goal_304, goal_305, goal_306, goal_307, goal_308, goal_309, goal_310, goal_311, goal_312]
def goal_202_cut_initGoals : List LineageGoal := initGoals ++ goal_202_prereqs

def goal_202_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_202 pm_goal_202 goal_202 sm_goal_202InitEnv pm_goal_202InitEnv goal_202_cut_initGoals

set_option maxRecDepth 4096 in
set_option maxHeartbeats 1600000 in
-- BW_contiguous is the gradient passthrough (identity on its first input).  The PM graph
-- first re-shards along dim 3 (AllToAll [1,3] then chunk-3), applies BW_contiguous locally,
-- then re-shards back along dim 1 (AllToAll [3,1]).  Since BW_contiguous keeps the (dim-3)
-- chunk of the gradient 833, gathering along dim 3 recovers 833 and the per-rank outputs are
-- the dim-1 chunks of 833, whose reconstruction along dim 1 is exactly the SM output.
theorem prove_goal_202_cut : goal_202_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  -- Prereq goal_203: gradient 833 is replicated (single tp) → initSM 833 = initPM 833
  have hInit203 : InitGoalHolds pm_goal_202.numRanks goal_203 initSM initPM := by
    apply hInitGoals
    simp only [goal_202_cut_initGoals, goal_202_prereqs]
    decide
  have h833_eq : initSM 833 = initPM 833 := by
    have hrec := hInit203.2.2
    simp only [goal_203, pm_goal_202, List.map] at hrec
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] at hrec | skip
    rw [reconstructWithDim_singleton] at hrec
    exact hrec
  have h833_shape : (initSM 833).shape = [1, 8, 4, 8] := hInit203.1
  have h833_shapeP : (initPM 833).shape = [1, 8, 4, 8] := by rw [← h833_eq]; exact h833_shape
  -- SM store: BW_contiguous(833, 658) = 833
  have hsm : (denoteGraph sm_goal_202 initSM) 832 = initSM 833 := by
    simp only [sm_goal_202, denoteGraph, List.foldl]
    rw [applyNode_bw_contiguous_out_g202]
  -- The final per-rank AllToAll [3,1] of the dim-3 chunks of 833 = dim-1 chunk of 833
  have hata : ∀ r, allToAllPrimWithDims 4 r
      [chunkPrimDimN 3 4 0 (initPM 833), chunkPrimDimN 3 4 1 (initPM 833),
       chunkPrimDimN 3 4 2 (initPM 833), chunkPrimDimN 3 4 3 (initPM 833)] 3 1 =
      chunkPrimDimN 1 4 r (initPM 833) := by
    intro r
    simp only [allToAllPrimWithDims]
    rw [allGatherPrimDimN_chunkPrimDimN_id_dim3_1_8_4_8_g202 (initPM 833) h833_shapeP]
  -- PM stores (per rank): unfold the 16-node fold to the final AllToAll
  have hpm0 : (denoteGraph pm_goal_202 initPM) 2546 = chunkPrimDimN 1 4 0 (initPM 833) := by
    simp only [pm_goal_202, denoteGraph, GraphDecl.nodes, List.foldl]
    rw [applyNode_eq_of_not_mem_outs (h := by decide)]
    rw [applyNode_eq_of_not_mem_outs (h := by decide)]
    rw [applyNode_eq_of_not_mem_outs (h := by decide)]
    rw [applyNode_allToAllPrimWithDims_out]
    rw [show (([2569, 2571, 2573, 2575] : List Tid)).map _ =
        [chunkPrimDimN 3 4 0 (initPM 833), chunkPrimDimN 3 4 1 (initPM 833),
         chunkPrimDimN 3 4 2 (initPM 833), chunkPrimDimN 3 4 3 (initPM 833)] from rfl]
    exact hata 0
  have hpm1 : (denoteGraph pm_goal_202 initPM) 2548 = chunkPrimDimN 1 4 1 (initPM 833) := by
    simp only [pm_goal_202, denoteGraph, GraphDecl.nodes, List.foldl]
    rw [applyNode_eq_of_not_mem_outs (h := by decide)]
    rw [applyNode_eq_of_not_mem_outs (h := by decide)]
    rw [applyNode_allToAllPrimWithDims_out]
    rw [show (([2569, 2571, 2573, 2575] : List Tid)).map _ =
        [chunkPrimDimN 3 4 0 (initPM 833), chunkPrimDimN 3 4 1 (initPM 833),
         chunkPrimDimN 3 4 2 (initPM 833), chunkPrimDimN 3 4 3 (initPM 833)] from rfl]
    exact hata 1
  have hpm2 : (denoteGraph pm_goal_202 initPM) 2550 = chunkPrimDimN 1 4 2 (initPM 833) := by
    simp only [pm_goal_202, denoteGraph, GraphDecl.nodes, List.foldl]
    rw [applyNode_eq_of_not_mem_outs (h := by decide)]
    rw [applyNode_allToAllPrimWithDims_out]
    rw [show (([2569, 2571, 2573, 2575] : List Tid)).map _ =
        [chunkPrimDimN 3 4 0 (initPM 833), chunkPrimDimN 3 4 1 (initPM 833),
         chunkPrimDimN 3 4 2 (initPM 833), chunkPrimDimN 3 4 3 (initPM 833)] from rfl]
    exact hata 2
  have hpm3 : (denoteGraph pm_goal_202 initPM) 2552 = chunkPrimDimN 1 4 3 (initPM 833) := by
    simp only [pm_goal_202, denoteGraph, GraphDecl.nodes, List.foldl]
    rw [applyNode_allToAllPrimWithDims_out]
    rw [show (([2569, 2571, 2573, 2575] : List Tid)).map _ =
        [chunkPrimDimN 3 4 0 (initPM 833), chunkPrimDimN 3 4 1 (initPM 833),
         chunkPrimDimN 3 4 2 (initPM 833), chunkPrimDimN 3 4 3 (initPM 833)] from rfl]
    exact hata 3
  -- Chunk shapes [1,2,4,8]
  have hc : ∀ r, (chunkPrimDimN 1 4 r (initPM 833)).shape = [1, 2, 4, 8] := by
    intro r
    rw [chunkPrimDimN_shape 1 4 r _ _ h833_shapeP (by omega)]; simp [List.set, List.getD]
  -- Discharge the three conjuncts
  simp only [goal_202, List.map]
  refine ⟨?_, ?_, ?_⟩
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    rw [hsm]; exact h833_shape
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    rw [hpm0, hpm1, hpm2, hpm3, hc 0, hc 1, hc 2, hc 3]
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    rw [hsm, hpm0, hpm1, hpm2, hpm3]
    change initSM 833 = reconstructWithDim 1 4 0
      [chunkPrimDimN 1 4 0 (initPM 833), chunkPrimDimN 1 4 1 (initPM 833),
       chunkPrimDimN 1 4 2 (initPM 833), chunkPrimDimN 1 4 3 (initPM 833)]
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    rw [reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _ (by rw [hc 0]; decide)]
    rw [allGatherPrimDimN_chunkPrimDimN_id_dim1_1_8_4_8_g202 (initPM 833) h833_shapeP]
    exact h833_eq

end TrainVerify.Denote.GeneratedGoals


