/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 224 (tensor id: 861)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_224 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_linear", ins := [862, 1055, 680], outs := [1056, 861] },
  ]

def pm_goal_224 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.ChunkPrim", ins := [862], outs := [2887], params := [1] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [862], outs := [2890], params := [1] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [862], outs := [2893], params := [1] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [862], outs := [2896], params := [1] },
    { rank := 0, op := "OpName.BW_linear", ins := [2887, 2869, 680], outs := [2885, 2886] },
    { rank := 1, op := "OpName.BW_linear", ins := [2890, 2870, 680], outs := [2888, 2889] },
    { rank := 2, op := "OpName.BW_linear", ins := [2893, 2871, 680], outs := [2891, 2892] },
    { rank := 3, op := "OpName.BW_linear", ins := [2896, 2872, 680], outs := [2894, 2895] },
    { rank := 0, op := "OpName.CROSS_DP_WRED", ins := [2886, 2889, 2892, 2895], outs := [2886] },
  ]

def sm_goal_224InitShapes : List (Tid × Shape) := [
  (680, [32, 32]),
  (862, [1, 8, 32]),
  (1055, [1, 8, 32]),
]

def sm_goal_224InitEnv : ShapeEnv := shapeEnvOfList sm_goal_224InitShapes

def pm_goal_224InitShapes : List (Tid × Shape) := [
  (680, [32, 32]),
  (862, [1, 8, 32]),
  (2869, [1, 2, 32]),
  (2870, [1, 2, 32]),
  (2871, [1, 2, 32]),
  (2872, [1, 2, 32]),
]

def pm_goal_224InitEnv : ShapeEnv := shapeEnvOfList pm_goal_224InitShapes

def goal_224_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_105, goal_106, goal_225, goal_230, goal_231, goal_236, goal_237, goal_238, goal_239, goal_241, goal_242, goal_245, goal_247, goal_248, goal_250, goal_251, goal_254, goal_256, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_287, goal_289, goal_291, goal_293, goal_295, goal_297, goal_299, goal_301, goal_303, goal_305, goal_307, goal_309, goal_310, goal_311, goal_312]
def goal_224_cut_initGoals : List LineageGoal := initGoals ++ goal_224_prereqs

def goal_224_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_224 pm_goal_224 goal_224 sm_goal_224InitEnv pm_goal_224InitEnv goal_224_cut_initGoals

theorem prove_goal_224_cut : goal_224_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  -- Extract prereqs: goal_307 (x=1055 gather), goal_225 (g=862 shared), initGoal_680 (w)
  have hInit307 : InitGoalHolds pm_goal_224.numRanks goal_307 initSM initPM := by
    apply hInitGoals; simp only [goal_224_cut_initGoals, goal_224_prereqs]; decide
  have hInit225 : InitGoalHolds pm_goal_224.numRanks goal_225 initSM initPM := by
    apply hInitGoals; simp only [goal_224_cut_initGoals, goal_224_prereqs]; decide
  have hInit680 : InitGoalHolds pm_goal_224.numRanks initGoal_680 initSM initPM := by
    apply hInitGoals; simp only [goal_224_cut_initGoals, goal_224_prereqs, initGoals]; decide
  -- goal_307: initSM 1055 = reconstructWithDim 1 4 0 [2869,2870,2871,2872]
  have h1055_rec : initSM 1055 = reconstructWithDim 1 4 0
      [initPM 2869, initPM 2870, initPM 2871, initPM 2872] := by
    have hrec := hInit307.2.2
    simp only [goal_307, pm_goal_224, List.map] at hrec
    exact hrec
  have htp307 := hInit307.2.1
  simp only [goal_307, List.map] at htp307
  have h2869_shape : (initPM 2869).shape = [1, 2, 32] := by
    have := congrArg List.head? htp307; simpa using this
  have h2870_shape : (initPM 2870).shape = [1, 2, 32] := by
    have := congrArg (List.head? ∘ List.tail) htp307; simpa using this
  have h2871_shape : (initPM 2871).shape = [1, 2, 32] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail) htp307; simpa using this
  have h2872_shape : (initPM 2872).shape = [1, 2, 32] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail ∘ List.tail) htp307; simpa using this
  -- goal_225: initSM 862 = initPM 862 (singleton)
  have h862_eq : initSM 862 = initPM 862 := by
    have hrec := hInit225.2.2
    simp only [goal_225, pm_goal_224, List.map] at hrec
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] at hrec | skip
    rw [reconstructWithDim_singleton] at hrec; exact hrec
  have h862_shape : (initSM 862).shape = [1, 8, 32] := hInit225.1
  -- initGoal_680: initSM 680 = initPM 680 (replicated)
  have h680_eq : initSM 680 = initPM 680 := by
    have hrec := hInit680.2.2
    simp only [initGoal_680, pm_goal_224, List.map] at hrec
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] at hrec | skip
    rw [reconstructWithDim_singleton] at hrec; exact hrec
  have h680_shape : (initSM 680).shape = [32, 32] := hInit680.1
  -- shapes of shared init tensors on PM side
  have h862_shapeP : (initPM 862).shape = [1, 8, 32] := by rw [← h862_eq]; exact h862_shape
  have h680_shapeP : (initPM 680).shape = [32, 32] := by rw [← h680_eq]; exact h680_shape
  have hchunk0_shape : (chunkPrimDimN 1 4 0 (initPM 862)).shape = [1, 2, 32] := by
    rw [chunkPrimDimN_shape 1 4 0 (initPM 862) _ h862_shapeP (by omega)]; simp [List.set, List.getD]
  -- convert reconstruct to allGather (non-scalar shards)
  have h1055_gather : initSM 1055 = allGatherPrimDimN 1 4 0
      [initPM 2869, initPM 2870, initPM 2871, initPM 2872] := by
    rw [h1055_rec]
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    exact reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _ (by rw [h2869_shape]; decide)
  -- SM store: dW (output index 1) of BW_linear on full tensors
  have hsm : (denoteGraph sm_goal_224 initSM) 861 =
      (bw_linear (initSM 862) (initSM 1055) (initSM 680)).2 := by
    simp only [sm_goal_224, denoteGraph, List.foldl]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
  -- PM store: 4 ChunkPrim + 4 BW_linear, then CROSS_DP_WRED sums the dW outputs
  have hpm : (denoteGraph pm_goal_224 initPM) 2886 =
      cross_dp_wred
        [(bw_linear (chunkPrimDimN 1 4 0 (initPM 862)) (initPM 2869) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 1 (initPM 862)) (initPM 2870) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 2 (initPM 862)) (initPM 2871) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 3 (initPM 862)) (initPM 2872) (initPM 680)).2] := by
    simp only [pm_goal_224, denoteGraph, List.foldl]
    rw [applyNode_cross_dp_wred_out]
    congr 1
  -- Key equation: SM dW = DP reduction of per-rank PM dW
  have hkey : (bw_linear (initSM 862) (initSM 1055) (initSM 680)).2 =
      cross_dp_wred
        [(bw_linear (chunkPrimDimN 1 4 0 (initPM 862)) (initPM 2869) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 1 (initPM 862)) (initPM 2870) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 2 (initPM 862)) (initPM 2871) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 3 (initPM 862)) (initPM 2872) (initPM 680)).2] := by
    rw [h1055_gather, h862_eq, h680_eq]
    unfold cross_dp_wred
    exact bw_linear_dw_dp_split_dim1_4_1_2_32 (initPM 862)
      (initPM 2869) (initPM 2870) (initPM 2871) (initPM 2872) (initPM 680)
      h862_shapeP h2869_shape h2870_shape h2871_shape h2872_shape h680_shapeP
  -- Discharge the three conjuncts
  simp only [goal_224, List.map]
  refine ⟨?_, ?_, ?_⟩
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    -- SM output shape: [32, 32]
    rw [hsm, hkey]; unfold cross_dp_wred
    rw [tensorSum_shape,
        bw_linear_3d_snd_shape 1 2 32 32 (chunkPrimDimN 1 4 0 (initPM 862))
          (initPM 2869) (initPM 680) hchunk0_shape h2869_shape h680_shapeP]
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    -- PM tp shapes: [[32, 32]]
    rw [hpm]; unfold cross_dp_wred
    rw [show [(tensorSum
        [(bw_linear (chunkPrimDimN 1 4 0 (initPM 862)) (initPM 2869) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 1 (initPM 862)) (initPM 2870) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 2 (initPM 862)) (initPM 2871) (initPM 680)).2,
         (bw_linear (chunkPrimDimN 1 4 3 (initPM 862)) (initPM 2872) (initPM 680)).2]).shape]
        = [[32, 32]] from by
      rw [tensorSum_shape,
          bw_linear_3d_snd_shape 1 2 32 32 (chunkPrimDimN 1 4 0 (initPM 862))
            (initPM 2869) (initPM 680) hchunk0_shape h2869_shape h680_shapeP]]
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    -- Value equality: smStore 861 = reconstructWithDim 0 4 0 [pmStore 2886]
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    rw [hsm, hkey, ← hpm, reconstructWithDim_singleton]

end TrainVerify.Denote.GeneratedGoals


