/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 23 (tensor id: 592)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_23 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [590, 591], outs := [592] },
  ]

def pm_goal_23 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [590, 1473], outs := [1477] },
    { rank := 1, op := "OpName.FW_linear", ins := [590, 1474], outs := [1478] },
    { rank := 2, op := "OpName.FW_linear", ins := [590, 1475], outs := [1479] },
    { rank := 3, op := "OpName.FW_linear", ins := [590, 1476], outs := [1480] },
  ]

def sm_goal_23InitShapes : List (Tid × Shape) := [
  (590, [1, 8, 32]),
  (591, [32, 32]),
]

def sm_goal_23InitEnv : ShapeEnv := shapeEnvOfList sm_goal_23InitShapes

def pm_goal_23InitShapes : List (Tid × Shape) := [
  (590, [1, 8, 32]),
  (1473, [8, 32]),
  (1474, [8, 32]),
  (1475, [8, 32]),
  (1476, [8, 32]),
]

def pm_goal_23InitEnv : ShapeEnv := shapeEnvOfList pm_goal_23InitShapes

def goal_23_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_257, goal_261, goal_263, goal_265]
def goal_23_cut_initGoals : List LineageGoal := initGoals ++ goal_23_prereqs

def goal_23_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_23 pm_goal_23 goal_23 sm_goal_23InitEnv pm_goal_23InitEnv goal_23_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

