/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 292 (tensor id: 1009)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_292 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_linear", ins := [818, 1008, 643], outs := [1009, 817] },
  ]

def pm_goal_292 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.ChunkPrim", ins := [818], outs := [2303], params := [2] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [818], outs := [2306], params := [2] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [818], outs := [2309], params := [2] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [818], outs := [2312], params := [2] },
    { rank := 0, op := "OpName.BW_linear", ins := [2303, 1000, 2285], outs := [2310, 2302] },
    { rank := 1, op := "OpName.BW_linear", ins := [2306, 1000, 2286], outs := [2307, 2305] },
    { rank := 2, op := "OpName.BW_linear", ins := [2309, 1000, 2287], outs := [2304, 2308] },
    { rank := 3, op := "OpName.BW_linear", ins := [2312, 1000, 2288], outs := [2301, 2311] },
    { rank := 0, op := "OpName.AllReducePrim", ins := [2310, 2307, 2304, 2301], outs := [1009] },
  ]

def sm_goal_292InitShapes : List (Tid × Shape) := [
  (643, [32, 32]),
  (818, [1, 8, 32]),
  (1008, [1, 8, 32]),
]

def sm_goal_292InitEnv : ShapeEnv := shapeEnvOfList sm_goal_292InitShapes

def pm_goal_292InitShapes : List (Tid × Shape) := [
  (818, [1, 8, 32]),
  (1000, [1, 8, 32]),
  (2285, [8, 32]),
  (2286, [8, 32]),
  (2287, [8, 32]),
  (2288, [8, 32]),
]

def pm_goal_292InitEnv : ShapeEnv := shapeEnvOfList pm_goal_292InitShapes

def goal_292_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_105, goal_106, goal_188, goal_193, goal_194, goal_197, goal_198, goal_199, goal_200, goal_201, goal_202, goal_203, goal_204, goal_206, goal_207, goal_210, goal_212, goal_213, goal_215, goal_216, goal_219, goal_221, goal_223, goal_225, goal_226, goal_227, goal_228, goal_229, goal_230, goal_231, goal_232, goal_233, goal_234, goal_235, goal_236, goal_237, goal_238, goal_239, goal_241, goal_242, goal_245, goal_247, goal_248, goal_250, goal_251, goal_254, goal_256, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_287, goal_289, goal_291, goal_293, goal_295, goal_296, goal_297, goal_298, goal_299, goal_300, goal_301, goal_302, goal_303, goal_304, goal_305, goal_306, goal_307, goal_308, goal_309, goal_310, goal_311, goal_312]
def goal_292_cut_initGoals : List LineageGoal := initGoals ++ goal_292_prereqs

def goal_292_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_292 pm_goal_292 goal_292 sm_goal_292InitEnv pm_goal_292InitEnv goal_292_cut_initGoals

theorem prove_goal_292_cut : goal_292_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  -- Extract prereqs: goal_188 (g=818 shared), goal_291 (x: 1008→1000 shared),
  -- initGoal_643 (w=643 gather dim0).
  have hInit188 : InitGoalHolds pm_goal_292.numRanks goal_188 initSM initPM := by
    apply hInitGoals; simp only [goal_292_cut_initGoals, goal_292_prereqs]; decide
  have hInit291 : InitGoalHolds pm_goal_292.numRanks goal_291 initSM initPM := by
    apply hInitGoals; simp only [goal_292_cut_initGoals, goal_292_prereqs]; decide
  have hInit643 : InitGoalHolds pm_goal_292.numRanks initGoal_643 initSM initPM := by
    apply hInitGoals; simp only [goal_292_cut_initGoals, goal_292_prereqs, initGoals]; decide
  -- goal_188: g=818 shared (singleton)
  have h818_eq : initSM 818 = initPM 818 := by
    have hrec := hInit188.2.2
    simp only [goal_188, pm_goal_292, List.map] at hrec
    rw [reconstructWithDim_singleton] at hrec; exact hrec
  have h818_shape : (initSM 818).shape = [1, 8, 32] := hInit188.1
  have h818_shapeP : (initPM 818).shape = [1, 8, 32] := by rw [← h818_eq]; exact h818_shape
  -- goal_291: x=1008 (SM) = 1000 (PM) shared (singleton)
  have h1008_eq : initSM 1008 = initPM 1000 := by
    have hrec := hInit291.2.2
    simp only [goal_291, pm_goal_292, List.map] at hrec
    rw [reconstructWithDim_singleton] at hrec; exact hrec
  have h1008_shape : (initSM 1008).shape = [1, 8, 32] := hInit291.1
  have h1000_shapeP : (initPM 1000).shape = [1, 8, 32] := by rw [← h1008_eq]; exact h1008_shape
  -- initGoal_643: w=643 gather dim0 into [8,32] shards
  have htp643 := hInit643.2.1
  simp only [initGoal_643, List.map] at htp643
  have h2285_shape : (initPM 2285).shape = [8, 32] := by
    have := congrArg List.head? htp643; simpa using this
  have h2286_shape : (initPM 2286).shape = [8, 32] := by
    have := congrArg (List.head? ∘ List.tail) htp643; simpa using this
  have h2287_shape : (initPM 2287).shape = [8, 32] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail) htp643; simpa using this
  have h2288_shape : (initPM 2288).shape = [8, 32] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail ∘ List.tail) htp643; simpa using this
  have h643_rec : initSM 643 = reconstructWithDim 0 4 0
      [initPM 2285, initPM 2286, initPM 2287, initPM 2288] := by
    have hrec := hInit643.2.2
    simp only [initGoal_643, pm_goal_292, List.map] at hrec
    exact hrec
  have h643_gather : initSM 643 = allGatherPrimDimN 0 4 0
      [initPM 2285, initPM 2286, initPM 2287, initPM 2288] := by
    rw [h643_rec]
    exact reconstructWithDim_cons_cons_nonscalar 0 4 0 _ _ _ (by rw [h2285_shape]; decide)
  -- shapes of the four chunks of g=818 (dim 2)
  have hc0 : (chunkPrimDimN 2 4 0 (initPM 818)).shape = [1, 8, 8] := by
    rw [chunkPrimDimN_shape 2 4 0 _ _ h818_shapeP (by omega)]; simp [List.set, List.getD]
  have hc1 : (chunkPrimDimN 2 4 1 (initPM 818)).shape = [1, 8, 8] := by
    rw [chunkPrimDimN_shape 2 4 1 _ _ h818_shapeP (by omega)]; simp [List.set, List.getD]
  have hc2 : (chunkPrimDimN 2 4 2 (initPM 818)).shape = [1, 8, 8] := by
    rw [chunkPrimDimN_shape 2 4 2 _ _ h818_shapeP (by omega)]; simp [List.set, List.getD]
  have hc3 : (chunkPrimDimN 2 4 3 (initPM 818)).shape = [1, 8, 8] := by
    rw [chunkPrimDimN_shape 2 4 3 _ _ h818_shapeP (by omega)]; simp [List.set, List.getD]
  -- SM store: dX (output index 0) of BW_linear on full tensors
  have hsm : (denoteGraph sm_goal_292 initSM) 1009 =
      (bw_linear (initSM 818) (initSM 1008) (initSM 643)).1 := by
    simp only [sm_goal_292, denoteGraph, List.foldl]
    rw [applyNode_bw_linear_fst_out _ _ _ _ _ _ _ _ (by decide)]
  -- PM store: 4 ChunkPrim + 4 BW_linear (dX outputs), then AllReducePrim sums them
  have hpm : (denoteGraph pm_goal_292 initPM) 1009 =
      allReducePrim 4 0
        [(bw_linear (chunkPrimDimN 2 4 0 (initPM 818)) (initPM 1000) (initPM 2285)).1,
         (bw_linear (chunkPrimDimN 2 4 1 (initPM 818)) (initPM 1000) (initPM 2286)).1,
         (bw_linear (chunkPrimDimN 2 4 2 (initPM 818)) (initPM 1000) (initPM 2287)).1,
         (bw_linear (chunkPrimDimN 2 4 3 (initPM 818)) (initPM 1000) (initPM 2288)).1] := by
    simp only [pm_goal_292, denoteGraph, List.foldl]
    rw [applyNode_allReducePrim_out]
    congr 1
  -- Key equation: SM dX = TP reduction of per-rank PM dX
  have hkey : (bw_linear (initSM 818) (initSM 1008) (initSM 643)).1 =
      allReducePrim 4 0
        [(bw_linear (chunkPrimDimN 2 4 0 (initPM 818)) (initPM 1000) (initPM 2285)).1,
         (bw_linear (chunkPrimDimN 2 4 1 (initPM 818)) (initPM 1000) (initPM 2286)).1,
         (bw_linear (chunkPrimDimN 2 4 2 (initPM 818)) (initPM 1000) (initPM 2287)).1,
         (bw_linear (chunkPrimDimN 2 4 3 (initPM 818)) (initPM 1000) (initPM 2288)).1] := by
    rw [h818_eq, h1008_eq, h643_gather]
    conv_lhs => rw [← allGather_chunkPrimDimN_roundtrip_dim2_4_1_8_32_g205 (initPM 818) h818_shapeP]
    exact bw_linear_dx_tp_split_dim2_4_g134
      (chunkPrimDimN 2 4 0 (initPM 818)) (chunkPrimDimN 2 4 1 (initPM 818))
      (chunkPrimDimN 2 4 2 (initPM 818)) (chunkPrimDimN 2 4 3 (initPM 818))
      (initPM 1000) (initPM 2285) (initPM 2286) (initPM 2287) (initPM 2288)
      hc0 hc1 hc2 hc3 h1000_shapeP h2285_shape h2286_shape h2287_shape h2288_shape
  -- shape of one PM dX shard (= [1,8,32])
  have hdx0shape : (bw_linear (chunkPrimDimN 2 4 0 (initPM 818)) (initPM 1000) (initPM 2285)).1.shape
      = [1, 8, 32] :=
    bw_linear_3d_fst_shape 1 8 8 32 _ _ _ hc0 h1000_shapeP h2285_shape
  have hRhead : ([(bw_linear (chunkPrimDimN 2 4 0 (initPM 818)) (initPM 1000) (initPM 2285)).1,
       (bw_linear (chunkPrimDimN 2 4 1 (initPM 818)) (initPM 1000) (initPM 2286)).1,
       (bw_linear (chunkPrimDimN 2 4 2 (initPM 818)) (initPM 1000) (initPM 2287)).1,
       (bw_linear (chunkPrimDimN 2 4 3 (initPM 818)) (initPM 1000) (initPM 2288)).1] : List Tensor).head?
      = some (bw_linear (chunkPrimDimN 2 4 0 (initPM 818)) (initPM 1000) (initPM 2285)).1 := rfl
  -- Discharge the three conjuncts
  simp only [goal_292, List.map]
  refine ⟨?_, ?_, ?_⟩
  · -- SM output shape: [1, 8, 32]
    rw [hsm, hkey, allReducePrim_shape 4 0 _ _ hRhead, hdx0shape]
  · -- PM tp shapes: [[1, 8, 32]]
    rw [hpm, allReducePrim_shape 4 0 _ _ hRhead, hdx0shape]
  · -- Value equality: smStore 1009 = reconstructWithDim 0 4 0 [pmStore 1009]
    rw [hsm, hkey, ← hpm, reconstructWithDim_singleton]

end TrainVerify.Denote.GeneratedGoals


