/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 222 (tensor id: 859)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_222 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_linear", ins := [860, 1051, 678], outs := [1052, 859] },
  ]

def pm_goal_222 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_linear", ins := [860, 2841, 2845], outs := [2861, 2862] },
    { rank := 1, op := "OpName.BW_linear", ins := [860, 2842, 2846], outs := [2863, 2864] },
    { rank := 2, op := "OpName.BW_linear", ins := [860, 2843, 2847], outs := [2865, 2866] },
    { rank := 3, op := "OpName.BW_linear", ins := [860, 2844, 2848], outs := [2867, 2868] },
  ]

def sm_goal_222InitShapes : List (Tid × Shape) := [
  (678, [32, 32]),
  (860, [1, 8, 32]),
  (1051, [1, 8, 32]),
]

def sm_goal_222InitEnv : ShapeEnv := shapeEnvOfList sm_goal_222InitShapes

def pm_goal_222InitShapes : List (Tid × Shape) := [
  (860, [1, 8, 32]),
  (2841, [1, 8, 8]),
  (2842, [1, 8, 8]),
  (2843, [1, 8, 8]),
  (2844, [1, 8, 8]),
  (2845, [32, 8]),
  (2846, [32, 8]),
  (2847, [32, 8]),
  (2848, [32, 8]),
]

def pm_goal_222InitEnv : ShapeEnv := shapeEnvOfList pm_goal_222InitShapes

def goal_222_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_105, goal_106, goal_223, goal_228, goal_229, goal_232, goal_233, goal_234, goal_235, goal_236, goal_237, goal_238, goal_239, goal_241, goal_242, goal_245, goal_247, goal_248, goal_250, goal_251, goal_254, goal_256, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_287, goal_289, goal_291, goal_293, goal_295, goal_297, goal_299, goal_301, goal_303, goal_305, goal_307, goal_309, goal_310, goal_311, goal_312]
def goal_222_cut_initGoals : List LineageGoal := initGoals ++ goal_222_prereqs

def goal_222_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_222 pm_goal_222 goal_222 sm_goal_222InitEnv pm_goal_222InitEnv goal_222_cut_initGoals

set_option maxRecDepth 4096 in
set_option maxHeartbeats 8000000 in
-- BW_linear dX: input-parallel (x sharded on dim 2, weight on dim 1), so the full dX
-- equals the dim-1 all-gather of the per-rank dX outputs.
theorem prove_goal_222_cut : goal_222_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  -- g (860): replicated singleton
  have hInit223 : InitGoalHolds pm_goal_222.numRanks goal_223 initSM initPM := by
    apply hInitGoals; simp only [goal_222_cut_initGoals, goal_222_prereqs]; decide
  have h860_shape : (initSM 860).shape = [1, 8, 32] := hInit223.1
  have h860_eq : initSM 860 = initPM 860 := by
    have hrec := hInit223.2.2
    simp only [goal_223, pm_goal_222, List.map] at hrec
    rw [hrec]; (first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip); exact reconstructWithDim_singleton ..
  have h860_shapeP : (initPM 860).shape = [1, 8, 32] := by rw [← h860_eq]; exact h860_shape
  -- x (1051): gather on dim 2 from [2841,2842,2843,2844]
  have hInit305 : InitGoalHolds pm_goal_222.numRanks goal_305 initSM initPM := by
    apply hInitGoals; simp only [goal_222_cut_initGoals, goal_222_prereqs]; decide
  have h1051_shape : (initSM 1051).shape = [1, 8, 32] := hInit305.1
  have h1051_rec : initSM 1051 = reconstructWithDim 2 4 0
      [initPM 2841, initPM 2842, initPM 2843, initPM 2844] := by
    have hrec := hInit305.2.2
    simp only [goal_305, pm_goal_222, List.map] at hrec
    exact hrec
  have htp305 := hInit305.2.1
  simp only [goal_305, List.map] at htp305
  have h2841_shape : (initPM 2841).shape = [1, 8, 8] := by
    have := congrArg List.head? htp305; simpa using this
  have h2842_shape : (initPM 2842).shape = [1, 8, 8] := by
    have := congrArg (List.head? ∘ List.tail) htp305; simpa using this
  have h2843_shape : (initPM 2843).shape = [1, 8, 8] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail) htp305; simpa using this
  have h2844_shape : (initPM 2844).shape = [1, 8, 8] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail ∘ List.tail) htp305; simpa using this
  have h1051_gather : initSM 1051 = allGatherPrimDimN 2 4 0
      [initPM 2841, initPM 2842, initPM 2843, initPM 2844] := by
    rw [h1051_rec]
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    exact reconstructWithDim_cons_cons_nonscalar 2 4 0 _ _ _ (by rw [h2841_shape]; decide)
  -- w (678): gather on dim 1 from [2845,2846,2847,2848]
  have hInit678 : InitGoalHolds pm_goal_222.numRanks initGoal_678 initSM initPM := by
    apply hInitGoals; simp only [goal_222_cut_initGoals, goal_222_prereqs, initGoals]; decide
  have h678_shape : (initSM 678).shape = [32, 32] := hInit678.1
  have h678_rec : initSM 678 = reconstructWithDim 1 4 0
      [initPM 2845, initPM 2846, initPM 2847, initPM 2848] := by
    have hrec := hInit678.2.2
    simp only [initGoal_678, pm_goal_222, List.map] at hrec
    exact hrec
  have htp678 := hInit678.2.1
  simp only [initGoal_678, List.map] at htp678
  have h2845_shape : (initPM 2845).shape = [32, 8] := by
    have := congrArg List.head? htp678; simpa using this
  have h2846_shape : (initPM 2846).shape = [32, 8] := by
    have := congrArg (List.head? ∘ List.tail) htp678; simpa using this
  have h2847_shape : (initPM 2847).shape = [32, 8] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail) htp678; simpa using this
  have h2848_shape : (initPM 2848).shape = [32, 8] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail ∘ List.tail) htp678; simpa using this
  have h678_gather : initSM 678 = allGatherPrimDimN 1 4 0
      [initPM 2845, initPM 2846, initPM 2847, initPM 2848] := by
    rw [h678_rec]
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    exact reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _ (by rw [h2845_shape]; decide)
  -- SM store: dX of full BW_linear
  have hsm : (denoteGraph sm_goal_222 initSM) 859 =
      (bw_linear (initSM 860) (initSM 1051) (initSM 678)).2 := by
    simp only [sm_goal_222, denoteGraph, List.foldl]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
  -- PM stores: four independent BW_linear dX outputs
  have hpm0 : (denoteGraph pm_goal_222 initPM) 2862 =
      (bw_linear (initPM 860) (initPM 2841) (initPM 2845)).2 := by
    simp only [pm_goal_222, denoteGraph, List.foldl]
    rw [applyNode_skip _ _ _ (2862 : Tid) (by decide : (2862 : Tid) ∉ [2867, 2868])]
    rw [applyNode_skip _ _ _ (2862 : Tid) (by decide : (2862 : Tid) ∉ [2865, 2866])]
    rw [applyNode_skip _ _ _ (2862 : Tid) (by decide : (2862 : Tid) ∉ [2863, 2864])]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
  have hpm1 : (denoteGraph pm_goal_222 initPM) 2864 =
      (bw_linear (initPM 860) (initPM 2842) (initPM 2846)).2 := by
    simp only [pm_goal_222, denoteGraph, List.foldl]
    rw [applyNode_skip _ _ _ (2864 : Tid) (by decide : (2864 : Tid) ∉ [2867, 2868])]
    rw [applyNode_skip _ _ _ (2864 : Tid) (by decide : (2864 : Tid) ∉ [2865, 2866])]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
    rw [applyNode_skip _ _ _ (860 : Tid) (by decide : (860 : Tid) ∉ [2861, 2862])]
    rw [applyNode_skip _ _ _ (2842 : Tid) (by decide : (2842 : Tid) ∉ [2861, 2862])]
    rw [applyNode_skip _ _ _ (2846 : Tid) (by decide : (2846 : Tid) ∉ [2861, 2862])]
  have hpm2 : (denoteGraph pm_goal_222 initPM) 2866 =
      (bw_linear (initPM 860) (initPM 2843) (initPM 2847)).2 := by
    simp only [pm_goal_222, denoteGraph, List.foldl]
    rw [applyNode_skip _ _ _ (2866 : Tid) (by decide : (2866 : Tid) ∉ [2867, 2868])]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
    rw [applyNode_skip _ _ _ (860 : Tid) (by decide : (860 : Tid) ∉ [2863, 2864])]
    rw [applyNode_skip _ _ _ (860 : Tid) (by decide : (860 : Tid) ∉ [2861, 2862])]
    rw [applyNode_skip _ _ _ (2843 : Tid) (by decide : (2843 : Tid) ∉ [2863, 2864])]
    rw [applyNode_skip _ _ _ (2843 : Tid) (by decide : (2843 : Tid) ∉ [2861, 2862])]
    rw [applyNode_skip _ _ _ (2847 : Tid) (by decide : (2847 : Tid) ∉ [2863, 2864])]
    rw [applyNode_skip _ _ _ (2847 : Tid) (by decide : (2847 : Tid) ∉ [2861, 2862])]
  have hpm3 : (denoteGraph pm_goal_222 initPM) 2868 =
      (bw_linear (initPM 860) (initPM 2844) (initPM 2848)).2 := by
    simp only [pm_goal_222, denoteGraph, List.foldl]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
    rw [applyNode_skip _ _ _ (860 : Tid) (by decide : (860 : Tid) ∉ [2865, 2866])]
    rw [applyNode_skip _ _ _ (860 : Tid) (by decide : (860 : Tid) ∉ [2863, 2864])]
    rw [applyNode_skip _ _ _ (860 : Tid) (by decide : (860 : Tid) ∉ [2861, 2862])]
    rw [applyNode_skip _ _ _ (2844 : Tid) (by decide : (2844 : Tid) ∉ [2865, 2866])]
    rw [applyNode_skip _ _ _ (2844 : Tid) (by decide : (2844 : Tid) ∉ [2863, 2864])]
    rw [applyNode_skip _ _ _ (2844 : Tid) (by decide : (2844 : Tid) ∉ [2861, 2862])]
    rw [applyNode_skip _ _ _ (2848 : Tid) (by decide : (2848 : Tid) ∉ [2865, 2866])]
    rw [applyNode_skip _ _ _ (2848 : Tid) (by decide : (2848 : Tid) ∉ [2863, 2864])]
    rw [applyNode_skip _ _ _ (2848 : Tid) (by decide : (2848 : Tid) ∉ [2861, 2862])]
  -- Key equation: full dX = dim-1 all-gather of per-rank dX
  have hkey : (bw_linear (initSM 860) (initSM 1051) (initSM 678)).2 =
      allGatherPrimDimN 1 4 0
        [(bw_linear (initPM 860) (initPM 2841) (initPM 2845)).2,
         (bw_linear (initPM 860) (initPM 2842) (initPM 2846)).2,
         (bw_linear (initPM 860) (initPM 2843) (initPM 2847)).2,
         (bw_linear (initPM 860) (initPM 2844) (initPM 2848)).2] := by
    rw [h1051_gather, h860_eq, h678_gather]
    exact bw_linear_dw_isplit_dim2_4_1_8_8_g150 (initPM 860)
      (initPM 2841) (initPM 2842) (initPM 2843) (initPM 2844)
      (initPM 2845) (initPM 2846) (initPM 2847) (initPM 2848)
      h860_shapeP h2841_shape h2842_shape h2843_shape h2844_shape
      h2845_shape h2846_shape h2847_shape h2848_shape
  -- Discharge the three conjuncts
  simp only [goal_222, List.map]
  refine ⟨?_, ?_, ?_⟩
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    show (denoteGraph sm_goal_222 initSM 859).shape = _
    rw [hsm]
    exact bw_linear_3d_snd_shape 1 8 32 32 _ _ _ h860_shape h1051_shape h678_shape
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    show [(denoteGraph pm_goal_222 initPM 2862).shape,
          (denoteGraph pm_goal_222 initPM 2864).shape,
          (denoteGraph pm_goal_222 initPM 2866).shape,
          (denoteGraph pm_goal_222 initPM 2868).shape] = _
    rw [hpm0, hpm1, hpm2, hpm3]
    simp only [bw_linear_3d_snd_shape 1 8 32 8 _ _ _ h860_shapeP h2841_shape h2845_shape,
               bw_linear_3d_snd_shape 1 8 32 8 _ _ _ h860_shapeP h2842_shape h2846_shape,
               bw_linear_3d_snd_shape 1 8 32 8 _ _ _ h860_shapeP h2843_shape h2847_shape,
               bw_linear_3d_snd_shape 1 8 32 8 _ _ _ h860_shapeP h2844_shape h2848_shape]
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    show denoteGraph sm_goal_222 initSM 859 =
      reconstructWithDim 1 4 0 [denoteGraph pm_goal_222 initPM 2862,
        denoteGraph pm_goal_222 initPM 2864, denoteGraph pm_goal_222 initPM 2866,
        denoteGraph pm_goal_222 initPM 2868]
    rw [hsm, hpm0, hpm1, hpm2, hpm3, hkey]
    symm
    apply reconstructWithDim_cons_cons_nonscalar
    rw [bw_linear_3d_snd_shape 1 8 32 8 _ _ _ h860_shapeP h2841_shape h2845_shape]; decide

end TrainVerify.Denote.GeneratedGoals


