/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 293 (tensor id: 1012)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_293 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [640], outs := [1004, 1008, 1012], params := [3] },
  ]

def pm_goal_293 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [2229], outs := [3607, 3609, 2313], params := [3] },
    { rank := 1, op := "OpName.FW_multiref", ins := [2230], outs := [3617, 3619, 2314], params := [3] },
    { rank := 2, op := "OpName.FW_multiref", ins := [2231], outs := [3627, 3629, 2315], params := [3] },
    { rank := 3, op := "OpName.FW_multiref", ins := [2232], outs := [3637, 3639, 2316], params := [3] },
  ]

def sm_goal_293InitShapes : List (Tid × Shape) := [
  (640, [1, 8, 32]),
]

def sm_goal_293InitEnv : ShapeEnv := shapeEnvOfList sm_goal_293InitShapes

def pm_goal_293InitShapes : List (Tid × Shape) := [
  (2229, [1, 2, 32]),
  (2230, [1, 2, 32]),
  (2231, [1, 2, 32]),
  (2232, [1, 2, 32]),
]

def pm_goal_293InitEnv : ShapeEnv := shapeEnvOfList pm_goal_293InitShapes

def goal_293_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285]
def goal_293_cut_initGoals : List LineageGoal := initGoals ++ goal_293_prereqs

def goal_293_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_293 pm_goal_293 goal_293 sm_goal_293InitEnv pm_goal_293InitEnv goal_293_cut_initGoals

set_option maxRecDepth 4096 in
-- FW_multiref copies its input to 3 outputs; the lineage of each output equals the input lineage.
theorem prove_goal_293_cut : goal_293_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  -- Extract init alignment for goal_55 (tensor 640 = gather of shards 2229..2232 on dim 1)
  have hInit640 : InitGoalHolds pm_goal_293.numRanks goal_55 initSM initPM := by
    apply hInitGoals
    simp only [goal_293_cut_initGoals, goal_293_prereqs]
    decide
  -- goal_55: initSM 640 = reconstructWithDim 1 4 0 [initPM 2229..2232]
  have h640_rec : initSM 640 = reconstructWithDim 1 4 0
      [initPM 2229, initPM 2230, initPM 2231, initPM 2232] := by
    have hrec := hInit640.2.2
    simp only [goal_55, pm_goal_293, List.map] at hrec
    exact hrec
  have h640_shape : (initSM 640).shape = [1, 8, 32] := hInit640.1
  -- PM shard shapes from goal_55
  have htp_shapes := hInit640.2.1
  simp only [goal_55, List.map] at htp_shapes
  have h2229_shape : (initPM 2229).shape = [1, 2, 32] := by
    have := congrArg List.head? htp_shapes; simpa using this
  have h2230_shape : (initPM 2230).shape = [1, 2, 32] := by
    have := congrArg List.tail htp_shapes
    have := congrArg List.head? this; simpa using this
  have h2231_shape : (initPM 2231).shape = [1, 2, 32] := by
    have := congrArg (List.tail ∘ List.tail) htp_shapes
    have := congrArg List.head? this; simpa using this
  have h2232_shape : (initPM 2232).shape = [1, 2, 32] := by
    have := congrArg (List.tail ∘ List.tail ∘ List.tail) htp_shapes
    have := congrArg List.head? this; simpa using this
  -- SM store: smStore 1012 = initSM 640 (third copy of FW_multiref)
  have hsm : (denoteGraph sm_goal_293 initSM) 1012 = initSM 640 := by
    simp only [sm_goal_293, denoteGraph, List.foldl]
    rw [applyNode_fw_multiref3_third_out_g293 _ _ 0 640 1004 1008 1012
        (by decide) (by decide)]
  -- PM stores: each rank's third output equals that rank's input
  have hpm0 : (denoteGraph pm_goal_293 initPM) 2313 = initPM 2229 := by
    simp only [pm_goal_293, denoteGraph, List.foldl]
    rw [applyNode_fw_multiref3_pass_g293 _ _ 3 2232 3637 3639 2316 2313
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 2 2231 3627 3629 2315 2313
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 1 2230 3617 3619 2314 2313
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_third_out_g293 _ _ 0 2229 3607 3609 2313
          (by decide) (by decide)]
  have hpm1 : (denoteGraph pm_goal_293 initPM) 2314 = initPM 2230 := by
    simp only [pm_goal_293, denoteGraph, List.foldl]
    rw [applyNode_fw_multiref3_pass_g293 _ _ 3 2232 3637 3639 2316 2314
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 2 2231 3627 3629 2315 2314
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_third_out_g293 _ _ 1 2230 3617 3619 2314
          (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 0 2229 3607 3609 2313 2230
          (by decide) (by decide) (by decide)]
  have hpm2 : (denoteGraph pm_goal_293 initPM) 2315 = initPM 2231 := by
    simp only [pm_goal_293, denoteGraph, List.foldl]
    rw [applyNode_fw_multiref3_pass_g293 _ _ 3 2232 3637 3639 2316 2315
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_third_out_g293 _ _ 2 2231 3627 3629 2315
          (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 1 2230 3617 3619 2314 2231
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 0 2229 3607 3609 2313 2231
          (by decide) (by decide) (by decide)]
  have hpm3 : (denoteGraph pm_goal_293 initPM) 2316 = initPM 2232 := by
    simp only [pm_goal_293, denoteGraph, List.foldl]
    rw [applyNode_fw_multiref3_third_out_g293 _ _ 3 2232 3637 3639 2316
          (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 2 2231 3627 3629 2315 2232
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 1 2230 3617 3619 2314 2232
          (by decide) (by decide) (by decide),
        applyNode_fw_multiref3_pass_g293 _ _ 0 2229 3607 3609 2313 2232
          (by decide) (by decide) (by decide)]
  -- Prove the three conjuncts
  simp only [goal_293, List.map]
  refine ⟨?_, ?_, ?_⟩
  · -- SM output shape
    rw [hsm]; exact h640_shape
  · -- PM tps shapes
    rw [hpm0, hpm1, hpm2, hpm3, h2229_shape, h2230_shape, h2231_shape, h2232_shape]
  · -- Value equality
    rw [hsm, hpm0, hpm1, hpm2, hpm3, h640_rec]
    rfl

end TrainVerify.Denote.GeneratedGoals


