/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 181 (tensor id: 806)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_181 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_multiref", ins := [990, 994], outs := [806] },
  ]

def pm_goal_181 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_multiref", ins := [2241, 2625], outs := [2215] },
    { rank := 1, op := "OpName.BW_multiref", ins := [2245, 2628], outs := [2218] },
    { rank := 2, op := "OpName.BW_multiref", ins := [2249, 2631], outs := [2221] },
    { rank := 3, op := "OpName.BW_multiref", ins := [2253, 2634], outs := [2224] },
  ]

def sm_goal_181InitShapes : List (Tid × Shape) := [
  (990, [1, 8, 32]),
  (994, [1, 8, 32]),
]

def sm_goal_181InitEnv : ShapeEnv := shapeEnvOfList sm_goal_181InitShapes

def pm_goal_181InitShapes : List (Tid × Shape) := [
  (2241, [1, 2, 32]),
  (2245, [1, 2, 32]),
  (2249, [1, 2, 32]),
  (2253, [1, 2, 32]),
  (2625, [1, 2, 32]),
  (2628, [1, 2, 32]),
  (2631, [1, 2, 32]),
  (2634, [1, 2, 32]),
]

def pm_goal_181InitEnv : ShapeEnv := shapeEnvOfList pm_goal_181InitShapes

def goal_181_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_105, goal_106, goal_184, goal_186, goal_188, goal_190, goal_191, goal_192, goal_193, goal_194, goal_195, goal_196, goal_197, goal_198, goal_199, goal_200, goal_201, goal_202, goal_203, goal_204, goal_206, goal_207, goal_210, goal_212, goal_213, goal_215, goal_216, goal_219, goal_221, goal_223, goal_225, goal_226, goal_227, goal_228, goal_229, goal_230, goal_231, goal_232, goal_233, goal_234, goal_235, goal_236, goal_237, goal_238, goal_239, goal_241, goal_242, goal_245, goal_247, goal_248, goal_250, goal_251, goal_254, goal_256, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_286, goal_287, goal_288, goal_289, goal_290, goal_291, goal_292, goal_293, goal_294, goal_295, goal_296, goal_297, goal_298, goal_299, goal_300, goal_301, goal_302, goal_303, goal_304, goal_305, goal_306, goal_307, goal_308, goal_309, goal_310, goal_311, goal_312]
def goal_181_cut_initGoals : List LineageGoal := initGoals ++ goal_181_prereqs

def goal_181_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_181 pm_goal_181 goal_181 sm_goal_181InitEnv pm_goal_181InitEnv goal_181_cut_initGoals

set_option maxRecDepth 4096 in
/-- BW_multiref: both inputs gathered on dim 1; tensorSum distributes over the gather. -/
theorem prove_goal_181_cut : goal_181_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  -- Prereq goal_286: tensor 990 = allGather dim 1 of shards [2241,2245,2249,2253]
  have hInit990 : InitGoalHolds pm_goal_181.numRanks goal_286 initSM initPM := by
    apply hInitGoals
    simp only [goal_181_cut_initGoals, goal_181_prereqs]
    decide
  have h990_rec : initSM 990 = reconstructWithDim 1 4 0
      [initPM 2241, initPM 2245, initPM 2249, initPM 2253] := by
    have hrec := hInit990.2.2
    simp only [goal_286, pm_goal_181, List.map] at hrec
    exact hrec
  have h990_shape : (initSM 990).shape = [1, 8, 32] := hInit990.1
  have htp286 := hInit990.2.1
  simp only [goal_286, List.map] at htp286
  have h2241_shape : (initPM 2241).shape = [1, 2, 32] := by
    have := congrArg List.head? htp286; simpa using this
  have h2245_shape : (initPM 2245).shape = [1, 2, 32] := by
    have := congrArg List.tail htp286
    have := congrArg List.head? this; simpa using this
  have h2249_shape : (initPM 2249).shape = [1, 2, 32] := by
    have := congrArg (List.tail ∘ List.tail) htp286
    have := congrArg List.head? this; simpa using this
  have h2253_shape : (initPM 2253).shape = [1, 2, 32] := by
    have := congrArg (List.tail ∘ List.tail ∘ List.tail) htp286
    have := congrArg List.head? this; simpa using this
  have h990_gather : initSM 990 = allGatherPrimDimN 1 4 0
      [initPM 2241, initPM 2245, initPM 2249, initPM 2253] := by
    rw [h990_rec]
    exact reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _ (by rw [h2241_shape]; decide)
  -- Prereq goal_288: tensor 994 = allGather dim 1 of shards [2625,2628,2631,2634]
  have hInit994 : InitGoalHolds pm_goal_181.numRanks goal_288 initSM initPM := by
    apply hInitGoals
    simp only [goal_181_cut_initGoals, goal_181_prereqs]
    decide
  have h994_rec : initSM 994 = reconstructWithDim 1 4 0
      [initPM 2625, initPM 2628, initPM 2631, initPM 2634] := by
    have hrec := hInit994.2.2
    simp only [goal_288, pm_goal_181, List.map] at hrec
    exact hrec
  have h994_shape : (initSM 994).shape = [1, 8, 32] := hInit994.1
  have htp288 := hInit994.2.1
  simp only [goal_288, List.map] at htp288
  have h2625_shape : (initPM 2625).shape = [1, 2, 32] := by
    have := congrArg List.head? htp288; simpa using this
  have h2628_shape : (initPM 2628).shape = [1, 2, 32] := by
    have := congrArg List.tail htp288
    have := congrArg List.head? this; simpa using this
  have h2631_shape : (initPM 2631).shape = [1, 2, 32] := by
    have := congrArg (List.tail ∘ List.tail) htp288
    have := congrArg List.head? this; simpa using this
  have h2634_shape : (initPM 2634).shape = [1, 2, 32] := by
    have := congrArg (List.tail ∘ List.tail ∘ List.tail) htp288
    have := congrArg List.head? this; simpa using this
  have h994_gather : initSM 994 = allGatherPrimDimN 1 4 0
      [initPM 2625, initPM 2628, initPM 2631, initPM 2634] := by
    rw [h994_rec]
    exact reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _ (by rw [h2625_shape]; decide)
  -- SM store: tensorSum [initSM 990, initSM 994]
  have hsm : (denoteGraph sm_goal_181 initSM) 806 =
      tensorSum [initSM 990, initSM 994] := by
    simp only [sm_goal_181, denoteGraph, List.foldl]
    rw [applyNode_bw_multiref_out]
    simp [List.map]
  -- PM stores (transparent; rfl computes through)
  have hpm_2215 : (denoteGraph pm_goal_181 initPM) 2215 =
      tensorSum [initPM 2241, initPM 2625] := rfl
  have hpm_2218 : (denoteGraph pm_goal_181 initPM) 2218 =
      tensorSum [initPM 2245, initPM 2628] := rfl
  have hpm_2221 : (denoteGraph pm_goal_181 initPM) 2221 =
      tensorSum [initPM 2249, initPM 2631] := rfl
  have hpm_2224 : (denoteGraph pm_goal_181 initPM) 2224 =
      tensorSum [initPM 2253, initPM 2634] := rfl
  -- Key equation: tensorSum of two gathers = gather of per-rank tensorSums
  have hkey : tensorSum [initSM 990, initSM 994] =
      allGatherPrimDimN 1 4 0
        [tensorSum [initPM 2241, initPM 2625],
         tensorSum [initPM 2245, initPM 2628],
         tensorSum [initPM 2249, initPM 2631],
         tensorSum [initPM 2253, initPM 2634]] := by
    rw [h990_gather, h994_gather]
    exact tensorSum_gather_dim1_4_1_2_32_g181
      (initPM 2241) (initPM 2245) (initPM 2249) (initPM 2253)
      (initPM 2625) (initPM 2628) (initPM 2631) (initPM 2634)
      h2241_shape h2245_shape h2249_shape h2253_shape
      h2625_shape h2628_shape h2631_shape h2634_shape
  -- Discharge the three conjuncts
  simp only [goal_181, List.map]
  refine ⟨?_, ?_, ?_⟩
  · -- SM output shape [1, 8, 32]
    rw [hsm, tensorSum_shape]; exact h990_shape
  · -- PM tp shapes [[1,2,32], [1,2,32], [1,2,32], [1,2,32]]
    simp only [hpm_2215, hpm_2218, hpm_2221, hpm_2224, tensorSum_shape,
      h2241_shape, h2245_shape, h2249_shape, h2253_shape]
  · -- Value equality
    rw [hsm, hkey, ← hpm_2215, ← hpm_2218, ← hpm_2221, ← hpm_2224]
    symm
    exact reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _
      (by rw [hpm_2215, tensorSum_shape, h2241_shape]; decide)


end TrainVerify.Denote.GeneratedGoals

