/- AUTO-GENERATED by bridge_emitter (FAMILY-A: multi-tp, 0 mid, per-rank op).
   goal_250: SM=BW_add([890, 1067, 706])->889;
   PM=4xBW_add(per-rank inputs)->[889] multi-tps gatherDim=None.
   prereqs=[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 251, 254, 256, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311] (len 136). Inputs sourced from: 706<-ts_tp:103, 890<-ts:251, 1067<-ts:311, 3313<-tp:311, 3314<-tp:311, 3315<-tp:311, 3316<-tp:311, 3335<-tp:251, 3338<-tp:251, 3341<-tp:251, 3344<-tp:251. -/
import denote.gpt_ly4_regen.BridgeKit
import denote.gpt_ly4_regen.SpikeBridge
import denote.gpt_ly4_regen.Goal3Bridge
import denote.gpt_ly4_regen.Goal4Bridge
import denote.gpt_ly4_regen.Goal5Bridge
import denote.gpt_ly4_regen.Goal6Bridge
import denote.gpt_ly4_regen.Goal7Bridge
import denote.gpt_ly4_regen.Goal8Bridge
import denote.gpt_ly4_regen.Goal9Bridge
import denote.gpt_ly4_regen.Goal10Bridge
import denote.gpt_ly4_regen.Goal11Bridge
import denote.gpt_ly4_regen.Goal12Bridge
import denote.gpt_ly4_regen.Goal13Bridge
import denote.gpt_ly4_regen.Goal14Bridge
import denote.gpt_ly4_regen.Goal15Bridge
import denote.gpt_ly4_regen.Goal16Bridge
import denote.gpt_ly4_regen.Goal17Bridge
import denote.gpt_ly4_regen.Goal18Bridge
import denote.gpt_ly4_regen.Goal19Bridge
import denote.gpt_ly4_regen.Goal20Bridge
import denote.gpt_ly4_regen.Goal21Bridge
import denote.gpt_ly4_regen.Goal22Bridge
import denote.gpt_ly4_regen.Goal23Bridge
import denote.gpt_ly4_regen.Goal24Bridge
import denote.gpt_ly4_regen.Goal25Bridge
import denote.gpt_ly4_regen.Goal26Bridge
import denote.gpt_ly4_regen.Goal27Bridge
import denote.gpt_ly4_regen.Goal28Bridge
import denote.gpt_ly4_regen.Goal29Bridge
import denote.gpt_ly4_regen.Goal30Bridge
import denote.gpt_ly4_regen.Goal31Bridge
import denote.gpt_ly4_regen.Goal32Bridge
import denote.gpt_ly4_regen.Goal33Bridge
import denote.gpt_ly4_regen.Goal34Bridge
import denote.gpt_ly4_regen.Goal35Bridge
import denote.gpt_ly4_regen.Goal36Bridge
import denote.gpt_ly4_regen.Goal37Bridge
import denote.gpt_ly4_regen.Goal38Bridge
import denote.gpt_ly4_regen.Goal39Bridge
import denote.gpt_ly4_regen.Goal40Bridge
import denote.gpt_ly4_regen.Goal41Bridge
import denote.gpt_ly4_regen.Goal42Bridge
import denote.gpt_ly4_regen.Goal43Bridge
import denote.gpt_ly4_regen.Goal44Bridge
import denote.gpt_ly4_regen.Goal45Bridge
import denote.gpt_ly4_regen.Goal46Bridge
import denote.gpt_ly4_regen.Goal47Bridge
import denote.gpt_ly4_regen.Goal48Bridge
import denote.gpt_ly4_regen.Goal49Bridge
import denote.gpt_ly4_regen.Goal50Bridge
import denote.gpt_ly4_regen.Goal51Bridge
import denote.gpt_ly4_regen.Goal52Bridge
import denote.gpt_ly4_regen.Goal53Bridge
import denote.gpt_ly4_regen.Goal54Bridge
import denote.gpt_ly4_regen.Goal55Bridge
import denote.gpt_ly4_regen.Goal56Bridge
import denote.gpt_ly4_regen.Goal57Bridge
import denote.gpt_ly4_regen.Goal58Bridge
import denote.gpt_ly4_regen.Goal59Bridge
import denote.gpt_ly4_regen.Goal60Bridge
import denote.gpt_ly4_regen.Goal61Bridge
import denote.gpt_ly4_regen.Goal62Bridge
import denote.gpt_ly4_regen.Goal63Bridge
import denote.gpt_ly4_regen.Goal64Bridge
import denote.gpt_ly4_regen.Goal65Bridge
import denote.gpt_ly4_regen.Goal66Bridge
import denote.gpt_ly4_regen.Goal67Bridge
import denote.gpt_ly4_regen.Goal68Bridge
import denote.gpt_ly4_regen.Goal69Bridge
import denote.gpt_ly4_regen.Goal70Bridge
import denote.gpt_ly4_regen.Goal71Bridge
import denote.gpt_ly4_regen.Goal72Bridge
import denote.gpt_ly4_regen.Goal73Bridge
import denote.gpt_ly4_regen.Goal74Bridge
import denote.gpt_ly4_regen.Goal75Bridge
import denote.gpt_ly4_regen.Goal76Bridge
import denote.gpt_ly4_regen.Goal77Bridge
import denote.gpt_ly4_regen.Goal78Bridge
import denote.gpt_ly4_regen.Goal79Bridge
import denote.gpt_ly4_regen.Goal80Bridge
import denote.gpt_ly4_regen.Goal81Bridge
import denote.gpt_ly4_regen.Goal82Bridge
import denote.gpt_ly4_regen.Goal83Bridge
import denote.gpt_ly4_regen.Goal84Bridge
import denote.gpt_ly4_regen.Goal85Bridge
import denote.gpt_ly4_regen.Goal86Bridge
import denote.gpt_ly4_regen.Goal87Bridge
import denote.gpt_ly4_regen.Goal88Bridge
import denote.gpt_ly4_regen.Goal89Bridge
import denote.gpt_ly4_regen.Goal90Bridge
import denote.gpt_ly4_regen.Goal91Bridge
import denote.gpt_ly4_regen.Goal92Bridge
import denote.gpt_ly4_regen.Goal93Bridge
import denote.gpt_ly4_regen.Goal94Bridge
import denote.gpt_ly4_regen.Goal95Bridge
import denote.gpt_ly4_regen.Goal96Bridge
import denote.gpt_ly4_regen.Goal97Bridge
import denote.gpt_ly4_regen.Goal98Bridge
import denote.gpt_ly4_regen.Goal99Bridge
import denote.gpt_ly4_regen.Goal100Bridge
import denote.gpt_ly4_regen.Goal101Bridge
import denote.gpt_ly4_regen.Goal102Bridge
import denote.gpt_ly4_regen.Goal103Bridge
import denote.gpt_ly4_regen.Goal104Bridge
import denote.gpt_ly4_regen.Goal105Bridge
import denote.gpt_ly4_regen.Goal106Bridge
import denote.gpt_ly4_regen.Goal251Bridge
import denote.gpt_ly4_regen.Goal254Bridge
import denote.gpt_ly4_regen.Goal256Bridge
import denote.gpt_ly4_regen.Goal257Bridge
import denote.gpt_ly4_regen.Goal259Bridge
import denote.gpt_ly4_regen.Goal261Bridge
import denote.gpt_ly4_regen.Goal263Bridge
import denote.gpt_ly4_regen.Goal265Bridge
import denote.gpt_ly4_regen.Goal267Bridge
import denote.gpt_ly4_regen.Goal269Bridge
import denote.gpt_ly4_regen.Goal271Bridge
import denote.gpt_ly4_regen.Goal273Bridge
import denote.gpt_ly4_regen.Goal275Bridge
import denote.gpt_ly4_regen.Goal277Bridge
import denote.gpt_ly4_regen.Goal279Bridge
import denote.gpt_ly4_regen.Goal281Bridge
import denote.gpt_ly4_regen.Goal283Bridge
import denote.gpt_ly4_regen.Goal285Bridge
import denote.gpt_ly4_regen.Goal287Bridge
import denote.gpt_ly4_regen.Goal289Bridge
import denote.gpt_ly4_regen.Goal291Bridge
import denote.gpt_ly4_regen.Goal293Bridge
import denote.gpt_ly4_regen.Goal295Bridge
import denote.gpt_ly4_regen.Goal297Bridge
import denote.gpt_ly4_regen.Goal299Bridge
import denote.gpt_ly4_regen.Goal301Bridge
import denote.gpt_ly4_regen.Goal303Bridge
import denote.gpt_ly4_regen.Goal305Bridge
import denote.gpt_ly4_regen.Goal307Bridge
import denote.gpt_ly4_regen.Goal309Bridge
import denote.gpt_ly4_regen.Goal311Bridge
import denote.gpt_ly4_regen.Goal_250

set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.style.nativeDecide false
set_option linter.unusedSimpArgs false
set_option linter.style.commandStart false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unusedVariables false
set_option linter.style.show false
set_option linter.style.setOption false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false

namespace TrainVerify.Denote.GeneratedGoals
open TrainVerify.Denote TrainVerify.Denote.Generated

-- [EMITTER] local generic BW_add second-output (dy) applyNode lemma (goal-agnostic;
-- mirrors Denote.lean's applyNode_bw_add2_snd_out_gNNN, dropping the goal suffix).
private theorem applyNode_bw_add2_snd_out_loc
    (graph : GraphDecl) (s : Store) (rank : Nat)
    (gTid xTid yTid dxTid dyTid : Tid)
    (hne : dxTid ≠ dyTid) :
    applyNode graph s { rank := rank, op := "OpName.BW_add", ins := [gTid, xTid, yTid], outs := [dxTid, dyTid] } dyTid =
      (bw_add2 (s gTid) (s xTid) (s yTid)).2 := by
  unfold applyNode
  rw [show ([gTid, xTid, yTid] : List Tid).map s = [s gTid, s xTid, s yTid] from rfl,
      evalOp_bw_add2]
  change storeSet s [(dxTid, (bw_add2 (s gTid) (s xTid) (s yTid)).1),
                     (dyTid, (bw_add2 (s gTid) (s xTid) (s yTid)).2)] dyTid = _
  unfold storeSet
  simp [List.find?, hne]

-- ========== mini sm_goal_250 computes 889 (BW_add) ==========
theorem denote_sm_goal_250_889 (s : Store) :
    denoteGraph sm_goal_250 s 889 = (bw_add2 (s 890) (s 1067) (s 706)).2 := by
  simp only [sm_goal_250, denoteGraph, List.foldl]
  rw [applyNode_bw_add2_snd_out_loc _ _ 0 890 1067 706 1068 889 (by decide)]

-- ========== SM self-frame ==========
theorem sm_frame_889_self (initSM : Store) :
    denoteGraph sm initSM 889 = denoteGraph sm_goal_250 (denoteGraph sm initSM) 889 := by
  rw [denote_sm_goal_250_889]
  rw [sm_val initSM 121 889 (by native_decide) (by native_decide)]
  rw [show sm.nodes[121]'(by native_decide)
      = { rank := 0, op := "OpName.BW_add", ins := [890, 1067, 706], outs := [1068, 889] }
      from by native_decide]
  rw [applyNode_bw_add2_snd_out_loc _ _ 0 890 1067 706 1068 889 (by decide)]
  rw [sm_prefix_eq initSM 121 890 (by native_decide),
      sm_prefix_eq initSM 121 1067 (by native_decide),
      sm_prefix_eq initSM 121 706 (by native_decide)]

-- ========== pm_full (mid tensors) ==========
theorem pm_full_g250_3317 (initPM : Store) :
    denoteGraph pm initPM 3317
      = chunkPrimDimN 1 pm.numRanks 0 (denoteGraph pm initPM 706) := by
  rw [pm_val initPM 754 3317 (by native_decide) (by native_decide)]
  rw [show pm.nodes[754]'(by native_decide)
      = { rank := 0, op := "OpName.ChunkPrim", ins := [706], outs := [3317], params := [1] }
      from by native_decide]
  rw [applyNode_chunkPrimDimN_out]
  rw [pm_prefix_eq initPM 754 706 (by native_decide)]

theorem pm_full_g250_3318 (initPM : Store) :
    denoteGraph pm initPM 3318
      = chunkPrimDimN 1 pm.numRanks 1 (denoteGraph pm initPM 706) := by
  rw [pm_val initPM 755 3318 (by native_decide) (by native_decide)]
  rw [show pm.nodes[755]'(by native_decide)
      = { rank := 1, op := "OpName.ChunkPrim", ins := [706], outs := [3318], params := [1] }
      from by native_decide]
  rw [applyNode_chunkPrimDimN_out]
  rw [pm_prefix_eq initPM 755 706 (by native_decide)]

theorem pm_full_g250_3319 (initPM : Store) :
    denoteGraph pm initPM 3319
      = chunkPrimDimN 1 pm.numRanks 2 (denoteGraph pm initPM 706) := by
  rw [pm_val initPM 756 3319 (by native_decide) (by native_decide)]
  rw [show pm.nodes[756]'(by native_decide)
      = { rank := 2, op := "OpName.ChunkPrim", ins := [706], outs := [3319], params := [1] }
      from by native_decide]
  rw [applyNode_chunkPrimDimN_out]
  rw [pm_prefix_eq initPM 756 706 (by native_decide)]

theorem pm_full_g250_3320 (initPM : Store) :
    denoteGraph pm initPM 3320
      = chunkPrimDimN 1 pm.numRanks 3 (denoteGraph pm initPM 706) := by
  rw [pm_val initPM 757 3320 (by native_decide) (by native_decide)]
  rw [show pm.nodes[757]'(by native_decide)
      = { rank := 3, op := "OpName.ChunkPrim", ins := [706], outs := [3320], params := [1] }
      from by native_decide]
  rw [applyNode_chunkPrimDimN_out]
  rw [pm_prefix_eq initPM 757 706 (by native_decide)]

theorem pm_full_g250_3334 (initPM : Store) :
    denoteGraph pm initPM 3334
      = (bw_add2 (denoteGraph pm initPM 3335) (denoteGraph pm initPM 3313) (denoteGraph pm initPM 3317)).2 := by
  rw [pm_val initPM 793 3334 (by native_decide) (by native_decide)]
  rw [show pm.nodes[793]'(by native_decide)
      = { rank := 0, op := "OpName.BW_add", ins := [3335, 3313, 3317], outs := [3333, 3334] }
      from by native_decide]
  rw [applyNode_bw_add2_snd_out_loc _ _ 0 3335 3313 3317 3333 3334 (by decide)]
  rw [pm_prefix_eq initPM 793 3335 (by native_decide),
      pm_prefix_eq initPM 793 3313 (by native_decide),
      pm_prefix_eq initPM 793 3317 (by native_decide)]

theorem pm_full_g250_3337 (initPM : Store) :
    denoteGraph pm initPM 3337
      = (bw_add2 (denoteGraph pm initPM 3338) (denoteGraph pm initPM 3314) (denoteGraph pm initPM 3318)).2 := by
  rw [pm_val initPM 794 3337 (by native_decide) (by native_decide)]
  rw [show pm.nodes[794]'(by native_decide)
      = { rank := 1, op := "OpName.BW_add", ins := [3338, 3314, 3318], outs := [3336, 3337] }
      from by native_decide]
  rw [applyNode_bw_add2_snd_out_loc _ _ 1 3338 3314 3318 3336 3337 (by decide)]
  rw [pm_prefix_eq initPM 794 3338 (by native_decide),
      pm_prefix_eq initPM 794 3314 (by native_decide),
      pm_prefix_eq initPM 794 3318 (by native_decide)]

theorem pm_full_g250_3340 (initPM : Store) :
    denoteGraph pm initPM 3340
      = (bw_add2 (denoteGraph pm initPM 3341) (denoteGraph pm initPM 3315) (denoteGraph pm initPM 3319)).2 := by
  rw [pm_val initPM 795 3340 (by native_decide) (by native_decide)]
  rw [show pm.nodes[795]'(by native_decide)
      = { rank := 2, op := "OpName.BW_add", ins := [3341, 3315, 3319], outs := [3339, 3340] }
      from by native_decide]
  rw [applyNode_bw_add2_snd_out_loc _ _ 2 3341 3315 3319 3339 3340 (by decide)]
  rw [pm_prefix_eq initPM 795 3341 (by native_decide),
      pm_prefix_eq initPM 795 3315 (by native_decide),
      pm_prefix_eq initPM 795 3319 (by native_decide)]

theorem pm_full_g250_3343 (initPM : Store) :
    denoteGraph pm initPM 3343
      = (bw_add2 (denoteGraph pm initPM 3344) (denoteGraph pm initPM 3316) (denoteGraph pm initPM 3320)).2 := by
  rw [pm_val initPM 798 3343 (by native_decide) (by native_decide)]
  rw [show pm.nodes[798]'(by native_decide)
      = { rank := 3, op := "OpName.BW_add", ins := [3344, 3316, 3320], outs := [3342, 3343] }
      from by native_decide]
  rw [applyNode_bw_add2_snd_out_loc _ _ 3 3344 3316 3320 3342 3343 (by decide)]
  rw [pm_prefix_eq initPM 798 3344 (by native_decide),
      pm_prefix_eq initPM 798 3316 (by native_decide),
      pm_prefix_eq initPM 798 3320 (by native_decide)]

-- ========== denote_pm (final tps [889]) ==========
theorem denote_pm_goal_250_889 (s : Store) :
    denoteGraph pm_goal_250 s 889 = allGatherPrimDimN 1 4 0 [(bw_add2 (s 3335) (s 3313) (chunkPrimDimN 1 4 0 (s 706))).2, (bw_add2 (s 3338) (s 3314) (chunkPrimDimN 1 4 1 (s 706))).2, (bw_add2 (s 3341) (s 3315) (chunkPrimDimN 1 4 2 (s 706))).2, (bw_add2 (s 3344) (s 3316) (chunkPrimDimN 1 4 3 (s 706))).2] := by
  simp only [pm_goal_250, denoteGraph, List.foldl]
  repeat rw [applyNode_skip _ _ _ 889 (by decide)]
  rw [applyNode_allGatherPrimDimN_out]
  simp only [List.map]
  try (set_option maxHeartbeats 800000 in congr 1)

-- ========== pm_frame (final tps) ==========
theorem pm_frame_889_self (initPM : Store) :
    denoteGraph pm initPM 889
      = allGatherPrimDimN 1 4 0 [(bw_add2 (denoteGraph pm initPM 3335) (denoteGraph pm initPM 3313) (chunkPrimDimN 1 4 0 (denoteGraph pm initPM 706))).2, (bw_add2 (denoteGraph pm initPM 3338) (denoteGraph pm initPM 3314) (chunkPrimDimN 1 4 1 (denoteGraph pm initPM 706))).2, (bw_add2 (denoteGraph pm initPM 3341) (denoteGraph pm initPM 3315) (chunkPrimDimN 1 4 2 (denoteGraph pm initPM 706))).2, (bw_add2 (denoteGraph pm initPM 3344) (denoteGraph pm initPM 3316) (chunkPrimDimN 1 4 3 (denoteGraph pm initPM 706))).2] := by
  rw [pm_val initPM 799 889 (by native_decide) (by native_decide)]
  rw [show pm.nodes[799]'(by native_decide)
      = { rank := 0, op := "OpName.AllGatherPrim", ins := [3334, 3337, 3340, 3343], outs := [889], params := [1] }
      from by native_decide]
  rw [applyNode_allGatherPrimDimN_out_thm]
  simp only [List.map]
  rw [pm_prefix_eq initPM 799 3334 (by native_decide),
      pm_prefix_eq initPM 799 3337 (by native_decide),
      pm_prefix_eq initPM 799 3340 (by native_decide),
      pm_prefix_eq initPM 799 3343 (by native_decide)]
  rw [pm_full_g250_3343, pm_full_g250_3340, pm_full_g250_3337, pm_full_g250_3334, pm_full_g250_3320, pm_full_g250_3319, pm_full_g250_3318, pm_full_g250_3317]
  rw [show pm.numRanks = 4 from by native_decide]

-- ========== helper: hInitCut separate lemma (heartbeat workaround) ==========
lemma goal_250_hInitCut_helper (Ssm Spm : Store)
    (hinitC : InitGoalsHold pm.numRanks initGoals Ssm Spm)
    (hg2 : InitGoalHolds pm.numRanks goal_2 Ssm Spm)
    (hg3 : InitGoalHolds pm.numRanks goal_3 Ssm Spm)
    (hg4 : InitGoalHolds pm.numRanks goal_4 Ssm Spm)
    (hg5 : InitGoalHolds pm.numRanks goal_5 Ssm Spm)
    (hg6 : InitGoalHolds pm.numRanks goal_6 Ssm Spm)
    (hg7 : InitGoalHolds pm.numRanks goal_7 Ssm Spm)
    (hg8 : InitGoalHolds pm.numRanks goal_8 Ssm Spm)
    (hg9 : InitGoalHolds pm.numRanks goal_9 Ssm Spm)
    (hg10 : InitGoalHolds pm.numRanks goal_10 Ssm Spm)
    (hg11 : InitGoalHolds pm.numRanks goal_11 Ssm Spm)
    (hg12 : InitGoalHolds pm.numRanks goal_12 Ssm Spm)
    (hg13 : InitGoalHolds pm.numRanks goal_13 Ssm Spm)
    (hg14 : InitGoalHolds pm.numRanks goal_14 Ssm Spm)
    (hg15 : InitGoalHolds pm.numRanks goal_15 Ssm Spm)
    (hg16 : InitGoalHolds pm.numRanks goal_16 Ssm Spm)
    (hg17 : InitGoalHolds pm.numRanks goal_17 Ssm Spm)
    (hg18 : InitGoalHolds pm.numRanks goal_18 Ssm Spm)
    (hg19 : InitGoalHolds pm.numRanks goal_19 Ssm Spm)
    (hg20 : InitGoalHolds pm.numRanks goal_20 Ssm Spm)
    (hg21 : InitGoalHolds pm.numRanks goal_21 Ssm Spm)
    (hg22 : InitGoalHolds pm.numRanks goal_22 Ssm Spm)
    (hg23 : InitGoalHolds pm.numRanks goal_23 Ssm Spm)
    (hg24 : InitGoalHolds pm.numRanks goal_24 Ssm Spm)
    (hg25 : InitGoalHolds pm.numRanks goal_25 Ssm Spm)
    (hg26 : InitGoalHolds pm.numRanks goal_26 Ssm Spm)
    (hg27 : InitGoalHolds pm.numRanks goal_27 Ssm Spm)
    (hg28 : InitGoalHolds pm.numRanks goal_28 Ssm Spm)
    (hg29 : InitGoalHolds pm.numRanks goal_29 Ssm Spm)
    (hg30 : InitGoalHolds pm.numRanks goal_30 Ssm Spm)
    (hg31 : InitGoalHolds pm.numRanks goal_31 Ssm Spm)
    (hg32 : InitGoalHolds pm.numRanks goal_32 Ssm Spm)
    (hg33 : InitGoalHolds pm.numRanks goal_33 Ssm Spm)
    (hg34 : InitGoalHolds pm.numRanks goal_34 Ssm Spm)
    (hg35 : InitGoalHolds pm.numRanks goal_35 Ssm Spm)
    (hg36 : InitGoalHolds pm.numRanks goal_36 Ssm Spm)
    (hg37 : InitGoalHolds pm.numRanks goal_37 Ssm Spm)
    (hg38 : InitGoalHolds pm.numRanks goal_38 Ssm Spm)
    (hg39 : InitGoalHolds pm.numRanks goal_39 Ssm Spm)
    (hg40 : InitGoalHolds pm.numRanks goal_40 Ssm Spm)
    (hg41 : InitGoalHolds pm.numRanks goal_41 Ssm Spm)
    (hg42 : InitGoalHolds pm.numRanks goal_42 Ssm Spm)
    (hg43 : InitGoalHolds pm.numRanks goal_43 Ssm Spm)
    (hg44 : InitGoalHolds pm.numRanks goal_44 Ssm Spm)
    (hg45 : InitGoalHolds pm.numRanks goal_45 Ssm Spm)
    (hg46 : InitGoalHolds pm.numRanks goal_46 Ssm Spm)
    (hg47 : InitGoalHolds pm.numRanks goal_47 Ssm Spm)
    (hg48 : InitGoalHolds pm.numRanks goal_48 Ssm Spm)
    (hg49 : InitGoalHolds pm.numRanks goal_49 Ssm Spm)
    (hg50 : InitGoalHolds pm.numRanks goal_50 Ssm Spm)
    (hg51 : InitGoalHolds pm.numRanks goal_51 Ssm Spm)
    (hg52 : InitGoalHolds pm.numRanks goal_52 Ssm Spm)
    (hg53 : InitGoalHolds pm.numRanks goal_53 Ssm Spm)
    (hg54 : InitGoalHolds pm.numRanks goal_54 Ssm Spm)
    (hg55 : InitGoalHolds pm.numRanks goal_55 Ssm Spm)
    (hg56 : InitGoalHolds pm.numRanks goal_56 Ssm Spm)
    (hg57 : InitGoalHolds pm.numRanks goal_57 Ssm Spm)
    (hg58 : InitGoalHolds pm.numRanks goal_58 Ssm Spm)
    (hg59 : InitGoalHolds pm.numRanks goal_59 Ssm Spm)
    (hg60 : InitGoalHolds pm.numRanks goal_60 Ssm Spm)
    (hg61 : InitGoalHolds pm.numRanks goal_61 Ssm Spm)
    (hg62 : InitGoalHolds pm.numRanks goal_62 Ssm Spm)
    (hg63 : InitGoalHolds pm.numRanks goal_63 Ssm Spm)
    (hg64 : InitGoalHolds pm.numRanks goal_64 Ssm Spm)
    (hg65 : InitGoalHolds pm.numRanks goal_65 Ssm Spm)
    (hg66 : InitGoalHolds pm.numRanks goal_66 Ssm Spm)
    (hg67 : InitGoalHolds pm.numRanks goal_67 Ssm Spm)
    (hg68 : InitGoalHolds pm.numRanks goal_68 Ssm Spm)
    (hg69 : InitGoalHolds pm.numRanks goal_69 Ssm Spm)
    (hg70 : InitGoalHolds pm.numRanks goal_70 Ssm Spm)
    (hg71 : InitGoalHolds pm.numRanks goal_71 Ssm Spm)
    (hg72 : InitGoalHolds pm.numRanks goal_72 Ssm Spm)
    (hg73 : InitGoalHolds pm.numRanks goal_73 Ssm Spm)
    (hg74 : InitGoalHolds pm.numRanks goal_74 Ssm Spm)
    (hg75 : InitGoalHolds pm.numRanks goal_75 Ssm Spm)
    (hg76 : InitGoalHolds pm.numRanks goal_76 Ssm Spm)
    (hg77 : InitGoalHolds pm.numRanks goal_77 Ssm Spm)
    (hg78 : InitGoalHolds pm.numRanks goal_78 Ssm Spm)
    (hg79 : InitGoalHolds pm.numRanks goal_79 Ssm Spm)
    (hg80 : InitGoalHolds pm.numRanks goal_80 Ssm Spm)
    (hg81 : InitGoalHolds pm.numRanks goal_81 Ssm Spm)
    (hg82 : InitGoalHolds pm.numRanks goal_82 Ssm Spm)
    (hg83 : InitGoalHolds pm.numRanks goal_83 Ssm Spm)
    (hg84 : InitGoalHolds pm.numRanks goal_84 Ssm Spm)
    (hg85 : InitGoalHolds pm.numRanks goal_85 Ssm Spm)
    (hg86 : InitGoalHolds pm.numRanks goal_86 Ssm Spm)
    (hg87 : InitGoalHolds pm.numRanks goal_87 Ssm Spm)
    (hg88 : InitGoalHolds pm.numRanks goal_88 Ssm Spm)
    (hg89 : InitGoalHolds pm.numRanks goal_89 Ssm Spm)
    (hg90 : InitGoalHolds pm.numRanks goal_90 Ssm Spm)
    (hg91 : InitGoalHolds pm.numRanks goal_91 Ssm Spm)
    (hg92 : InitGoalHolds pm.numRanks goal_92 Ssm Spm)
    (hg93 : InitGoalHolds pm.numRanks goal_93 Ssm Spm)
    (hg94 : InitGoalHolds pm.numRanks goal_94 Ssm Spm)
    (hg95 : InitGoalHolds pm.numRanks goal_95 Ssm Spm)
    (hg96 : InitGoalHolds pm.numRanks goal_96 Ssm Spm)
    (hg97 : InitGoalHolds pm.numRanks goal_97 Ssm Spm)
    (hg98 : InitGoalHolds pm.numRanks goal_98 Ssm Spm)
    (hg99 : InitGoalHolds pm.numRanks goal_99 Ssm Spm)
    (hg100 : InitGoalHolds pm.numRanks goal_100 Ssm Spm)
    (hg101 : InitGoalHolds pm.numRanks goal_101 Ssm Spm)
    (hg102 : InitGoalHolds pm.numRanks goal_102 Ssm Spm)
    (hg103 : InitGoalHolds pm.numRanks goal_103 Ssm Spm)
    (hg104 : InitGoalHolds pm.numRanks goal_104 Ssm Spm)
    (hg105 : InitGoalHolds pm.numRanks goal_105 Ssm Spm)
    (hg106 : InitGoalHolds pm.numRanks goal_106 Ssm Spm)
    (hg251 : InitGoalHolds pm.numRanks goal_251 Ssm Spm)
    (hg254 : InitGoalHolds pm.numRanks goal_254 Ssm Spm)
    (hg256 : InitGoalHolds pm.numRanks goal_256 Ssm Spm)
    (hg257 : InitGoalHolds pm.numRanks goal_257 Ssm Spm)
    (hg259 : InitGoalHolds pm.numRanks goal_259 Ssm Spm)
    (hg261 : InitGoalHolds pm.numRanks goal_261 Ssm Spm)
    (hg263 : InitGoalHolds pm.numRanks goal_263 Ssm Spm)
    (hg265 : InitGoalHolds pm.numRanks goal_265 Ssm Spm)
    (hg267 : InitGoalHolds pm.numRanks goal_267 Ssm Spm)
    (hg269 : InitGoalHolds pm.numRanks goal_269 Ssm Spm)
    (hg271 : InitGoalHolds pm.numRanks goal_271 Ssm Spm)
    (hg273 : InitGoalHolds pm.numRanks goal_273 Ssm Spm)
    (hg275 : InitGoalHolds pm.numRanks goal_275 Ssm Spm)
    (hg277 : InitGoalHolds pm.numRanks goal_277 Ssm Spm)
    (hg279 : InitGoalHolds pm.numRanks goal_279 Ssm Spm)
    (hg281 : InitGoalHolds pm.numRanks goal_281 Ssm Spm)
    (hg283 : InitGoalHolds pm.numRanks goal_283 Ssm Spm)
    (hg285 : InitGoalHolds pm.numRanks goal_285 Ssm Spm)
    (hg287 : InitGoalHolds pm.numRanks goal_287 Ssm Spm)
    (hg289 : InitGoalHolds pm.numRanks goal_289 Ssm Spm)
    (hg291 : InitGoalHolds pm.numRanks goal_291 Ssm Spm)
    (hg293 : InitGoalHolds pm.numRanks goal_293 Ssm Spm)
    (hg295 : InitGoalHolds pm.numRanks goal_295 Ssm Spm)
    (hg297 : InitGoalHolds pm.numRanks goal_297 Ssm Spm)
    (hg299 : InitGoalHolds pm.numRanks goal_299 Ssm Spm)
    (hg301 : InitGoalHolds pm.numRanks goal_301 Ssm Spm)
    (hg303 : InitGoalHolds pm.numRanks goal_303 Ssm Spm)
    (hg305 : InitGoalHolds pm.numRanks goal_305 Ssm Spm)
    (hg307 : InitGoalHolds pm.numRanks goal_307 Ssm Spm)
    (hg309 : InitGoalHolds pm.numRanks goal_309 Ssm Spm)
    (hg311 : InitGoalHolds pm.numRanks goal_311 Ssm Spm) :
    InitGoalsHold pm_goal_250.numRanks goal_250_cut_initGoals Ssm Spm := by
  have hnr : pm_goal_250.numRanks = pm.numRanks := by native_decide
  rw [hnr]
  simp only [InitGoalsHold] at hinitC ⊢
  simp only [goal_250_cut_initGoals, goal_250_prereqs, List.forall_mem_append,
    List.forall_mem_cons, List.forall_mem_nil, and_true]
  exact ⟨hinitC, hg2, hg3, hg4, hg5, hg6, hg7, hg8, hg9, hg10, hg11, hg12, hg13, hg14, hg15, hg16, hg17, hg18, hg19, hg20, hg21, hg22, hg23, hg24, hg25, hg26, hg27, hg28, hg29, hg30, hg31, hg32, hg33, hg34, hg35, hg36, hg37, hg38, hg39, hg40, hg41, hg42, hg43, hg44, hg45, hg46, hg47, hg48, hg49, hg50, hg51, hg52, hg53, hg54, hg55, hg56, hg57, hg58, hg59, hg60, hg61, hg62, hg63, hg64, hg65, hg66, hg67, hg68, hg69, hg70, hg71, hg72, hg73, hg74, hg75, hg76, hg77, hg78, hg79, hg80, hg81, hg82, hg83, hg84, hg85, hg86, hg87, hg88, hg89, hg90, hg91, hg92, hg93, hg94, hg95, hg96, hg97, hg98, hg99, hg100, hg101, hg102, hg103, hg104, hg105, hg106, hg251, hg254, hg256, hg257, hg259, hg261, hg263, hg265, hg267, hg269, hg271, hg273, hg275, hg277, hg279, hg281, hg283, hg285, hg287, hg289, hg291, hg293, hg295, hg297, hg299, hg301, hg303, hg305, hg307, hg309, hg311, List.forall_mem_nil _⟩

-- ========== Assembly: goal_250_cut_to_full ==========
theorem goal_250_cut_to_full (h : goal_250_stmt_cut) : goal_250_stmt := by
  intro initSM initPM hSM hPM hInit
  set Ssm := denoteGraph sm initSM with hSsm
  set Spm := denoteGraph pm initPM with hSpm
  have hg2 := goal_2_intermediate initSM initPM hSM hPM hInit
  have hg3 := goal_3_intermediate initSM initPM hSM hPM hInit
  have hg4 := goal_4_intermediate initSM initPM hSM hPM hInit
  have hg5 := goal_5_intermediate initSM initPM hSM hPM hInit
  have hg6 := goal_6_intermediate initSM initPM hSM hPM hInit
  have hg7 := goal_7_intermediate initSM initPM hSM hPM hInit
  have hg8 := goal_8_intermediate initSM initPM hSM hPM hInit
  have hg9 := goal_9_intermediate initSM initPM hSM hPM hInit
  have hg10 := goal_10_intermediate initSM initPM hSM hPM hInit
  have hg11 := goal_11_intermediate initSM initPM hSM hPM hInit
  have hg12 := goal_12_intermediate initSM initPM hSM hPM hInit
  have hg13 := goal_13_intermediate initSM initPM hSM hPM hInit
  have hg14 := goal_14_intermediate initSM initPM hSM hPM hInit
  have hg15 := goal_15_intermediate initSM initPM hSM hPM hInit
  have hg16 := goal_16_intermediate initSM initPM hSM hPM hInit
  have hg17 := goal_17_intermediate initSM initPM hSM hPM hInit
  have hg18 := goal_18_intermediate initSM initPM hSM hPM hInit
  have hg19 := goal_19_intermediate initSM initPM hSM hPM hInit
  have hg20 := goal_20_intermediate initSM initPM hSM hPM hInit
  have hg21 := goal_21_intermediate initSM initPM hSM hPM hInit
  have hg22 := goal_22_intermediate initSM initPM hSM hPM hInit
  have hg23 := goal_23_intermediate initSM initPM hSM hPM hInit
  have hg24 := goal_24_intermediate initSM initPM hSM hPM hInit
  have hg25 := goal_25_intermediate initSM initPM hSM hPM hInit
  have hg26 := goal_26_intermediate initSM initPM hSM hPM hInit
  have hg27 := goal_27_intermediate initSM initPM hSM hPM hInit
  have hg28 := goal_28_intermediate initSM initPM hSM hPM hInit
  have hg29 := goal_29_intermediate initSM initPM hSM hPM hInit
  have hg30 := goal_30_intermediate initSM initPM hSM hPM hInit
  have hg31 := goal_31_intermediate initSM initPM hSM hPM hInit
  have hg32 := goal_32_intermediate initSM initPM hSM hPM hInit
  have hg33 := goal_33_intermediate initSM initPM hSM hPM hInit
  have hg34 := goal_34_intermediate initSM initPM hSM hPM hInit
  have hg35 := goal_35_intermediate initSM initPM hSM hPM hInit
  have hg36 := goal_36_intermediate initSM initPM hSM hPM hInit
  have hg37 := goal_37_intermediate initSM initPM hSM hPM hInit
  have hg38 := goal_38_intermediate initSM initPM hSM hPM hInit
  have hg39 := goal_39_intermediate initSM initPM hSM hPM hInit
  have hg40 := goal_40_intermediate initSM initPM hSM hPM hInit
  have hg41 := goal_41_intermediate initSM initPM hSM hPM hInit
  have hg42 := goal_42_intermediate initSM initPM hSM hPM hInit
  have hg43 := goal_43_intermediate initSM initPM hSM hPM hInit
  have hg44 := goal_44_intermediate initSM initPM hSM hPM hInit
  have hg45 := goal_45_intermediate initSM initPM hSM hPM hInit
  have hg46 := goal_46_intermediate initSM initPM hSM hPM hInit
  have hg47 := goal_47_intermediate initSM initPM hSM hPM hInit
  have hg48 := goal_48_intermediate initSM initPM hSM hPM hInit
  have hg49 := goal_49_intermediate initSM initPM hSM hPM hInit
  have hg50 := goal_50_intermediate initSM initPM hSM hPM hInit
  have hg51 := goal_51_intermediate initSM initPM hSM hPM hInit
  have hg52 := goal_52_intermediate initSM initPM hSM hPM hInit
  have hg53 := goal_53_intermediate initSM initPM hSM hPM hInit
  have hg54 := goal_54_intermediate initSM initPM hSM hPM hInit
  have hg55 := goal_55_intermediate initSM initPM hSM hPM hInit
  have hg56 := goal_56_intermediate initSM initPM hSM hPM hInit
  have hg57 := goal_57_intermediate initSM initPM hSM hPM hInit
  have hg58 := goal_58_intermediate initSM initPM hSM hPM hInit
  have hg59 := goal_59_intermediate initSM initPM hSM hPM hInit
  have hg60 := goal_60_intermediate initSM initPM hSM hPM hInit
  have hg61 := goal_61_intermediate initSM initPM hSM hPM hInit
  have hg62 := goal_62_intermediate initSM initPM hSM hPM hInit
  have hg63 := goal_63_intermediate initSM initPM hSM hPM hInit
  have hg64 := goal_64_intermediate initSM initPM hSM hPM hInit
  have hg65 := goal_65_intermediate initSM initPM hSM hPM hInit
  have hg66 := goal_66_intermediate initSM initPM hSM hPM hInit
  have hg67 := goal_67_intermediate initSM initPM hSM hPM hInit
  have hg68 := goal_68_intermediate initSM initPM hSM hPM hInit
  have hg69 := goal_69_intermediate initSM initPM hSM hPM hInit
  have hg70 := goal_70_intermediate initSM initPM hSM hPM hInit
  have hg71 := goal_71_intermediate initSM initPM hSM hPM hInit
  have hg72 := goal_72_intermediate initSM initPM hSM hPM hInit
  have hg73 := goal_73_intermediate initSM initPM hSM hPM hInit
  have hg74 := goal_74_intermediate initSM initPM hSM hPM hInit
  have hg75 := goal_75_intermediate initSM initPM hSM hPM hInit
  have hg76 := goal_76_intermediate initSM initPM hSM hPM hInit
  have hg77 := goal_77_intermediate initSM initPM hSM hPM hInit
  have hg78 := goal_78_intermediate initSM initPM hSM hPM hInit
  have hg79 := goal_79_intermediate initSM initPM hSM hPM hInit
  have hg80 := goal_80_intermediate initSM initPM hSM hPM hInit
  have hg81 := goal_81_intermediate initSM initPM hSM hPM hInit
  have hg82 := goal_82_intermediate initSM initPM hSM hPM hInit
  have hg83 := goal_83_intermediate initSM initPM hSM hPM hInit
  have hg84 := goal_84_intermediate initSM initPM hSM hPM hInit
  have hg85 := goal_85_intermediate initSM initPM hSM hPM hInit
  have hg86 := goal_86_intermediate initSM initPM hSM hPM hInit
  have hg87 := goal_87_intermediate initSM initPM hSM hPM hInit
  have hg88 := goal_88_intermediate initSM initPM hSM hPM hInit
  have hg89 := goal_89_intermediate initSM initPM hSM hPM hInit
  have hg90 := goal_90_intermediate initSM initPM hSM hPM hInit
  have hg91 := goal_91_intermediate initSM initPM hSM hPM hInit
  have hg92 := goal_92_intermediate initSM initPM hSM hPM hInit
  have hg93 := goal_93_intermediate initSM initPM hSM hPM hInit
  have hg94 := goal_94_intermediate initSM initPM hSM hPM hInit
  have hg95 := goal_95_intermediate initSM initPM hSM hPM hInit
  have hg96 := goal_96_intermediate initSM initPM hSM hPM hInit
  have hg97 := goal_97_intermediate initSM initPM hSM hPM hInit
  have hg98 := goal_98_intermediate initSM initPM hSM hPM hInit
  have hg99 := goal_99_intermediate initSM initPM hSM hPM hInit
  have hg100 := goal_100_intermediate initSM initPM hSM hPM hInit
  have hg101 := goal_101_intermediate initSM initPM hSM hPM hInit
  have hg102 := goal_102_intermediate initSM initPM hSM hPM hInit
  have hg103 := goal_103_intermediate initSM initPM hSM hPM hInit
  have hg104 := goal_104_intermediate initSM initPM hSM hPM hInit
  have hg105 := goal_105_intermediate initSM initPM hSM hPM hInit
  have hg106 := goal_106_intermediate initSM initPM hSM hPM hInit
  have hg251 := goal_251_intermediate initSM initPM hSM hPM hInit
  have hg254 := goal_254_intermediate initSM initPM hSM hPM hInit
  have hg256 := goal_256_intermediate initSM initPM hSM hPM hInit
  have hg257 := goal_257_intermediate initSM initPM hSM hPM hInit
  have hg259 := goal_259_intermediate initSM initPM hSM hPM hInit
  have hg261 := goal_261_intermediate initSM initPM hSM hPM hInit
  have hg263 := goal_263_intermediate initSM initPM hSM hPM hInit
  have hg265 := goal_265_intermediate initSM initPM hSM hPM hInit
  have hg267 := goal_267_intermediate initSM initPM hSM hPM hInit
  have hg269 := goal_269_intermediate initSM initPM hSM hPM hInit
  have hg271 := goal_271_intermediate initSM initPM hSM hPM hInit
  have hg273 := goal_273_intermediate initSM initPM hSM hPM hInit
  have hg275 := goal_275_intermediate initSM initPM hSM hPM hInit
  have hg277 := goal_277_intermediate initSM initPM hSM hPM hInit
  have hg279 := goal_279_intermediate initSM initPM hSM hPM hInit
  have hg281 := goal_281_intermediate initSM initPM hSM hPM hInit
  have hg283 := goal_283_intermediate initSM initPM hSM hPM hInit
  have hg285 := goal_285_intermediate initSM initPM hSM hPM hInit
  have hg287 := goal_287_intermediate initSM initPM hSM hPM hInit
  have hg289 := goal_289_intermediate initSM initPM hSM hPM hInit
  have hg291 := goal_291_intermediate initSM initPM hSM hPM hInit
  have hg293 := goal_293_intermediate initSM initPM hSM hPM hInit
  have hg295 := goal_295_intermediate initSM initPM hSM hPM hInit
  have hg297 := goal_297_intermediate initSM initPM hSM hPM hInit
  have hg299 := goal_299_intermediate initSM initPM hSM hPM hInit
  have hg301 := goal_301_intermediate initSM initPM hSM hPM hInit
  have hg303 := goal_303_intermediate initSM initPM hSM hPM hInit
  have hg305 := goal_305_intermediate initSM initPM hSM hPM hInit
  have hg307 := goal_307_intermediate initSM initPM hSM hPM hInit
  have hg309 := goal_309_intermediate initSM initPM hSM hPM hInit
  have hg311 := goal_311_intermediate initSM initPM hSM hPM hInit
  have hinitC := initGoals_preserved initSM initPM hInit
  have hnr : pm_goal_250.numRanks = pm.numRanks := by native_decide
  have h706_smsh : (Ssm 706).shape = [1, 8, 32] := by
    have h := hg103.1; simp only [goal_103] at h; exact h
  have h890_smsh : (Ssm 890).shape = [1, 8, 32] := by
    have h := hg251.1; simp only [goal_251] at h; exact h
  have h1067_smsh : (Ssm 1067).shape = [1, 8, 32] := by
    have h := hg311.1; simp only [goal_311] at h; exact h
  have h706_pmsh : (Spm 706).shape = [1, 8, 32] := by
    have h := hg103.2.1
    simp only [goal_103, List.map, List.cons.injEq, and_true] at h
    exact h
  have h251tp := hg251.2.1
  simp only [goal_251, List.map, List.cons.injEq, and_true] at h251tp
  obtain ⟨h3335_pmsh, h3338_pmsh, h3341_pmsh, h3344_pmsh⟩ := h251tp
  have h311tp := hg311.2.1
  simp only [goal_311, List.map, List.cons.injEq, and_true] at h311tp
  obtain ⟨h3313_pmsh, h3314_pmsh, h3315_pmsh, h3316_pmsh⟩ := h311tp
  have hSM250 : StoreShapesHold Ssm sm_goal_250InitEnv := by
    intro tid sh hsh
    rw [sm_goal_250InitEnv] at hsh
    have hmem := mem_of_shapeEnvOfList_eq_some hsh
    simp only [sm_goal_250InitShapes, List.mem_cons, List.not_mem_nil, or_false,
               Prod.mk.injEq] at hmem
    rcases hmem with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact h706_smsh
    · exact h890_smsh
    · exact h1067_smsh
  have hPM250 : StoreShapesHold Spm pm_goal_250InitEnv := by
    intro tid sh hsh
    rw [pm_goal_250InitEnv] at hsh
    have hmem := mem_of_shapeEnvOfList_eq_some hsh
    simp only [pm_goal_250InitShapes, List.mem_cons, List.not_mem_nil, or_false,
               Prod.mk.injEq] at hmem
    rcases hmem with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact h706_pmsh
    · exact h3313_pmsh
    · exact h3314_pmsh
    · exact h3315_pmsh
    · exact h3316_pmsh
    · exact h3335_pmsh
    · exact h3338_pmsh
    · exact h3341_pmsh
    · exact h3344_pmsh

  have hInitCut : InitGoalsHold pm_goal_250.numRanks goal_250_cut_initGoals Ssm Spm :=
    goal_250_hInitCut_helper Ssm Spm hinitC hg2 hg3 hg4 hg5 hg6 hg7 hg8 hg9 hg10 hg11 hg12 hg13 hg14 hg15 hg16 hg17 hg18 hg19 hg20 hg21 hg22 hg23 hg24 hg25 hg26 hg27 hg28 hg29 hg30 hg31 hg32 hg33 hg34 hg35 hg36 hg37 hg38 hg39 hg40 hg41 hg42 hg43 hg44 hg45 hg46 hg47 hg48 hg49 hg50 hg51 hg52 hg53 hg54 hg55 hg56 hg57 hg58 hg59 hg60 hg61 hg62 hg63 hg64 hg65 hg66 hg67 hg68 hg69 hg70 hg71 hg72 hg73 hg74 hg75 hg76 hg77 hg78 hg79 hg80 hg81 hg82 hg83 hg84 hg85 hg86 hg87 hg88 hg89 hg90 hg91 hg92 hg93 hg94 hg95 hg96 hg97 hg98 hg99 hg100 hg101 hg102 hg103 hg104 hg105 hg106 hg251 hg254 hg256 hg257 hg259 hg261 hg263 hg265 hg267 hg269 hg271 hg273 hg275 hg277 hg279 hg281 hg283 hg285 hg287 hg289 hg291 hg293 hg295 hg297 hg299 hg301 hg303 hg305 hg307 hg309 hg311
  have hcut := h Ssm Spm hSM250 hPM250 hInitCut
  have hsmf : Ssm 889 = denoteGraph sm_goal_250 Ssm 889 := by
    rw [hSsm]; exact sm_frame_889_self initSM
  have hpm889 : Spm 889 = denoteGraph pm_goal_250 Spm 889 := by
    rw [denote_pm_goal_250_889]; rw [hSpm]; exact pm_frame_889_self initPM
  rw [hnr] at hcut
  simp only [goal_250, List.map] at hcut ⊢
  rw [hsmf, hpm889]
  exact hcut

theorem goal_250_intermediate (initSM initPM : Store)
    (hSM : StoreShapesHold initSM smInitEnv) (hPM : StoreShapesHold initPM pmInitEnv)
    (hInit : InitGoalsHold pm.numRanks initGoals initSM initPM) :
    InitGoalHolds pm.numRanks goal_250 (denoteGraph sm initSM) (denoteGraph pm initPM) := by
  have hfull : goal_250_stmt := goal_250_cut_to_full prove_goal_250_cut
  have := hfull initSM initPM hSM hPM hInit
  simpa [InitGoalHolds, goal_250] using this

end TrainVerify.Denote.GeneratedGoals
