/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 249 (tensor id: 888)
-/
import denote.gpt_ly4_regen.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_249 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_linear", ins := [889, 704, 705], outs := [887, 888] },
  ]

def pm_goal_249 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.AllToAllPrim", ins := [3265, 3266, 3267, 3268], outs := [3285], params := [1, 2] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [3265, 3266, 3267, 3268], outs := [3286], params := [1, 2] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [3265, 3266, 3267, 3268], outs := [3287], params := [1, 2] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [3265, 3266, 3267, 3268], outs := [3288], params := [1, 2] },
    { rank := 0, op := "OpName.BW_linear", ins := [889, 3285, 3289], outs := [3305, 3306] },
    { rank := 1, op := "OpName.BW_linear", ins := [889, 3286, 3290], outs := [3307, 3308] },
    { rank := 2, op := "OpName.BW_linear", ins := [889, 3287, 3291], outs := [3309, 3310] },
    { rank := 3, op := "OpName.BW_linear", ins := [889, 3288, 3292], outs := [3311, 3312] },
  ]

def sm_goal_249InitShapes : List (Tid × Shape) := [
  (704, [1, 8, 128]),
  (705, [32, 128]),
  (889, [1, 8, 32]),
]

def sm_goal_249InitEnv : ShapeEnv := shapeEnvOfList sm_goal_249InitShapes

def pm_goal_249InitShapes : List (Tid × Shape) := [
  (889, [1, 8, 32]),
  (3265, [1, 2, 128]),
  (3266, [1, 2, 128]),
  (3267, [1, 2, 128]),
  (3268, [1, 2, 128]),
  (3289, [32, 32]),
  (3290, [32, 32]),
  (3291, [32, 32]),
  (3292, [32, 32]),
]

def pm_goal_249InitEnv : ShapeEnv := shapeEnvOfList pm_goal_249InitShapes

def goal_249_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_105, goal_106, goal_250, goal_251, goal_254, goal_256, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_287, goal_289, goal_291, goal_293, goal_295, goal_297, goal_299, goal_301, goal_303, goal_305, goal_307, goal_309, goal_311]
def goal_249_cut_initGoals : List LineageGoal := initGoals ++ goal_249_prereqs

def goal_249_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_249 pm_goal_249 goal_249 sm_goal_249InitEnv pm_goal_249InitEnv goal_249_cut_initGoals

set_option maxRecDepth 4096 in
set_option maxHeartbeats 1600000 in
-- BW_linear dW with AllToAll-distributed input.  x (704, [1,8,128]) is sharded along its
-- last (input-feature) dim via AllToAllPrim params [1,2] into four [1,8,32] chunks; g (889)
-- is replicated; w (705, [32,128]) is split along dim 1.  dW depends only on g and x, so the
-- full dW (888 = [32,128]) is the dim-1 all-gather of the four per-rank dW shards (each [32,32]).
theorem prove_goal_249_cut : goal_249_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  -- Prereqs: goal_102 (x=704 gather dim1 from 3265..3268), initGoal_705 (w=705),
  -- goal_250 (g=889 replicated).
  have hInit102 : InitGoalHolds pm_goal_249.numRanks goal_102 initSM initPM := by
    apply hInitGoals; simp only [goal_249_cut_initGoals, goal_249_prereqs]; decide
  have hInit705 : InitGoalHolds pm_goal_249.numRanks initGoal_705 initSM initPM := by
    apply hInitGoals; simp only [goal_249_cut_initGoals, goal_249_prereqs, initGoals]; decide
  have hInit250 : InitGoalHolds pm_goal_249.numRanks goal_250 initSM initPM := by
    apply hInitGoals; simp only [goal_249_cut_initGoals, goal_249_prereqs]; decide
  -- goal_102 input-shard shapes [1,2,128]
  have htp102 := hInit102.2.1
  simp only [goal_102, List.map] at htp102
  have h3265_shape : (initPM 3265).shape = [1, 2, 128] := by
    have := congrArg List.head? htp102; simpa using this
  have h3266_shape : (initPM 3266).shape = [1, 2, 128] := by
    have := congrArg (List.head? ∘ List.tail) htp102; simpa using this
  have h3267_shape : (initPM 3267).shape = [1, 2, 128] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail) htp102; simpa using this
  have h3268_shape : (initPM 3268).shape = [1, 2, 128] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail ∘ List.tail) htp102; simpa using this
  -- goal_102: initSM 704 = reconstructWithDim 1 4 0 [3265,3266,3267,3268] = dim-1 all-gather
  have h704_rec : initSM 704 = reconstructWithDim 1 4 0
      [initPM 3265, initPM 3266, initPM 3267, initPM 3268] := by
    have hrec := hInit102.2.2
    simp only [goal_102, pm_goal_249, List.map] at hrec
    exact hrec
  have h704_gather : initSM 704 = allGatherPrimDimN 1 4 0
      [initPM 3265, initPM 3266, initPM 3267, initPM 3268] := by
    rw [h704_rec]
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    exact reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _ (by rw [h3265_shape]; decide)
  have hC_shape : (allGatherPrimDimN 1 4 0
      [initPM 3265, initPM 3266, initPM 3267, initPM 3268]).shape = [1, 8, 128] := by
    rw [allGatherPrimDimN_shape 1 4 _ [1, 2, 128] (by simp [h3265_shape])]
    simp [List.set, List.getD]
  -- initGoal_705 weight-shard shapes [32,32]
  have htp705 := hInit705.2.1
  simp only [initGoal_705, List.map] at htp705
  have h3289_shape : (initPM 3289).shape = [32, 32] := by
    have := congrArg List.head? htp705; simpa using this
  have h3290_shape : (initPM 3290).shape = [32, 32] := by
    have := congrArg (List.head? ∘ List.tail) htp705; simpa using this
  have h3291_shape : (initPM 3291).shape = [32, 32] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail) htp705; simpa using this
  have h3292_shape : (initPM 3292).shape = [32, 32] := by
    have := congrArg (List.head? ∘ List.tail ∘ List.tail ∘ List.tail) htp705; simpa using this
  have h705_shape : (initSM 705).shape = [32, 128] := hInit705.1
  -- goal_250: g=889 replicated
  have h889_eq : initSM 889 = initPM 889 := by
    have hrec := hInit250.2.2
    simp only [goal_250, pm_goal_249, List.map] at hrec
    first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] at hrec | skip
    rw [reconstructWithDim_singleton] at hrec; exact hrec
  have h889_shape : (initSM 889).shape = [1, 8, 32] := hInit250.1
  have h889P_shape : (initPM 889).shape = [1, 8, 32] := by rw [← h889_eq]; exact h889_shape
  -- SM store: dW (snd output, tid 888) of BW_linear on full tensors
  have hsm : (denoteGraph sm_goal_249 initSM) 888 =
      (bw_linear (initSM 889) (initSM 704) (initSM 705)).2 := by
    simp only [sm_goal_249, denoteGraph, List.foldl]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
  -- PM stores: each rank's BW_linear consumes its local AllToAll output, which is
  -- definitionally `chunkPrimDimN 2 4 r (allGatherPrimDimN 1 4 0 [3265..3268])`.
  have hpm0 : (denoteGraph pm_goal_249 initPM) 3306 =
      (bw_linear (initPM 889)
        (chunkPrimDimN 2 4 0 (allGatherPrimDimN 1 4 0
          [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3289)).2 := by
    simp only [pm_goal_249, denoteGraph, List.foldl]
    rw [applyNode_skip (h := by decide), applyNode_skip (h := by decide),
        applyNode_skip (h := by decide), applyNode_bw_linear_snd_out (hne := by decide)]
    rfl
  have hpm1 : (denoteGraph pm_goal_249 initPM) 3308 =
      (bw_linear (initPM 889)
        (chunkPrimDimN 2 4 1 (allGatherPrimDimN 1 4 0
          [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3290)).2 := by
    simp only [pm_goal_249, denoteGraph, List.foldl]
    rw [applyNode_skip (h := by decide), applyNode_skip (h := by decide),
        applyNode_bw_linear_snd_out (hne := by decide)]
    rfl
  have hpm2 : (denoteGraph pm_goal_249 initPM) 3310 =
      (bw_linear (initPM 889)
        (chunkPrimDimN 2 4 2 (allGatherPrimDimN 1 4 0
          [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3291)).2 := by
    simp only [pm_goal_249, denoteGraph, List.foldl]
    rw [applyNode_skip (h := by decide), applyNode_bw_linear_snd_out (hne := by decide)]
    rfl
  have hpm3 : (denoteGraph pm_goal_249 initPM) 3312 =
      (bw_linear (initPM 889)
        (chunkPrimDimN 2 4 3 (allGatherPrimDimN 1 4 0
          [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3292)).2 := by
    simp only [pm_goal_249, denoteGraph, List.foldl]
    rw [applyNode_bw_linear_snd_out (hne := by decide)]
    rfl
  -- per-rank dW shapes
  have hd0 : (bw_linear (initPM 889)
      (chunkPrimDimN 2 4 0 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3289)).2.shape = [32, 32] := by
    have hch : (chunkPrimDimN 2 4 0 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])).shape = [1, 8, 32] := by
      rw [chunkPrimDimN_shape 2 4 0 _ _ hC_shape (by omega)]; simp [List.set, List.getD]
    exact bw_linear_3d_snd_shape 1 8 32 32 _ _ _ h889P_shape hch h3289_shape
  have hd1 : (bw_linear (initPM 889)
      (chunkPrimDimN 2 4 1 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3290)).2.shape = [32, 32] := by
    have hch : (chunkPrimDimN 2 4 1 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])).shape = [1, 8, 32] := by
      rw [chunkPrimDimN_shape 2 4 1 _ _ hC_shape (by omega)]; simp [List.set, List.getD]
    exact bw_linear_3d_snd_shape 1 8 32 32 _ _ _ h889P_shape hch h3290_shape
  have hd2 : (bw_linear (initPM 889)
      (chunkPrimDimN 2 4 2 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3291)).2.shape = [32, 32] := by
    have hch : (chunkPrimDimN 2 4 2 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])).shape = [1, 8, 32] := by
      rw [chunkPrimDimN_shape 2 4 2 _ _ hC_shape (by omega)]; simp [List.set, List.getD]
    exact bw_linear_3d_snd_shape 1 8 32 32 _ _ _ h889P_shape hch h3291_shape
  have hd3 : (bw_linear (initPM 889)
      (chunkPrimDimN 2 4 3 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])) (initPM 3292)).2.shape = [32, 32] := by
    have hch : (chunkPrimDimN 2 4 3 (allGatherPrimDimN 1 4 0
        [initPM 3265, initPM 3266, initPM 3267, initPM 3268])).shape = [1, 8, 32] := by
      rw [chunkPrimDimN_shape 2 4 3 _ _ hC_shape (by omega)]; simp [List.set, List.getD]
    exact bw_linear_3d_snd_shape 1 8 32 32 _ _ _ h889P_shape hch h3292_shape
  -- Discharge the three conjuncts.
  simp only [goal_249, List.map]
  refine ⟨?_, ?_, ?_⟩
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    -- SM output shape: [32, 128]
    rw [hsm, h889_eq, h704_gather,
        bw_linear_3d_snd_shape 1 8 32 128 _ _ _ h889P_shape hC_shape h705_shape]
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    -- PM tp shapes
    rw [hpm0, hpm1, hpm2, hpm3, hd0, hd1, hd2, hd3]
  · first | rw [reconstructForGoal_of_not_replicated _ _ _ (by rfl)] | skip
    -- Value equality
    rw [show pm_goal_249.numRanks = 4 from rfl, hpm0, hpm1, hpm2, hpm3,
        reconstructWithDim_cons_cons_nonscalar 1 4 0 _ _ _ (by rw [hd0]; decide),
        hsm, h889_eq, h704_gather,
        bw_linear_dw_xsplit_dim2_4_1_8_128_g249 (initPM 889)
          (allGatherPrimDimN 1 4 0 [initPM 3265, initPM 3266, initPM 3267, initPM 3268])
          (initSM 705) (initPM 3289) (initPM 3290) (initPM 3291) (initPM 3292)
          h889P_shape hC_shape h705_shape
          h3289_shape h3290_shape h3291_shape h3292_shape]

end TrainVerify.Denote.GeneratedGoals
