/- AUTO-GENERATED by bridge_emitter (FAMILY-A: multi-tp, 0 mid, per-rank op).
   goal_100: SM=FW_layernorm([1063, 699, 700])->701;
   PM=4xFW_layernorm(per-rank inputs)->[3205, 3206, 3207, 3208] multi-tps gatherDim=1.
   prereqs=[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309] (len 125). Inputs sourced from: 699<-init:699, 700<-init:700, 1063<-ts:309, 3201<-tp:309, 3202<-tp:309, 3203<-tp:309, 3204<-tp:309. -/
import denote.gpt_ly4_regen.BridgeKit
import denote.gpt_ly4_regen.SpikeBridge
import denote.gpt_ly4_regen.Goal3Bridge
import denote.gpt_ly4_regen.Goal4Bridge
import denote.gpt_ly4_regen.Goal5Bridge
import denote.gpt_ly4_regen.Goal6Bridge
import denote.gpt_ly4_regen.Goal7Bridge
import denote.gpt_ly4_regen.Goal8Bridge
import denote.gpt_ly4_regen.Goal9Bridge
import denote.gpt_ly4_regen.Goal10Bridge
import denote.gpt_ly4_regen.Goal11Bridge
import denote.gpt_ly4_regen.Goal12Bridge
import denote.gpt_ly4_regen.Goal13Bridge
import denote.gpt_ly4_regen.Goal14Bridge
import denote.gpt_ly4_regen.Goal15Bridge
import denote.gpt_ly4_regen.Goal16Bridge
import denote.gpt_ly4_regen.Goal17Bridge
import denote.gpt_ly4_regen.Goal18Bridge
import denote.gpt_ly4_regen.Goal19Bridge
import denote.gpt_ly4_regen.Goal20Bridge
import denote.gpt_ly4_regen.Goal21Bridge
import denote.gpt_ly4_regen.Goal22Bridge
import denote.gpt_ly4_regen.Goal23Bridge
import denote.gpt_ly4_regen.Goal24Bridge
import denote.gpt_ly4_regen.Goal25Bridge
import denote.gpt_ly4_regen.Goal26Bridge
import denote.gpt_ly4_regen.Goal27Bridge
import denote.gpt_ly4_regen.Goal28Bridge
import denote.gpt_ly4_regen.Goal29Bridge
import denote.gpt_ly4_regen.Goal30Bridge
import denote.gpt_ly4_regen.Goal31Bridge
import denote.gpt_ly4_regen.Goal32Bridge
import denote.gpt_ly4_regen.Goal33Bridge
import denote.gpt_ly4_regen.Goal34Bridge
import denote.gpt_ly4_regen.Goal35Bridge
import denote.gpt_ly4_regen.Goal36Bridge
import denote.gpt_ly4_regen.Goal37Bridge
import denote.gpt_ly4_regen.Goal38Bridge
import denote.gpt_ly4_regen.Goal39Bridge
import denote.gpt_ly4_regen.Goal40Bridge
import denote.gpt_ly4_regen.Goal41Bridge
import denote.gpt_ly4_regen.Goal42Bridge
import denote.gpt_ly4_regen.Goal43Bridge
import denote.gpt_ly4_regen.Goal44Bridge
import denote.gpt_ly4_regen.Goal45Bridge
import denote.gpt_ly4_regen.Goal46Bridge
import denote.gpt_ly4_regen.Goal47Bridge
import denote.gpt_ly4_regen.Goal48Bridge
import denote.gpt_ly4_regen.Goal49Bridge
import denote.gpt_ly4_regen.Goal50Bridge
import denote.gpt_ly4_regen.Goal51Bridge
import denote.gpt_ly4_regen.Goal52Bridge
import denote.gpt_ly4_regen.Goal53Bridge
import denote.gpt_ly4_regen.Goal54Bridge
import denote.gpt_ly4_regen.Goal55Bridge
import denote.gpt_ly4_regen.Goal56Bridge
import denote.gpt_ly4_regen.Goal57Bridge
import denote.gpt_ly4_regen.Goal58Bridge
import denote.gpt_ly4_regen.Goal59Bridge
import denote.gpt_ly4_regen.Goal60Bridge
import denote.gpt_ly4_regen.Goal61Bridge
import denote.gpt_ly4_regen.Goal62Bridge
import denote.gpt_ly4_regen.Goal63Bridge
import denote.gpt_ly4_regen.Goal64Bridge
import denote.gpt_ly4_regen.Goal65Bridge
import denote.gpt_ly4_regen.Goal66Bridge
import denote.gpt_ly4_regen.Goal67Bridge
import denote.gpt_ly4_regen.Goal68Bridge
import denote.gpt_ly4_regen.Goal69Bridge
import denote.gpt_ly4_regen.Goal70Bridge
import denote.gpt_ly4_regen.Goal71Bridge
import denote.gpt_ly4_regen.Goal72Bridge
import denote.gpt_ly4_regen.Goal73Bridge
import denote.gpt_ly4_regen.Goal74Bridge
import denote.gpt_ly4_regen.Goal75Bridge
import denote.gpt_ly4_regen.Goal76Bridge
import denote.gpt_ly4_regen.Goal77Bridge
import denote.gpt_ly4_regen.Goal78Bridge
import denote.gpt_ly4_regen.Goal79Bridge
import denote.gpt_ly4_regen.Goal80Bridge
import denote.gpt_ly4_regen.Goal81Bridge
import denote.gpt_ly4_regen.Goal82Bridge
import denote.gpt_ly4_regen.Goal83Bridge
import denote.gpt_ly4_regen.Goal84Bridge
import denote.gpt_ly4_regen.Goal85Bridge
import denote.gpt_ly4_regen.Goal86Bridge
import denote.gpt_ly4_regen.Goal87Bridge
import denote.gpt_ly4_regen.Goal88Bridge
import denote.gpt_ly4_regen.Goal89Bridge
import denote.gpt_ly4_regen.Goal90Bridge
import denote.gpt_ly4_regen.Goal91Bridge
import denote.gpt_ly4_regen.Goal92Bridge
import denote.gpt_ly4_regen.Goal93Bridge
import denote.gpt_ly4_regen.Goal94Bridge
import denote.gpt_ly4_regen.Goal95Bridge
import denote.gpt_ly4_regen.Goal96Bridge
import denote.gpt_ly4_regen.Goal97Bridge
import denote.gpt_ly4_regen.Goal98Bridge
import denote.gpt_ly4_regen.Goal99Bridge
import denote.gpt_ly4_regen.Goal257Bridge
import denote.gpt_ly4_regen.Goal259Bridge
import denote.gpt_ly4_regen.Goal261Bridge
import denote.gpt_ly4_regen.Goal263Bridge
import denote.gpt_ly4_regen.Goal265Bridge
import denote.gpt_ly4_regen.Goal267Bridge
import denote.gpt_ly4_regen.Goal269Bridge
import denote.gpt_ly4_regen.Goal271Bridge
import denote.gpt_ly4_regen.Goal273Bridge
import denote.gpt_ly4_regen.Goal275Bridge
import denote.gpt_ly4_regen.Goal277Bridge
import denote.gpt_ly4_regen.Goal279Bridge
import denote.gpt_ly4_regen.Goal281Bridge
import denote.gpt_ly4_regen.Goal283Bridge
import denote.gpt_ly4_regen.Goal285Bridge
import denote.gpt_ly4_regen.Goal287Bridge
import denote.gpt_ly4_regen.Goal289Bridge
import denote.gpt_ly4_regen.Goal291Bridge
import denote.gpt_ly4_regen.Goal293Bridge
import denote.gpt_ly4_regen.Goal295Bridge
import denote.gpt_ly4_regen.Goal297Bridge
import denote.gpt_ly4_regen.Goal299Bridge
import denote.gpt_ly4_regen.Goal301Bridge
import denote.gpt_ly4_regen.Goal303Bridge
import denote.gpt_ly4_regen.Goal305Bridge
import denote.gpt_ly4_regen.Goal307Bridge
import denote.gpt_ly4_regen.Goal309Bridge
import denote.gpt_ly4_regen.Goal_100

set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.style.nativeDecide false
set_option linter.unusedSimpArgs false
set_option linter.style.commandStart false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option linter.unusedVariables false
set_option linter.style.show false
set_option linter.style.setOption false
set_option linter.unnecessarySeqFocus false
set_option linter.flexible false

namespace TrainVerify.Denote.GeneratedGoals
open TrainVerify.Denote TrainVerify.Denote.Generated

-- ========== mini sm_goal_100 computes 701 (FW_layernorm) ==========
theorem denote_sm_goal_100_701 (s : Store) :
    denoteGraph sm_goal_100 s 701 = fw_layernorm (s 1063) (s 699) (s 700) := by
  simp only [sm_goal_100, denoteGraph, List.foldl]
  rw [applyNode_fw_layernorm_out]

-- ========== SM self-frame ==========
theorem sm_frame_701_self (initSM : Store) :
    denoteGraph sm initSM 701 = denoteGraph sm_goal_100 (denoteGraph sm initSM) 701 := by
  rw [denote_sm_goal_100_701]
  rw [sm_val initSM 110 701 (by native_decide) (by native_decide)]
  rw [show sm.nodes[110]'(by native_decide)
      = { rank := 0, op := "OpName.FW_layernorm", ins := [1063, 699, 700], outs := [701] }
      from by native_decide]
  rw [applyNode_fw_layernorm_out]
  rw [sm_prefix_eq initSM 110 1063 (by native_decide),
      sm_prefix_eq initSM 110 699 (by native_decide),
      sm_prefix_eq initSM 110 700 (by native_decide)]

-- ========== denote_pm (final tps [3205, 3206, 3207, 3208]) ==========
theorem denote_pm_goal_100_3205 (s : Store) :
    denoteGraph pm_goal_100 s 3205 = fw_layernorm (s 3201) (s 699) (s 700) := by
  simp only [pm_goal_100, denoteGraph, List.foldl]
  repeat rw [applyNode_skip _ _ _ 3205 (by decide)]
  rw [applyNode_fw_layernorm_out]
  repeat rw [applyNode_skip _ _ _ 3201 (by decide)]
  repeat rw [applyNode_skip _ _ _ 699 (by decide)]
  repeat rw [applyNode_skip _ _ _ 700 (by decide)]

theorem denote_pm_goal_100_3206 (s : Store) :
    denoteGraph pm_goal_100 s 3206 = fw_layernorm (s 3202) (s 699) (s 700) := by
  simp only [pm_goal_100, denoteGraph, List.foldl]
  repeat rw [applyNode_skip _ _ _ 3206 (by decide)]
  rw [applyNode_fw_layernorm_out]
  repeat rw [applyNode_skip _ _ _ 3202 (by decide)]
  repeat rw [applyNode_skip _ _ _ 699 (by decide)]
  repeat rw [applyNode_skip _ _ _ 700 (by decide)]

theorem denote_pm_goal_100_3207 (s : Store) :
    denoteGraph pm_goal_100 s 3207 = fw_layernorm (s 3203) (s 699) (s 700) := by
  simp only [pm_goal_100, denoteGraph, List.foldl]
  repeat rw [applyNode_skip _ _ _ 3207 (by decide)]
  rw [applyNode_fw_layernorm_out]
  repeat rw [applyNode_skip _ _ _ 3203 (by decide)]
  repeat rw [applyNode_skip _ _ _ 699 (by decide)]
  repeat rw [applyNode_skip _ _ _ 700 (by decide)]

theorem denote_pm_goal_100_3208 (s : Store) :
    denoteGraph pm_goal_100 s 3208 = fw_layernorm (s 3204) (s 699) (s 700) := by
  simp only [pm_goal_100, denoteGraph, List.foldl]
  repeat rw [applyNode_skip _ _ _ 3208 (by decide)]
  rw [applyNode_fw_layernorm_out]
  repeat rw [applyNode_skip _ _ _ 3204 (by decide)]
  repeat rw [applyNode_skip _ _ _ 699 (by decide)]
  repeat rw [applyNode_skip _ _ _ 700 (by decide)]

-- ========== pm_frame (final tps) ==========
theorem pm_frame_3205_self (initPM : Store) :
    denoteGraph pm initPM 3205
      = fw_layernorm (denoteGraph pm initPM 3201) (denoteGraph pm initPM 699) (denoteGraph pm initPM 700) := by
  rw [pm_val initPM 724 3205 (by native_decide) (by native_decide)]
  rw [show pm.nodes[724]'(by native_decide)
      = { rank := 0, op := "OpName.FW_layernorm", ins := [3201, 699, 700], outs := [3205] }
      from by native_decide]
  rw [applyNode_fw_layernorm_out]
  rw [pm_prefix_eq initPM 724 3201 (by native_decide),
      pm_prefix_eq initPM 724 699 (by native_decide),
      pm_prefix_eq initPM 724 700 (by native_decide)]

theorem pm_frame_3206_self (initPM : Store) :
    denoteGraph pm initPM 3206
      = fw_layernorm (denoteGraph pm initPM 3202) (denoteGraph pm initPM 699) (denoteGraph pm initPM 700) := by
  rw [pm_val initPM 725 3206 (by native_decide) (by native_decide)]
  rw [show pm.nodes[725]'(by native_decide)
      = { rank := 1, op := "OpName.FW_layernorm", ins := [3202, 699, 700], outs := [3206] }
      from by native_decide]
  rw [applyNode_fw_layernorm_out]
  rw [pm_prefix_eq initPM 725 3202 (by native_decide),
      pm_prefix_eq initPM 725 699 (by native_decide),
      pm_prefix_eq initPM 725 700 (by native_decide)]

theorem pm_frame_3207_self (initPM : Store) :
    denoteGraph pm initPM 3207
      = fw_layernorm (denoteGraph pm initPM 3203) (denoteGraph pm initPM 699) (denoteGraph pm initPM 700) := by
  rw [pm_val initPM 726 3207 (by native_decide) (by native_decide)]
  rw [show pm.nodes[726]'(by native_decide)
      = { rank := 2, op := "OpName.FW_layernorm", ins := [3203, 699, 700], outs := [3207] }
      from by native_decide]
  rw [applyNode_fw_layernorm_out]
  rw [pm_prefix_eq initPM 726 3203 (by native_decide),
      pm_prefix_eq initPM 726 699 (by native_decide),
      pm_prefix_eq initPM 726 700 (by native_decide)]

theorem pm_frame_3208_self (initPM : Store) :
    denoteGraph pm initPM 3208
      = fw_layernorm (denoteGraph pm initPM 3204) (denoteGraph pm initPM 699) (denoteGraph pm initPM 700) := by
  rw [pm_val initPM 727 3208 (by native_decide) (by native_decide)]
  rw [show pm.nodes[727]'(by native_decide)
      = { rank := 3, op := "OpName.FW_layernorm", ins := [3204, 699, 700], outs := [3208] }
      from by native_decide]
  rw [applyNode_fw_layernorm_out]
  rw [pm_prefix_eq initPM 727 3204 (by native_decide),
      pm_prefix_eq initPM 727 699 (by native_decide),
      pm_prefix_eq initPM 727 700 (by native_decide)]

-- ========== helper: hInitCut separate lemma (heartbeat workaround) ==========
lemma goal_100_hInitCut_helper (Ssm Spm : Store)
    (hinitC : InitGoalsHold pm.numRanks initGoals Ssm Spm)
    (hg2 : InitGoalHolds pm.numRanks goal_2 Ssm Spm)
    (hg3 : InitGoalHolds pm.numRanks goal_3 Ssm Spm)
    (hg4 : InitGoalHolds pm.numRanks goal_4 Ssm Spm)
    (hg5 : InitGoalHolds pm.numRanks goal_5 Ssm Spm)
    (hg6 : InitGoalHolds pm.numRanks goal_6 Ssm Spm)
    (hg7 : InitGoalHolds pm.numRanks goal_7 Ssm Spm)
    (hg8 : InitGoalHolds pm.numRanks goal_8 Ssm Spm)
    (hg9 : InitGoalHolds pm.numRanks goal_9 Ssm Spm)
    (hg10 : InitGoalHolds pm.numRanks goal_10 Ssm Spm)
    (hg11 : InitGoalHolds pm.numRanks goal_11 Ssm Spm)
    (hg12 : InitGoalHolds pm.numRanks goal_12 Ssm Spm)
    (hg13 : InitGoalHolds pm.numRanks goal_13 Ssm Spm)
    (hg14 : InitGoalHolds pm.numRanks goal_14 Ssm Spm)
    (hg15 : InitGoalHolds pm.numRanks goal_15 Ssm Spm)
    (hg16 : InitGoalHolds pm.numRanks goal_16 Ssm Spm)
    (hg17 : InitGoalHolds pm.numRanks goal_17 Ssm Spm)
    (hg18 : InitGoalHolds pm.numRanks goal_18 Ssm Spm)
    (hg19 : InitGoalHolds pm.numRanks goal_19 Ssm Spm)
    (hg20 : InitGoalHolds pm.numRanks goal_20 Ssm Spm)
    (hg21 : InitGoalHolds pm.numRanks goal_21 Ssm Spm)
    (hg22 : InitGoalHolds pm.numRanks goal_22 Ssm Spm)
    (hg23 : InitGoalHolds pm.numRanks goal_23 Ssm Spm)
    (hg24 : InitGoalHolds pm.numRanks goal_24 Ssm Spm)
    (hg25 : InitGoalHolds pm.numRanks goal_25 Ssm Spm)
    (hg26 : InitGoalHolds pm.numRanks goal_26 Ssm Spm)
    (hg27 : InitGoalHolds pm.numRanks goal_27 Ssm Spm)
    (hg28 : InitGoalHolds pm.numRanks goal_28 Ssm Spm)
    (hg29 : InitGoalHolds pm.numRanks goal_29 Ssm Spm)
    (hg30 : InitGoalHolds pm.numRanks goal_30 Ssm Spm)
    (hg31 : InitGoalHolds pm.numRanks goal_31 Ssm Spm)
    (hg32 : InitGoalHolds pm.numRanks goal_32 Ssm Spm)
    (hg33 : InitGoalHolds pm.numRanks goal_33 Ssm Spm)
    (hg34 : InitGoalHolds pm.numRanks goal_34 Ssm Spm)
    (hg35 : InitGoalHolds pm.numRanks goal_35 Ssm Spm)
    (hg36 : InitGoalHolds pm.numRanks goal_36 Ssm Spm)
    (hg37 : InitGoalHolds pm.numRanks goal_37 Ssm Spm)
    (hg38 : InitGoalHolds pm.numRanks goal_38 Ssm Spm)
    (hg39 : InitGoalHolds pm.numRanks goal_39 Ssm Spm)
    (hg40 : InitGoalHolds pm.numRanks goal_40 Ssm Spm)
    (hg41 : InitGoalHolds pm.numRanks goal_41 Ssm Spm)
    (hg42 : InitGoalHolds pm.numRanks goal_42 Ssm Spm)
    (hg43 : InitGoalHolds pm.numRanks goal_43 Ssm Spm)
    (hg44 : InitGoalHolds pm.numRanks goal_44 Ssm Spm)
    (hg45 : InitGoalHolds pm.numRanks goal_45 Ssm Spm)
    (hg46 : InitGoalHolds pm.numRanks goal_46 Ssm Spm)
    (hg47 : InitGoalHolds pm.numRanks goal_47 Ssm Spm)
    (hg48 : InitGoalHolds pm.numRanks goal_48 Ssm Spm)
    (hg49 : InitGoalHolds pm.numRanks goal_49 Ssm Spm)
    (hg50 : InitGoalHolds pm.numRanks goal_50 Ssm Spm)
    (hg51 : InitGoalHolds pm.numRanks goal_51 Ssm Spm)
    (hg52 : InitGoalHolds pm.numRanks goal_52 Ssm Spm)
    (hg53 : InitGoalHolds pm.numRanks goal_53 Ssm Spm)
    (hg54 : InitGoalHolds pm.numRanks goal_54 Ssm Spm)
    (hg55 : InitGoalHolds pm.numRanks goal_55 Ssm Spm)
    (hg56 : InitGoalHolds pm.numRanks goal_56 Ssm Spm)
    (hg57 : InitGoalHolds pm.numRanks goal_57 Ssm Spm)
    (hg58 : InitGoalHolds pm.numRanks goal_58 Ssm Spm)
    (hg59 : InitGoalHolds pm.numRanks goal_59 Ssm Spm)
    (hg60 : InitGoalHolds pm.numRanks goal_60 Ssm Spm)
    (hg61 : InitGoalHolds pm.numRanks goal_61 Ssm Spm)
    (hg62 : InitGoalHolds pm.numRanks goal_62 Ssm Spm)
    (hg63 : InitGoalHolds pm.numRanks goal_63 Ssm Spm)
    (hg64 : InitGoalHolds pm.numRanks goal_64 Ssm Spm)
    (hg65 : InitGoalHolds pm.numRanks goal_65 Ssm Spm)
    (hg66 : InitGoalHolds pm.numRanks goal_66 Ssm Spm)
    (hg67 : InitGoalHolds pm.numRanks goal_67 Ssm Spm)
    (hg68 : InitGoalHolds pm.numRanks goal_68 Ssm Spm)
    (hg69 : InitGoalHolds pm.numRanks goal_69 Ssm Spm)
    (hg70 : InitGoalHolds pm.numRanks goal_70 Ssm Spm)
    (hg71 : InitGoalHolds pm.numRanks goal_71 Ssm Spm)
    (hg72 : InitGoalHolds pm.numRanks goal_72 Ssm Spm)
    (hg73 : InitGoalHolds pm.numRanks goal_73 Ssm Spm)
    (hg74 : InitGoalHolds pm.numRanks goal_74 Ssm Spm)
    (hg75 : InitGoalHolds pm.numRanks goal_75 Ssm Spm)
    (hg76 : InitGoalHolds pm.numRanks goal_76 Ssm Spm)
    (hg77 : InitGoalHolds pm.numRanks goal_77 Ssm Spm)
    (hg78 : InitGoalHolds pm.numRanks goal_78 Ssm Spm)
    (hg79 : InitGoalHolds pm.numRanks goal_79 Ssm Spm)
    (hg80 : InitGoalHolds pm.numRanks goal_80 Ssm Spm)
    (hg81 : InitGoalHolds pm.numRanks goal_81 Ssm Spm)
    (hg82 : InitGoalHolds pm.numRanks goal_82 Ssm Spm)
    (hg83 : InitGoalHolds pm.numRanks goal_83 Ssm Spm)
    (hg84 : InitGoalHolds pm.numRanks goal_84 Ssm Spm)
    (hg85 : InitGoalHolds pm.numRanks goal_85 Ssm Spm)
    (hg86 : InitGoalHolds pm.numRanks goal_86 Ssm Spm)
    (hg87 : InitGoalHolds pm.numRanks goal_87 Ssm Spm)
    (hg88 : InitGoalHolds pm.numRanks goal_88 Ssm Spm)
    (hg89 : InitGoalHolds pm.numRanks goal_89 Ssm Spm)
    (hg90 : InitGoalHolds pm.numRanks goal_90 Ssm Spm)
    (hg91 : InitGoalHolds pm.numRanks goal_91 Ssm Spm)
    (hg92 : InitGoalHolds pm.numRanks goal_92 Ssm Spm)
    (hg93 : InitGoalHolds pm.numRanks goal_93 Ssm Spm)
    (hg94 : InitGoalHolds pm.numRanks goal_94 Ssm Spm)
    (hg95 : InitGoalHolds pm.numRanks goal_95 Ssm Spm)
    (hg96 : InitGoalHolds pm.numRanks goal_96 Ssm Spm)
    (hg97 : InitGoalHolds pm.numRanks goal_97 Ssm Spm)
    (hg98 : InitGoalHolds pm.numRanks goal_98 Ssm Spm)
    (hg99 : InitGoalHolds pm.numRanks goal_99 Ssm Spm)
    (hg257 : InitGoalHolds pm.numRanks goal_257 Ssm Spm)
    (hg259 : InitGoalHolds pm.numRanks goal_259 Ssm Spm)
    (hg261 : InitGoalHolds pm.numRanks goal_261 Ssm Spm)
    (hg263 : InitGoalHolds pm.numRanks goal_263 Ssm Spm)
    (hg265 : InitGoalHolds pm.numRanks goal_265 Ssm Spm)
    (hg267 : InitGoalHolds pm.numRanks goal_267 Ssm Spm)
    (hg269 : InitGoalHolds pm.numRanks goal_269 Ssm Spm)
    (hg271 : InitGoalHolds pm.numRanks goal_271 Ssm Spm)
    (hg273 : InitGoalHolds pm.numRanks goal_273 Ssm Spm)
    (hg275 : InitGoalHolds pm.numRanks goal_275 Ssm Spm)
    (hg277 : InitGoalHolds pm.numRanks goal_277 Ssm Spm)
    (hg279 : InitGoalHolds pm.numRanks goal_279 Ssm Spm)
    (hg281 : InitGoalHolds pm.numRanks goal_281 Ssm Spm)
    (hg283 : InitGoalHolds pm.numRanks goal_283 Ssm Spm)
    (hg285 : InitGoalHolds pm.numRanks goal_285 Ssm Spm)
    (hg287 : InitGoalHolds pm.numRanks goal_287 Ssm Spm)
    (hg289 : InitGoalHolds pm.numRanks goal_289 Ssm Spm)
    (hg291 : InitGoalHolds pm.numRanks goal_291 Ssm Spm)
    (hg293 : InitGoalHolds pm.numRanks goal_293 Ssm Spm)
    (hg295 : InitGoalHolds pm.numRanks goal_295 Ssm Spm)
    (hg297 : InitGoalHolds pm.numRanks goal_297 Ssm Spm)
    (hg299 : InitGoalHolds pm.numRanks goal_299 Ssm Spm)
    (hg301 : InitGoalHolds pm.numRanks goal_301 Ssm Spm)
    (hg303 : InitGoalHolds pm.numRanks goal_303 Ssm Spm)
    (hg305 : InitGoalHolds pm.numRanks goal_305 Ssm Spm)
    (hg307 : InitGoalHolds pm.numRanks goal_307 Ssm Spm)
    (hg309 : InitGoalHolds pm.numRanks goal_309 Ssm Spm) :
    InitGoalsHold pm_goal_100.numRanks goal_100_cut_initGoals Ssm Spm := by
  have hnr : pm_goal_100.numRanks = pm.numRanks := by native_decide
  rw [hnr]
  simp only [InitGoalsHold] at hinitC ⊢
  simp only [goal_100_cut_initGoals, goal_100_prereqs, List.forall_mem_append,
    List.forall_mem_cons, List.forall_mem_nil, and_true]
  exact ⟨hinitC, hg2, hg3, hg4, hg5, hg6, hg7, hg8, hg9, hg10, hg11, hg12, hg13, hg14, hg15, hg16, hg17, hg18, hg19, hg20, hg21, hg22, hg23, hg24, hg25, hg26, hg27, hg28, hg29, hg30, hg31, hg32, hg33, hg34, hg35, hg36, hg37, hg38, hg39, hg40, hg41, hg42, hg43, hg44, hg45, hg46, hg47, hg48, hg49, hg50, hg51, hg52, hg53, hg54, hg55, hg56, hg57, hg58, hg59, hg60, hg61, hg62, hg63, hg64, hg65, hg66, hg67, hg68, hg69, hg70, hg71, hg72, hg73, hg74, hg75, hg76, hg77, hg78, hg79, hg80, hg81, hg82, hg83, hg84, hg85, hg86, hg87, hg88, hg89, hg90, hg91, hg92, hg93, hg94, hg95, hg96, hg97, hg98, hg99, hg257, hg259, hg261, hg263, hg265, hg267, hg269, hg271, hg273, hg275, hg277, hg279, hg281, hg283, hg285, hg287, hg289, hg291, hg293, hg295, hg297, hg299, hg301, hg303, hg305, hg307, hg309, List.forall_mem_nil _⟩

-- ========== Assembly: goal_100_cut_to_full ==========
theorem goal_100_cut_to_full (h : goal_100_stmt_cut) : goal_100_stmt := by
  intro initSM initPM hSM hPM hInit
  set Ssm := denoteGraph sm initSM with hSsm
  set Spm := denoteGraph pm initPM with hSpm
  have hg2 := goal_2_intermediate initSM initPM hSM hPM hInit
  have hg3 := goal_3_intermediate initSM initPM hSM hPM hInit
  have hg4 := goal_4_intermediate initSM initPM hSM hPM hInit
  have hg5 := goal_5_intermediate initSM initPM hSM hPM hInit
  have hg6 := goal_6_intermediate initSM initPM hSM hPM hInit
  have hg7 := goal_7_intermediate initSM initPM hSM hPM hInit
  have hg8 := goal_8_intermediate initSM initPM hSM hPM hInit
  have hg9 := goal_9_intermediate initSM initPM hSM hPM hInit
  have hg10 := goal_10_intermediate initSM initPM hSM hPM hInit
  have hg11 := goal_11_intermediate initSM initPM hSM hPM hInit
  have hg12 := goal_12_intermediate initSM initPM hSM hPM hInit
  have hg13 := goal_13_intermediate initSM initPM hSM hPM hInit
  have hg14 := goal_14_intermediate initSM initPM hSM hPM hInit
  have hg15 := goal_15_intermediate initSM initPM hSM hPM hInit
  have hg16 := goal_16_intermediate initSM initPM hSM hPM hInit
  have hg17 := goal_17_intermediate initSM initPM hSM hPM hInit
  have hg18 := goal_18_intermediate initSM initPM hSM hPM hInit
  have hg19 := goal_19_intermediate initSM initPM hSM hPM hInit
  have hg20 := goal_20_intermediate initSM initPM hSM hPM hInit
  have hg21 := goal_21_intermediate initSM initPM hSM hPM hInit
  have hg22 := goal_22_intermediate initSM initPM hSM hPM hInit
  have hg23 := goal_23_intermediate initSM initPM hSM hPM hInit
  have hg24 := goal_24_intermediate initSM initPM hSM hPM hInit
  have hg25 := goal_25_intermediate initSM initPM hSM hPM hInit
  have hg26 := goal_26_intermediate initSM initPM hSM hPM hInit
  have hg27 := goal_27_intermediate initSM initPM hSM hPM hInit
  have hg28 := goal_28_intermediate initSM initPM hSM hPM hInit
  have hg29 := goal_29_intermediate initSM initPM hSM hPM hInit
  have hg30 := goal_30_intermediate initSM initPM hSM hPM hInit
  have hg31 := goal_31_intermediate initSM initPM hSM hPM hInit
  have hg32 := goal_32_intermediate initSM initPM hSM hPM hInit
  have hg33 := goal_33_intermediate initSM initPM hSM hPM hInit
  have hg34 := goal_34_intermediate initSM initPM hSM hPM hInit
  have hg35 := goal_35_intermediate initSM initPM hSM hPM hInit
  have hg36 := goal_36_intermediate initSM initPM hSM hPM hInit
  have hg37 := goal_37_intermediate initSM initPM hSM hPM hInit
  have hg38 := goal_38_intermediate initSM initPM hSM hPM hInit
  have hg39 := goal_39_intermediate initSM initPM hSM hPM hInit
  have hg40 := goal_40_intermediate initSM initPM hSM hPM hInit
  have hg41 := goal_41_intermediate initSM initPM hSM hPM hInit
  have hg42 := goal_42_intermediate initSM initPM hSM hPM hInit
  have hg43 := goal_43_intermediate initSM initPM hSM hPM hInit
  have hg44 := goal_44_intermediate initSM initPM hSM hPM hInit
  have hg45 := goal_45_intermediate initSM initPM hSM hPM hInit
  have hg46 := goal_46_intermediate initSM initPM hSM hPM hInit
  have hg47 := goal_47_intermediate initSM initPM hSM hPM hInit
  have hg48 := goal_48_intermediate initSM initPM hSM hPM hInit
  have hg49 := goal_49_intermediate initSM initPM hSM hPM hInit
  have hg50 := goal_50_intermediate initSM initPM hSM hPM hInit
  have hg51 := goal_51_intermediate initSM initPM hSM hPM hInit
  have hg52 := goal_52_intermediate initSM initPM hSM hPM hInit
  have hg53 := goal_53_intermediate initSM initPM hSM hPM hInit
  have hg54 := goal_54_intermediate initSM initPM hSM hPM hInit
  have hg55 := goal_55_intermediate initSM initPM hSM hPM hInit
  have hg56 := goal_56_intermediate initSM initPM hSM hPM hInit
  have hg57 := goal_57_intermediate initSM initPM hSM hPM hInit
  have hg58 := goal_58_intermediate initSM initPM hSM hPM hInit
  have hg59 := goal_59_intermediate initSM initPM hSM hPM hInit
  have hg60 := goal_60_intermediate initSM initPM hSM hPM hInit
  have hg61 := goal_61_intermediate initSM initPM hSM hPM hInit
  have hg62 := goal_62_intermediate initSM initPM hSM hPM hInit
  have hg63 := goal_63_intermediate initSM initPM hSM hPM hInit
  have hg64 := goal_64_intermediate initSM initPM hSM hPM hInit
  have hg65 := goal_65_intermediate initSM initPM hSM hPM hInit
  have hg66 := goal_66_intermediate initSM initPM hSM hPM hInit
  have hg67 := goal_67_intermediate initSM initPM hSM hPM hInit
  have hg68 := goal_68_intermediate initSM initPM hSM hPM hInit
  have hg69 := goal_69_intermediate initSM initPM hSM hPM hInit
  have hg70 := goal_70_intermediate initSM initPM hSM hPM hInit
  have hg71 := goal_71_intermediate initSM initPM hSM hPM hInit
  have hg72 := goal_72_intermediate initSM initPM hSM hPM hInit
  have hg73 := goal_73_intermediate initSM initPM hSM hPM hInit
  have hg74 := goal_74_intermediate initSM initPM hSM hPM hInit
  have hg75 := goal_75_intermediate initSM initPM hSM hPM hInit
  have hg76 := goal_76_intermediate initSM initPM hSM hPM hInit
  have hg77 := goal_77_intermediate initSM initPM hSM hPM hInit
  have hg78 := goal_78_intermediate initSM initPM hSM hPM hInit
  have hg79 := goal_79_intermediate initSM initPM hSM hPM hInit
  have hg80 := goal_80_intermediate initSM initPM hSM hPM hInit
  have hg81 := goal_81_intermediate initSM initPM hSM hPM hInit
  have hg82 := goal_82_intermediate initSM initPM hSM hPM hInit
  have hg83 := goal_83_intermediate initSM initPM hSM hPM hInit
  have hg84 := goal_84_intermediate initSM initPM hSM hPM hInit
  have hg85 := goal_85_intermediate initSM initPM hSM hPM hInit
  have hg86 := goal_86_intermediate initSM initPM hSM hPM hInit
  have hg87 := goal_87_intermediate initSM initPM hSM hPM hInit
  have hg88 := goal_88_intermediate initSM initPM hSM hPM hInit
  have hg89 := goal_89_intermediate initSM initPM hSM hPM hInit
  have hg90 := goal_90_intermediate initSM initPM hSM hPM hInit
  have hg91 := goal_91_intermediate initSM initPM hSM hPM hInit
  have hg92 := goal_92_intermediate initSM initPM hSM hPM hInit
  have hg93 := goal_93_intermediate initSM initPM hSM hPM hInit
  have hg94 := goal_94_intermediate initSM initPM hSM hPM hInit
  have hg95 := goal_95_intermediate initSM initPM hSM hPM hInit
  have hg96 := goal_96_intermediate initSM initPM hSM hPM hInit
  have hg97 := goal_97_intermediate initSM initPM hSM hPM hInit
  have hg98 := goal_98_intermediate initSM initPM hSM hPM hInit
  have hg99 := goal_99_intermediate initSM initPM hSM hPM hInit
  have hg257 := goal_257_intermediate initSM initPM hSM hPM hInit
  have hg259 := goal_259_intermediate initSM initPM hSM hPM hInit
  have hg261 := goal_261_intermediate initSM initPM hSM hPM hInit
  have hg263 := goal_263_intermediate initSM initPM hSM hPM hInit
  have hg265 := goal_265_intermediate initSM initPM hSM hPM hInit
  have hg267 := goal_267_intermediate initSM initPM hSM hPM hInit
  have hg269 := goal_269_intermediate initSM initPM hSM hPM hInit
  have hg271 := goal_271_intermediate initSM initPM hSM hPM hInit
  have hg273 := goal_273_intermediate initSM initPM hSM hPM hInit
  have hg275 := goal_275_intermediate initSM initPM hSM hPM hInit
  have hg277 := goal_277_intermediate initSM initPM hSM hPM hInit
  have hg279 := goal_279_intermediate initSM initPM hSM hPM hInit
  have hg281 := goal_281_intermediate initSM initPM hSM hPM hInit
  have hg283 := goal_283_intermediate initSM initPM hSM hPM hInit
  have hg285 := goal_285_intermediate initSM initPM hSM hPM hInit
  have hg287 := goal_287_intermediate initSM initPM hSM hPM hInit
  have hg289 := goal_289_intermediate initSM initPM hSM hPM hInit
  have hg291 := goal_291_intermediate initSM initPM hSM hPM hInit
  have hg293 := goal_293_intermediate initSM initPM hSM hPM hInit
  have hg295 := goal_295_intermediate initSM initPM hSM hPM hInit
  have hg297 := goal_297_intermediate initSM initPM hSM hPM hInit
  have hg299 := goal_299_intermediate initSM initPM hSM hPM hInit
  have hg301 := goal_301_intermediate initSM initPM hSM hPM hInit
  have hg303 := goal_303_intermediate initSM initPM hSM hPM hInit
  have hg305 := goal_305_intermediate initSM initPM hSM hPM hInit
  have hg307 := goal_307_intermediate initSM initPM hSM hPM hInit
  have hg309 := goal_309_intermediate initSM initPM hSM hPM hInit
  have hinitC := initGoals_preserved initSM initPM hInit
  have hnr : pm_goal_100.numRanks = pm.numRanks := by native_decide
  have hg699 := hinitC initGoal_699 (by simp only [initGoals]; decide)
  have hg700 := hinitC initGoal_700 (by simp only [initGoals]; decide)
  have h699_smsh : (Ssm 699).shape = [32] := by
    have h := hg699.1; simp only [initGoal_699] at h; exact h
  have h700_smsh : (Ssm 700).shape = [32] := by
    have h := hg700.1; simp only [initGoal_700] at h; exact h
  have h699_pmsh : (Spm 699).shape = [32] := by
    have h := hg699.2.1; simp only [initGoal_699, List.map] at h
    have := congrArg List.head? h; simpa using this
  have h700_pmsh : (Spm 700).shape = [32] := by
    have h := hg700.2.1; simp only [initGoal_700, List.map] at h
    have := congrArg List.head? h; simpa using this
  have h1063_smsh : (Ssm 1063).shape = [1, 8, 32] := by
    have h := hg309.1; simp only [goal_309] at h; exact h
  have h309tp := hg309.2.1
  simp only [goal_309, List.map, List.cons.injEq, and_true] at h309tp
  obtain ⟨h3201_pmsh, h3202_pmsh, h3203_pmsh, h3204_pmsh⟩ := h309tp
  have hSM100 : StoreShapesHold Ssm sm_goal_100InitEnv := by
    intro tid sh hsh
    rw [sm_goal_100InitEnv] at hsh
    have hmem := mem_of_shapeEnvOfList_eq_some hsh
    simp only [sm_goal_100InitShapes, List.mem_cons, List.not_mem_nil, or_false,
               Prod.mk.injEq] at hmem
    rcases hmem with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact h699_smsh
    · exact h700_smsh
    · exact h1063_smsh
  have hPM100 : StoreShapesHold Spm pm_goal_100InitEnv := by
    intro tid sh hsh
    rw [pm_goal_100InitEnv] at hsh
    have hmem := mem_of_shapeEnvOfList_eq_some hsh
    simp only [pm_goal_100InitShapes, List.mem_cons, List.not_mem_nil, or_false,
               Prod.mk.injEq] at hmem
    rcases hmem with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · exact h699_pmsh
    · exact h700_pmsh
    · exact h3201_pmsh
    · exact h3202_pmsh
    · exact h3203_pmsh
    · exact h3204_pmsh

  have hInitCut : InitGoalsHold pm_goal_100.numRanks goal_100_cut_initGoals Ssm Spm :=
    goal_100_hInitCut_helper Ssm Spm hinitC hg2 hg3 hg4 hg5 hg6 hg7 hg8 hg9 hg10 hg11 hg12 hg13 hg14 hg15 hg16 hg17 hg18 hg19 hg20 hg21 hg22 hg23 hg24 hg25 hg26 hg27 hg28 hg29 hg30 hg31 hg32 hg33 hg34 hg35 hg36 hg37 hg38 hg39 hg40 hg41 hg42 hg43 hg44 hg45 hg46 hg47 hg48 hg49 hg50 hg51 hg52 hg53 hg54 hg55 hg56 hg57 hg58 hg59 hg60 hg61 hg62 hg63 hg64 hg65 hg66 hg67 hg68 hg69 hg70 hg71 hg72 hg73 hg74 hg75 hg76 hg77 hg78 hg79 hg80 hg81 hg82 hg83 hg84 hg85 hg86 hg87 hg88 hg89 hg90 hg91 hg92 hg93 hg94 hg95 hg96 hg97 hg98 hg99 hg257 hg259 hg261 hg263 hg265 hg267 hg269 hg271 hg273 hg275 hg277 hg279 hg281 hg283 hg285 hg287 hg289 hg291 hg293 hg295 hg297 hg299 hg301 hg303 hg305 hg307 hg309
  have hcut := h Ssm Spm hSM100 hPM100 hInitCut
  have hsmf : Ssm 701 = denoteGraph sm_goal_100 Ssm 701 := by
    rw [hSsm]; exact sm_frame_701_self initSM
  have hpm3205 : Spm 3205 = denoteGraph pm_goal_100 Spm 3205 := by
    rw [denote_pm_goal_100_3205]; rw [hSpm]; exact pm_frame_3205_self initPM
  have hpm3206 : Spm 3206 = denoteGraph pm_goal_100 Spm 3206 := by
    rw [denote_pm_goal_100_3206]; rw [hSpm]; exact pm_frame_3206_self initPM
  have hpm3207 : Spm 3207 = denoteGraph pm_goal_100 Spm 3207 := by
    rw [denote_pm_goal_100_3207]; rw [hSpm]; exact pm_frame_3207_self initPM
  have hpm3208 : Spm 3208 = denoteGraph pm_goal_100 Spm 3208 := by
    rw [denote_pm_goal_100_3208]; rw [hSpm]; exact pm_frame_3208_self initPM
  rw [hnr] at hcut
  simp only [goal_100, List.map] at hcut ⊢
  rw [hsmf, hpm3205, hpm3206, hpm3207, hpm3208]
  exact hcut

theorem goal_100_intermediate (initSM initPM : Store)
    (hSM : StoreShapesHold initSM smInitEnv) (hPM : StoreShapesHold initPM pmInitEnv)
    (hInit : InitGoalsHold pm.numRanks initGoals initSM initPM) :
    InitGoalHolds pm.numRanks goal_100 (denoteGraph sm initSM) (denoteGraph pm initPM) := by
  have hfull : goal_100_stmt := goal_100_cut_to_full prove_goal_100_cut
  have := hfull initSM initPM hSM hPM hInit
  simpa [InitGoalHolds, goal_100] using this

end TrainVerify.Denote.GeneratedGoals
