#!/usr/bin/env python3
SM_NODE=60; SM_OUT=640; SM_DATA=989; W=638; B=639
PM_NODES=[392,393,394,395]; PM_OUTS=[2229,2230,2231,2232]; PM_DATA=[2225,2226,2227,2228]
PREREQS=list(range(2,55))+[257,259,261,263,265,267,269,271,273,275,277,279,281,283,285]
GIN=285  # goal_285 provides 989 + tps 2225-2228
out=[]
def w(s=""): out.append(s)

w("/- goal_55 bridge (prereqs=[2..54,257-285 odd]=68). per-rank FW_layernorm (data+replicated")
w("   weight/bias), multi-tps gatherDim=1, no follow-on collective.")
w("   SM=FW_layernorm(989,638,639)->640 node 60 [1,8,32].")
w("   PM=4xFW_layernorm(2225+r,638,639)->2229-2232 node 392-395, each rank data [1,2,32], w/b replicated [32].")
w("   989=goal_285 output [1,8,32] dim1-sharded tps 2225-2228 [1,2,32]; 638/639=initGoal_638/639 replicated [32].")
w("   multi-tps output gatherDim=1; PM mini-graph no collective (input pre-sharded).")
w("   Core semantics (per-rank layernorm + concat = full layernorm) in prove_goal_55_cut. Bridge = frame.")
w("   Template = Goal30Bridge verbatim (same per-rank layernorm no-collective), remap tid/node/shape;")
w("   data upstream goal_271 -> goal_285, weight 603/604 -> 638/639. -/")
w("import denote.gpt_ly4_regen.Goal30Bridge")
w("import denote.gpt_ly4_regen.Goal285Bridge")
w("import denote.gpt_ly4_regen.Goal_55")
w()
for o in ["maxRecDepth 100000","maxHeartbeats 0","linter.style.nativeDecide false",
"linter.unusedSimpArgs false","linter.style.commandStart false","linter.unusedTactic false",
"linter.unreachableTactic false","linter.unusedVariables false","linter.style.show false",
"linter.style.setOption false","linter.unnecessarySeqFocus false","linter.flexible false"]:
    w("set_option "+o)
w()
w("namespace TrainVerify.Denote.GeneratedGoals")
w("open TrainVerify.Denote TrainVerify.Denote.Generated")
w()
# SM mini
w(f"theorem denote_sm_goal_55_{SM_OUT} (s : Store) :")
w(f"    denoteGraph sm_goal_55 s {SM_OUT} = fw_layernorm (s {SM_DATA}) (s {W}) (s {B}) := by")
w("  simp only [sm_goal_55, denoteGraph, List.foldl]")
w("  rw [applyNode_fw_layernorm_out]")
w()
# pm mini (node 0 simple, 1-3 with congr)
for r in range(4):
    o=PM_OUTS[r]; d=PM_DATA[r]
    w(f"theorem denote_pm_goal_55_{o} (s : Store) :")
    w(f"    denoteGraph pm_goal_55 s {o} = fw_layernorm (s {d}) (s {W}) (s {B}) := by")
    w("  simp only [pm_goal_55, denoteGraph, List.foldl]")
    w("  repeat rw [applyNode_eq_of_not_mem_outs (h := by decide)]")
    w("  rw [applyNode_fw_layernorm_out]")
    if r>0:
        w("  congr 1 <;> repeat rw [applyNode_eq_of_not_mem_outs (h := by decide)]")
    w()
# SM frame
w(f"theorem sm_frame_{SM_OUT}_self (initSM : Store) :")
w(f"    denoteGraph sm initSM {SM_OUT} = denoteGraph sm_goal_55 (denoteGraph sm initSM) {SM_OUT} := by")
w(f"  rw [denote_sm_goal_55_{SM_OUT}]")
w(f"  rw [sm_val initSM {SM_NODE} {SM_OUT} (by native_decide) (by native_decide)]")
w(f"  rw [show sm.nodes[{SM_NODE}]'(by native_decide)")
w(f'      = {{ rank := 0, op := "OpName.FW_layernorm", ins := [{SM_DATA}, {W}, {B}], outs := [{SM_OUT}] }}')
w("      from by native_decide]")
w("  rw [applyNode_fw_layernorm_out]")
w(f"  rw [sm_prefix_eq initSM {SM_NODE} {SM_DATA} (by native_decide),")
w(f"      sm_prefix_eq initSM {SM_NODE} {W} (by native_decide),")
w(f"      sm_prefix_eq initSM {SM_NODE} {B} (by native_decide)]")
w()
# PM frame
for r in range(4):
    node=PM_NODES[r]; o=PM_OUTS[r]; d=PM_DATA[r]
    w(f"theorem pm_frame_{o}_self (initPM : Store) :")
    w(f"    denoteGraph pm initPM {o}")
    w(f"      = fw_layernorm (denoteGraph pm initPM {d})")
    w(f"          (denoteGraph pm initPM {W}) (denoteGraph pm initPM {B}) := by")
    w(f"  rw [pm_val initPM {node} {o} (by native_decide) (by native_decide)]")
    w(f"  rw [show pm.nodes[{node}]'(by native_decide)")
    w(f'      = {{ rank := {r}, op := "OpName.FW_layernorm", ins := [{d}, {W}, {B}], outs := [{o}] }}')
    w("      from by native_decide]")
    w("  rw [applyNode_fw_layernorm_out]")
    w(f"  rw [pm_prefix_eq initPM {node} {d} (by native_decide),")
    w(f"      pm_prefix_eq initPM {node} {W} (by native_decide),")
    w(f"      pm_prefix_eq initPM {node} {B} (by native_decide)]")
    w()
# helper hInitCut
w("lemma goal_55_hInitCut_helper (Ssm Spm : Store)")
w("    (hinitC : InitGoalsHold pm.numRanks initGoals Ssm Spm)")
for g in PREREQS:
    w(f"    (hg{g} : InitGoalHolds pm.numRanks goal_{g} Ssm Spm)")
w("    : InitGoalsHold pm_goal_55.numRanks goal_55_cut_initGoals Ssm Spm := by")
w("  have hnr : pm_goal_55.numRanks = pm.numRanks := by native_decide")
w("  rw [hnr]; intro g hg")
w("  simp only [goal_55_cut_initGoals, goal_55_prereqs, List.mem_append] at hg")
w("  rcases hg with hg | hg")
w("  \u00b7 exact hinitC g hg")
w("  \u00b7 simp only [List.mem_cons, List.not_mem_nil, or_false] at hg")
w("    rcases hg with "+" | ".join(["rfl"]*len(PREREQS)))
for g in PREREQS:
    w(f"    \u00b7 exact hg{g}")
w()
# main
w("theorem goal_55_cut_to_full (h : goal_55_stmt_cut) : goal_55_stmt := by")
w("  intro initSM initPM hSM hPM hInit")
w("  set Ssm := denoteGraph sm initSM with hSsm")
w("  set Spm := denoteGraph pm initPM with hSpm")
for g in PREREQS:
    w(f"  have hg{g} := goal_{g}_intermediate initSM initPM hSM hPM hInit")
w("  have hinitC := initGoals_preserved initSM initPM hInit")
w("  have hnr : pm_goal_55.numRanks = pm.numRanks := by native_decide")
w("  have hInitCut : InitGoalsHold pm_goal_55.numRanks goal_55_cut_initGoals Ssm Spm :=")
w("    goal_55_hInitCut_helper Ssm Spm hinitC "+" ".join([f"hg{g}" for g in PREREQS]))
# data shapes from goal_285
w(f"  have h989_smsh : (Ssm {SM_DATA}).shape = [1, 8, 32] := by")
w(f"    have h := hg{GIN}.1; simp only [goal_{GIN}] at h; exact h")
w(f"  have h285tp := hg{GIN}.2.1")
w(f"  simp only [goal_{GIN}, List.map, List.cons.injEq, and_true] at h285tp")
w("  obtain \u27e8h2225sh, h2226sh, h2227sh, h2228sh\u27e9 := h285tp")
# weight/bias from initGoals
w(f"  have hg638 := hinitC initGoal_{W} (by simp only [initGoals]; decide)")
w(f"  have hg639 := hinitC initGoal_{B} (by simp only [initGoals]; decide)")
w(f"  have h638_smsh : (Ssm {W}).shape = [32] := by")
w(f"    have h := hg638.1; simp only [initGoal_{W}] at h; exact h")
w(f"  have h639_smsh : (Ssm {B}).shape = [32] := by")
w(f"    have h := hg639.1; simp only [initGoal_{B}] at h; exact h")
w(f"  have h638_pmsh : (Spm {W}).shape = [32] := by")
w(f"    have h := hg638.2.1; simp only [initGoal_{W}, List.map] at h")
w("    have := congrArg List.head? h; simpa using this")
w(f"  have h639_pmsh : (Spm {B}).shape = [32] := by")
w(f"    have h := hg639.2.1; simp only [initGoal_{B}, List.map] at h")
w("    have := congrArg List.head? h; simpa using this")
# StoreShapesHold sm: order [(638),(639),(989)]
w("  have hSM55 : StoreShapesHold Ssm sm_goal_55InitEnv := by")
w("    intro tid sh hsh")
w("    rw [sm_goal_55InitEnv] at hsh")
w("    have hmem := mem_of_shapeEnvOfList_eq_some hsh")
w("    simp only [sm_goal_55InitShapes, List.mem_cons, List.not_mem_nil, or_false,")
w("               Prod.mk.injEq] at hmem")
w("    rcases hmem with \u27e8rfl, rfl\u27e9 | \u27e8rfl, rfl\u27e9 | \u27e8rfl, rfl\u27e9")
w("    \u00b7 exact h638_smsh")
w("    \u00b7 exact h639_smsh")
w("    \u00b7 exact h989_smsh")
# StoreShapesHold pm: order [(638),(639),(2225-2228)]
w("  have hPM55 : StoreShapesHold Spm pm_goal_55InitEnv := by")
w("    intro tid sh hsh")
w("    rw [pm_goal_55InitEnv] at hsh")
w("    have hmem := mem_of_shapeEnvOfList_eq_some hsh")
w("    simp only [pm_goal_55InitShapes, List.mem_cons, List.not_mem_nil, or_false,")
w("               Prod.mk.injEq] at hmem")
w("    rcases hmem with \u27e8rfl, rfl\u27e9 | \u27e8rfl, rfl\u27e9 | \u27e8rfl, rfl\u27e9 | \u27e8rfl, rfl\u27e9 | \u27e8rfl, rfl\u27e9 | \u27e8rfl, rfl\u27e9")
w("    \u00b7 exact h638_pmsh")
w("    \u00b7 exact h639_pmsh")
w("    \u00b7 exact h2225sh")
w("    \u00b7 exact h2226sh")
w("    \u00b7 exact h2227sh")
w("    \u00b7 exact h2228sh")
w("  have hcut := h Ssm Spm hSM55 hPM55 hInitCut")
w(f"  have hsmf : Ssm {SM_OUT} = denoteGraph sm_goal_55 Ssm {SM_OUT} := by")
w(f"    rw [hSsm]; exact sm_frame_{SM_OUT}_self initSM")
for r in range(4):
    o=PM_OUTS[r]
    w(f"  have hpm{o} : Spm {o} = denoteGraph pm_goal_55 Spm {o} := by")
    w(f"    rw [denote_pm_goal_55_{o}]; rw [hSpm]; exact pm_frame_{o}_self initPM")
w("  rw [hnr] at hcut")
w("  simp only [goal_55, List.map] at hcut \u22a2")
w("  rw [hsmf, "+", ".join([f"hpm{o}" for o in PM_OUTS])+"]")
w("  exact hcut")
w()
w("theorem goal_55_intermediate (initSM initPM : Store)")
w("    (hSM : StoreShapesHold initSM smInitEnv) (hPM : StoreShapesHold initPM pmInitEnv)")
w("    (hInit : InitGoalsHold pm.numRanks initGoals initSM initPM) :")
w("    InitGoalHolds pm.numRanks goal_55 (denoteGraph sm initSM) (denoteGraph pm initPM) := by")
w("  have hfull : goal_55_stmt := goal_55_cut_to_full prove_goal_55_cut")
w("  have := hfull initSM initPM hSM hPM hInit")
w("  simpa [InitGoalHolds, goal_55] using this")
w()
w("end TrainVerify.Denote.GeneratedGoals")

with open("trainverify/denote/gpt_ly4_regen/Goal55Bridge.lean","w") as f:
    f.write("\n".join(out)+"\n")
print("Generated Goal55Bridge.lean:", len(out), "lines, prereqs:", len(PREREQS))
