"""Atomic cross-axis renderer for joined BW_view plus sharded BW_div."""
from __future__ import annotations


def render_closed_bw_view_bw_div_segment(ir, relation, segment_id: str) -> str:
    try:
      from .composer import _node_text,_render_mixed_final_value,_select_exact_typed_certificate,_shape_text
      from .relation_compiler import JoinedBWViewCertificate,KRankDivCertificate
    except ImportError:
      from composer import _node_text,_render_mixed_final_value,_select_exact_typed_certificate,_shape_text
      from relation_compiler import JoinedBWViewCertificate,KRankDivCertificate
    vrule="bw-view-joined";drule="div-sharded-k-rank-dim2";vth="TrainVerify.Denote.RelationCompiler.JoinedRel.fw_view";dth="TrainVerify.Denote.bw_div_allGatherPrimDimN_eq_g128"
    chain=relation.dependent_chain_plan;seg=next((z for z in chain.segments if z.segment_id==segment_id),None)
    if seg is None or len(seg.transition_ids)!=2: raise ValueError("BW_view/BW_div requires two transitions")
    by={t.transition_id:t for t in relation.transition_specs};ts=tuple(by[x] for x in seg.transition_ids);v=next((z for z in ts if z.rule_id==vrule),None);d=next((z for z in ts if z.rule_id==drule),None)
    if v is None or d is None or v.lean_theorem!=vth or d.lean_theorem!=dth: raise ValueError("BW_view/BW_div typed identity mismatch")
    vc=_select_exact_typed_certificate(relation,v,vrule,vth,JoinedBWViewCertificate,lambda c:((c.input_fact,),(c.output_fact,)))
    dc=_select_exact_typed_certificate(relation,d,drule,dth,KRankDivCertificate,lambda c:((c.input_fact,),(c.output_fact,)))
    rec={r.source:r for r in chain.relation_facts}
    try:vi,vo,di,do=rec[vc.input_fact],rec[vc.output_fact],rec[dc.input_fact],rec[dc.output_fact]
    except KeyError as exc: raise ValueError("BW_view/BW_div fact missing") from exc
    states={z.state_id:z for z in chain.states};before,after=states[seg.pre_state_id],states[seg.post_state_id]
    if not {vi.fact_id,di.fact_id}<=set(before.fact_ids) or not {vo.fact_id,do.fact_id}<=set(after.fact_ids): raise ValueError("BW_view/BW_div facts not live")
    if not set(after.fact_ids)<=({vo.fact_id,do.fact_id}|set(before.fact_ids)): raise ValueError("BW_view/BW_div post state introduces unproved fact")
    if vi.kind!="joined" or vo.kind!="joined" or vi.joined_pm_tid is None or vo.joined_pm_tid is None or vi.full_shape!=(1,8,4,8) or vo.full_shape!=(1,8,32): raise ValueError("BW_view joined metadata mismatch")
    if any(r.kind!="sharded" or r.gather_dim!=2 or r.full_shape!=(1,4,8,8) or r.shard_shape!=(1,4,2,8) for r in (di,do)) or dc.rank_count!=4 or dc.scalar_param!=2: raise ValueError("BW_div sharded metadata mismatch")
    ss,se=seg.sm_range;ps,pe=seg.pm_range
    if len(v.sm_node_indices)!=1 or len(v.pm_node_indices)!=1 or len(d.sm_node_indices)!=1 or len(d.pm_node_indices)!=4: raise ValueError("BW_view/BW_div footprint cardinality mismatch")
    if (set(v.sm_node_indices)|set(d.sm_node_indices)!=set(range(ss,se))
        or set(d.pm_node_indices)|set(range(ps,v.pm_node_indices[0]+1))!=set(range(ps,pe))): raise ValueError("BW_view/BW_div footprints do not cover complete frames")
    vnS=ir.sm_nodes[v.sm_node_indices[0]];vnP=ir.pm_nodes[v.pm_node_indices[0]];dnS=ir.sm_nodes[d.sm_node_indices[0]];dnP=tuple(ir.pm_nodes[i] for i in d.pm_node_indices);smframe=list(ir.sm_nodes[ss:se]);pmframe=list(ir.pm_nodes[ps:pe])
    # All nodes before the selected joined writer are exact shadow overwrites.
    shadows=tuple(n for i,n in zip(range(ps,pe),pmframe) if i<v.pm_node_indices[0])
    if (vnS.op!="BW_view" or len(vnS.ins)!=2 or vnS.ins[0]!=vi.sm_tid or vnS.outs!=[vo.sm_tid] or tuple(vnS.params)!=(1,8,32)
        or vnP.op!="BW_view" or len(vnP.ins)!=2 or vnP.ins[0]!=vi.joined_pm_tid or vnP.outs!=[vo.joined_pm_tid] or tuple(vnP.params)!=(1,8,32)):
      raise ValueError("BW_view writer roles mismatch")
    if len(shadows)!=3 or any(n.op!="BW_view" or tuple(n.ins)!=tuple(vnP.ins) or n.outs!=vnP.outs or tuple(n.params)!=tuple(vnP.params) for n in shadows): raise ValueError("BW_view shadow writers mismatch")
    if (dnS.op!="BW_div" or len(dnS.ins)!=2 or dnS.ins[0]!=di.sm_tid or dnS.outs!=[do.sm_tid] or tuple(dnS.params)!=(2,)
        or tuple(n.rank for n in dnP)!=(0,1,2,3) or any(n.op!="BW_div" or len(n.ins)!=2 or n.ins[0]!=di.pm_tids[r] or n.outs!=[do.pm_tids[r]] or tuple(n.params)!=(2,) for r,n in enumerate(dnP))): raise ValueError("BW_div writers mismatch")
    if vc.sm_step_id!=f"sm:{v.sm_node_indices[0]}:0" or vc.pm_step_id!=f"pm:{v.pm_node_indices[0]}:0" or dc.sm_step_id!=f"sm:{d.sm_node_indices[0]}:0" or dc.pm_step_ids!=tuple(f"pm:{i}:0" for i in d.pm_node_indices): raise ValueError("BW_view/BW_div certificate footprint mismatch")
    smn,pmn=f"{segment_id}_sm_nodes",f"{segment_id}_pm_nodes";smf,pmf=f"{segment_id}_sm_final",f"{segment_id}_pm_final";lines=[f"private def {smn} : List NodeDecl := [{', '.join(_node_text(n) for n in smframe)}]",f"private def {pmn} : List NodeDecl := [{', '.join(_node_text(n) for n in pmframe)}]",f"private def {smf} (z : Store) : Store := {smn}.foldl (applyNodeDistributedFaithful {ir.sm_graph_ref}) z",f"private def {pmf} (z : Store) : Store := {pmn}.foldl (applyNodeDistributedFaithful {ir.pm_graph_ref}) z",""]
    def helper(name,graph,initial,fn,nn,frame,pos,node,kind):
      final=f"({fn} {initial})";out=node.outs[0]
      if kind=="view": expr=f"fw_view {_shape_text(node.params)} ({{store}} {node.ins[0]})";apply=f"exact applyNode_bw_view_out {graph} t {node.rank} {node.params[0]} {_shape_text(node.params[1:])} {node.ins[0]} {node.ins[1]} {out}"
      else: expr=f"bw_div ({node.params[0]} : Scalar) ({{store}} {node.ins[0]})";apply=f"exact applyNode_bw_div_out_g128 {graph} t {node.rank} {node.params[0]} {node.ins[0]} {node.ins[1]} {out}"
      th=f"{segment_id}_{name}";lines.extend([f"private theorem {th} ({initial}:Store) : {final} {out} = {expr.format(store=final)} := by",f"  have hfinal : {final} = {nn}.foldl (applyNodeDistributedFaithful {graph}) {initial} := by unfold {fn}; rfl"])
      h=_render_mixed_final_value(name="hout",graph=graph,initial_store=initial,final_store=final,final_equality="hfinal",nodes_name=nn,nodes=frame,position=pos,output_tid=out,input_tids=(node.ins[0],),written_tids={u for n in frame for u in n.outs},expression=expr,apply_lines=["rw [applyNodeDistributedFaithful_eq_applyNodeDistributed_of_not_collective (hshuffle := by native_decide) (hunshuffle := by native_decide) (hattn := by native_decide)]","simp [applyNodeDistributed, applyNodeRingAttn]",apply])
      lines.extend(z[2:] if z.startswith("  ") else z for z in h);lines.extend(["  exact hout",""]);return th
    hvS=helper("hViewSm",ir.sm_graph_ref,"smStore",smf,smn,smframe,v.sm_node_indices[0]-ss,vnS,"view");hvP=helper("hViewPm",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,v.pm_node_indices[0]-ps,vnP,"view");hdS=helper("hDivSm",ir.sm_graph_ref,"smStore",smf,smn,smframe,d.sm_node_indices[0]-ss,dnS,"div");hdP=[helper(f"hDivPm{r}",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,i-ps,n,"div") for r,(i,n) in enumerate(zip(d.pm_node_indices,dnP))]
    il="["+", ".join(f"pmFinal {u}" for u in di.pm_tids)+"]";ol="["+", ".join(f"pmFinal {u}" for u in do.pm_tids)+"]"
    lines.extend(["set_option maxHeartbeats 500000 in",f"private theorem {segment_id}_sound (smStore pmStore:Store) (hstate:{before.state_id}.Holds smStore pmStore) : {after.state_id}.Holds ({smf} smStore) ({pmf} pmStore) := by",f"    let smFinal := {smf} smStore",f"    let pmFinal := {pmf} pmStore",f"    have hframe : {before.state_id}.Holds smFinal pmFinal := by",f"      unfold smFinal pmFinal {smf} {pmf}",f"      apply RelationState.Holds.fold_frame {smn} {pmn} smStore pmStore hstate","      · native_decide","      · native_decide","      · native_decide","      · native_decide",f"    have hvi : {vi.fact_id}.Holds smFinal pmFinal := hframe _ (by native_decide)",f"    change smFinal {vi.sm_tid}=pmFinal {vi.joined_pm_tid} ∧ (smFinal {vi.sm_tid}).shape=[1,8,4,8] ∧ (pmFinal {vi.joined_pm_tid}).shape=[1,8,4,8] at hvi",f"    have hdi : {di.fact_id}.Holds smFinal pmFinal := hframe _ (by native_decide)",f"    change ShardedRel (smFinal {di.sm_tid}) {il} 2 [1,4,2*{il}.length,8] [1,4,2,8] at hdi",f"    have hvsm := {hvS} smStore",f"    change smFinal {vo.sm_tid}=fw_view [1,8,32] (smFinal {vi.sm_tid}) at hvsm",f"    have hvpm := {hvP} pmStore",f"    change pmFinal {vo.joined_pm_tid}=fw_view [1,8,32] (pmFinal {vi.joined_pm_tid}) at hvpm",f"    have hdsm := {hdS} smStore",f"    change smFinal {do.sm_tid}=bw_div (2:Scalar) (smFinal {di.sm_tid}) at hdsm"])
    for r in range(4): lines.extend([f"    have hdpm{r} := {hdP[r]} pmStore",f"    change pmFinal {do.pm_tids[r]}=bw_div (2:Scalar) (pmFinal {di.pm_tids[r]}) at hdpm{r}",f"    have hdiShape{r}:=(hdi.shard_shapes (pmFinal {di.pm_tids[r]}) (by simp))",f"    have hdoShape{r} : (pmFinal {do.pm_tids[r]}).shape=[1,4,2,8] := by rw [hdpm{r}, bw_div_shape_g128, hdiShape{r}]"])
    lines.extend([f"    have houtV : {vo.fact_id}.Holds smFinal pmFinal := by",f"      change smFinal {vo.sm_tid}=pmFinal {vo.joined_pm_tid} ∧ (smFinal {vo.sm_tid}).shape=[1,8,32] ∧ (pmFinal {vo.joined_pm_tid}).shape=[1,8,32]","      rw [hvsm,hvpm]","      exact JoinedRel.fw_view [1,8,32] [1,8,4,8] hvi",f"    have hdiValue : smFinal {di.sm_tid}=allGatherPrimDimN 2 4 0 {il} := by simpa only [List.length_cons,List.length_nil] using hdi.full_value",f"    have hcomm := {dc.lean_theorem} (2:Scalar) 2 4 {il} [1,4,2,8] (by omega) (by simp) (by simp [hdiShape0])",f"      (by intro i hi; exact hdi.shard_shapes _ (List.get_mem _ _))",f"    simp only [List.map] at hcomm",f"    have hdoValue : smFinal {do.sm_tid}=allGatherPrimDimN 2 4 0 {ol} := by","      rw [hdsm,hdiValue,hcomm]","      rw ["+", ".join(f"← hdpm{r}" for r in range(4))+"]",f"    have hdoValueList : smFinal {do.sm_tid}=allGatherPrimDimN 2 {ol}.length 0 {ol} := by simpa only [List.length_cons,List.length_nil] using hdoValue",f"    have hdoFullShape : (smFinal {do.sm_tid}).shape=[1,4,8,8] := by rw [hdsm,bw_div_shape_g128]; exact hdi.full_shape",f"    have houtD : {do.fact_id}.Holds smFinal pmFinal := by",f"      change ShardedRel (smFinal {do.sm_tid}) {ol} 2 [1,4,8,8] [1,4,2,8]","      refine {full_value:=hdoValueList,full_shape:=hdoFullShape,shards_nonempty:=by simp,gather_dim_lt:=by native_decide,shard_shapes:=?_,shape_contract:=by simp only [List.length_cons,List.length_nil];native_decide}","      intro piece hmem","      simp only [List.mem_cons,List.not_mem_nil,or_false] at hmem","      rcases hmem with h0|h1|h2|h3"])
    for r in range(4): lines.extend(["      · subst piece",f"        exact hdoShape{r}"])
    lines.extend(["    intro fact hfact",f"    have covered : fact ∈ [{vo.fact_id},{do.fact_id}]++{before.state_id}.facts := by exact (show {after.state_id}.facts ⊆ [{vo.fact_id},{do.fact_id}]++{before.state_id}.facts by native_decide) hfact","    simp only [List.mem_append] at covered","    rcases covered with fresh|old","    · simp only [List.mem_cons,List.not_mem_nil,or_false] at fresh","      rcases fresh with rfl|rfl","      · exact houtV","      · exact houtD","    · exact hframe fact old","","set_option maxRecDepth 8192 in",f"private def {segment_id}:ClosedDepSegmentCertificate {ir.sm_graph_ref} {ir.pm_graph_ref} {before.state_id} {after.state_id} where",f" smNodes:={smn}",f" pmNodes:={pmn}"," sound:=by intro smStore pmStore hstate; exact "+f"{segment_id}_sound smStore pmStore hstate",""])
    return "\n".join(lines)
