"""Atomic reconstruction/chunk/BW-softmax plus transpose/gather renderer."""
from __future__ import annotations


def render_closed_reconstruction_softmax_segment(ir, relation, segment_id: str) -> str:
    try:
        from .composer import _node_text,_render_mixed_final_value,_select_exact_typed_certificate,_shape_text
        from .relation_compiler import (KRankTransposeRelationCertificate,KRankAllReduceReconstructionCertificate,
            KRankFullProducerChunksCertificate,KRankBWSoftmaxCertificate,KRankAllGatherReconstructionCertificate)
    except ImportError:
        from composer import _node_text,_render_mixed_final_value,_select_exact_typed_certificate,_shape_text
        from relation_compiler import (KRankTransposeRelationCertificate,KRankAllReduceReconstructionCertificate,
            KRankFullProducerChunksCertificate,KRankBWSoftmaxCertificate,KRankAllGatherReconstructionCertificate)
    rules=("transpose-sharded-k-rank","allreduce-reconstruction-k-rank","full-producer-chunks-k-rank","bw-softmax-sharded-dim2-rank4","allgather-reconstruction-k-rank")
    theorems={
      rules[0]:"TrainVerify.Denote.RelationCompiler.ShardedRel.fw_transposeAxes_1_2_dim3_rank4",
      rules[1]:"TrainVerify.Denote.RelationCompiler.ReductionRel.to_joined_allReduce",
      rules[2]:"TrainVerify.Denote.allGatherPrimDimN_chunks_ofFn",
      rules[3]:"TrainVerify.Denote.bw_softmax_distribute_allGatherPrimDimN_dim2_4_1_4_2_8_g164",
      rules[4]:"TrainVerify.Denote.RelationCompiler.ShardedRel.to_joined_allGather",
    }
    classes=(KRankTransposeRelationCertificate,KRankAllReduceReconstructionCertificate,KRankFullProducerChunksCertificate,KRankBWSoftmaxCertificate,KRankAllGatherReconstructionCertificate)
    ids=(lambda c:((c.input_fact,),(c.output_fact,)),lambda c:((c.input_fact,),(c.output_fact,)),lambda c:((c.input_fact,),(c.output_fact,)),lambda c:(tuple(sorted((c.gradient_fact,c.activation_fact))),(c.output_fact,)),lambda c:((c.input_fact,),(c.output_fact,)))
    chain=relation.dependent_chain_plan;seg=next((s for s in chain.segments if s.segment_id==segment_id),None)
    if seg is None or len(seg.transition_ids)!=5:raise ValueError("reconstruction/softmax requires five transitions")
    tm={t.transition_id:t for t in relation.transition_specs};ts=tuple(tm[x] for x in seg.transition_ids)
    if tuple(t.rule_id for t in ts)!=rules:raise ValueError("reconstruction/softmax family order mismatch")
    cs=[]
    for t,cls,key in zip(ts,classes,ids):
        if t.lean_theorem!=theorems[t.rule_id]:raise ValueError("reconstruction/softmax theorem mismatch")
        cs.append(_select_exact_typed_certificate(relation,t,t.rule_id,t.lean_theorem,cls,key))
    tc,rc,cc,sc,gc=cs;tt,rt,ct,st,gt=ts;rs={r.source:r for r in chain.relation_facts}
    try:
        tin,tout=rs[tc.input_fact],rs[tc.output_fact];rpre,rjoin=rs[rc.input_fact],rs[rc.output_fact]
        cjoin,cshard=rs[cc.input_fact],rs[cc.output_fact];sg,sy,so=rs[sc.gradient_fact],rs[sc.activation_fact],rs[sc.output_fact]
        gin,gout=rs[gc.input_fact],rs[gc.output_fact]
    except KeyError as exc:raise ValueError("reconstruction/softmax fact missing") from exc
    states={s.state_id:s for s in chain.states};before,after=states[seg.pre_state_id],states[seg.post_state_id]
    if rjoin.source!=cjoin.source or cshard.source!=sc.gradient_fact or tout.source!=gc.input_fact:raise ValueError("reconstruction/softmax internal dependency mismatch")
    required={tin.fact_id,rpre.fact_id,sy.fact_id};proved={cshard.fact_id,so.fact_id,gout.fact_id}
    if not required<=set(before.fact_ids) or not set(after.fact_ids)<=set(before.fact_ids)|proved:raise ValueError("reconstruction/softmax liveness mismatch")
    F=(1,4,8,8);D2=(1,4,2,8);TF=(1,8,4,8);D3=(1,4,8,2);TD3=(1,8,4,2);k=4
    if (tc.rank_count!=k or rc.rank_count!=k or cc.rank_count!=k or sc.rank_count!=k or gc.rank_count!=k
        or tin.kind!="sharded" or tin.gather_dim!=3 or tin.full_shape!=F or tin.shard_shape!=D3
        or tout.kind!="sharded" or tout.gather_dim!=3 or tout.full_shape!=TF or tout.shard_shape!=TD3
        or rpre.kind!="reduction" or rpre.full_shape!=F or rjoin.kind!="joined" or rjoin.joined_pm_tid is None
        or cshard.kind!="sharded" or cshard.gather_dim!=2 or cshard.full_shape!=F or cshard.shard_shape!=D2
        or any(x.kind!="sharded" or x.gather_dim!=2 or x.full_shape!=F or x.shard_shape!=D2 for x in (sg,sy,so))
        or gout.kind!="joined" or gout.joined_pm_tid is None):raise ValueError("reconstruction/softmax metadata mismatch")
    ss,se=seg.sm_range;ps,pe=seg.pm_range;ownedS=tuple(i for t in ts for i in t.sm_node_indices);ownedP=tuple(i for t in ts for i in t.pm_node_indices)
    if len(ownedS)!=len(set(ownedS)) or len(ownedP)!=len(set(ownedP)) or set(ownedS)!=set(range(ss,se)) or set(ownedP)!=set(range(ps,pe)):raise ValueError("reconstruction/softmax frame coverage mismatch")
    tn=ir.sm_nodes[tt.sm_node_indices[0]];tp=tuple(ir.pm_nodes[i] for i in tt.pm_node_indices);rn=ir.pm_nodes[rt.pm_node_indices[0]];cn=tuple(ir.pm_nodes[i] for i in ct.pm_node_indices);sn=ir.sm_nodes[st.sm_node_indices[0]];sp=tuple(ir.pm_nodes[i] for i in st.pm_node_indices);gn=ir.pm_nodes[gt.pm_node_indices[0]]
    if (tn.op!="BW_transpose" or tuple(tn.ins[:1])!=(tin.sm_tid,) or tn.outs!=[tout.sm_tid] or tuple(tn.params)!=(1,2)
        or tuple(n.rank for n in tp)!=(0,1,2,3) or any(n.op!="BW_transpose" or n.ins[0]!=tin.pm_tids[r] or n.outs!=[tout.pm_tids[r]] for r,n in enumerate(tp))):raise ValueError("reconstruction/softmax transpose writers mismatch")
    if rn.op!="AllReducePrim" or tuple(rn.ins)!=rpre.pm_tids or rn.outs!=[rjoin.joined_pm_tid]:raise ValueError("reconstruction/softmax AllReduce writer mismatch")
    if tuple(n.rank for n in cn)!=(0,1,2,3) or any(n.op!="ChunkPrim" or n.ins!=[rjoin.joined_pm_tid] or n.params!=[2] or n.outs!=[cshard.pm_tids[r]] for r,n in enumerate(cn)):raise ValueError("reconstruction/softmax chunk writers mismatch")
    if sn.op!="BW_softmax" or tuple(sn.ins)!=(sg.sm_tid,sy.sm_tid) or sn.outs!=[so.sm_tid] or tuple(n.rank for n in sp)!=(0,1,2,3) or any(n.op!="BW_softmax" or tuple(n.ins)!=(sg.pm_tids[r],sy.pm_tids[r]) or n.outs!=[so.pm_tids[r]] for r,n in enumerate(sp)):raise ValueError("reconstruction/softmax softmax writers mismatch")
    if gn.op!="AllGatherPrim" or tuple(gn.ins)!=gin.pm_tids or gn.outs!=[gout.joined_pm_tid] or gn.params!=[3]:raise ValueError("reconstruction/softmax AllGather writer mismatch")
    smframe=list(ir.sm_nodes[ss:se]);pmframe=list(ir.pm_nodes[ps:pe]);smn,pmn=f"{segment_id}_sm_nodes",f"{segment_id}_pm_nodes";smf,pmf=f"{segment_id}_sm_final",f"{segment_id}_pm_final"
    lines=[f"private def {smn}:List NodeDecl:=[{', '.join(_node_text(n) for n in smframe)}]",f"private def {pmn}:List NodeDecl:=[{', '.join(_node_text(n) for n in pmframe)}]",f"@[irreducible] private def {smf}(s:Store):Store:={smn}.foldl (applyNodeDistributedFaithful {ir.sm_graph_ref}) s",f"@[irreducible] private def {pmf}(s:Store):Store:={pmn}.foldl (applyNodeDistributedFaithful {ir.pm_graph_ref}) s",""]
    def writer(name,graph,initial,fn,nn,frame,pos,node,expr,apply,input_tids=None):
        final=f"({fn} {initial})";th=f"{segment_id}_{name}";lines.extend([f"private theorem {th}({initial}:Store):{final} {node.outs[0]}={expr.format(store=final)}:=by",f"  have hfinal:{final}={nn}.foldl (applyNodeDistributedFaithful {graph}) {initial}:=by unfold {fn};rfl"])
        h=_render_mixed_final_value(name="hout",graph=graph,initial_store=initial,final_store=final,final_equality="hfinal",nodes_name=nn,nodes=frame,position=pos,output_tid=node.outs[0],input_tids=tuple(node.ins if input_tids is None else input_tids),written_tids={u for n in frame for u in n.outs},expression=expr,apply_lines=["rw [applyNodeDistributedFaithful_eq_applyNodeDistributed_of_not_collective (hshuffle:=by native_decide) (hunshuffle:=by native_decide) (hattn:=by native_decide)]","simp [applyNodeDistributed,applyNodeRingAttn]",apply])
        lines.extend(z[2:] if z.startswith("  ") else z for z in h);lines.extend(["  exact hout",""]);return th
    htS=writer("hTransposeSm",ir.sm_graph_ref,"smStore",smf,smn,smframe,tt.sm_node_indices[0]-ss,tn,f"transposeAxes 1 2 ({{store}} {tin.sm_tid})",f"exact applyNode_bw_transposeAxes_out {ir.sm_graph_ref} t 0 {tn.ins[0]} {tn.ins[1]} {tn.outs[0]} 1 2",(tn.ins[0],));htP=[]
    for r,(i,n) in enumerate(zip(tt.pm_node_indices,tp)):htP.append(writer(f"hTransposePm{r}",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,i-ps,n,f"transposeAxes 1 2 ({{store}} {tin.pm_tids[r]})",f"exact applyNode_bw_transposeAxes_out {ir.pm_graph_ref} t {r} {n.ins[0]} {n.ins[1]} {n.outs[0]} 1 2",(n.ins[0],)))
    rlist="["+", ".join(f"{{store}} {u}" for u in rpre.pm_tids)+"]";hR=writer("hAllReduce",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,rt.pm_node_indices[0]-ps,rn,f"allReducePrim 4 0 {rlist}",f"exact applyNode_allReducePrim_out {ir.pm_graph_ref} t 0 {_shape_text(list(rpre.pm_tids))} {rn.outs[0]}")
    hC=[]
    for r,(i,n) in enumerate(zip(ct.pm_node_indices,cn)):hC.append(writer(f"hChunk{r}",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,i-ps,n,f"chunkPrimDimN 2 4 {r} ({{store}} {rjoin.joined_pm_tid})",f"rw [show 4={ir.pm_graph_ref}.numRanks by rfl];simpa using applyNode_chunkPrimDimN_out {ir.pm_graph_ref} t {r} {rjoin.joined_pm_tid} {n.outs[0]} 2"))
    hSS=writer("hSoftmaxSm",ir.sm_graph_ref,"smStore",smf,smn,smframe,st.sm_node_indices[0]-ss,sn,f"bw_softmax ({{store}} {sg.sm_tid}) ({{store}} {sy.sm_tid})",f"exact applyNode_bw_softmax_out_g234 {ir.sm_graph_ref} t 0 {sn.ins[0]} {sn.ins[1]} {sn.outs[0]} []");hSP=[]
    for r,(i,n) in enumerate(zip(st.pm_node_indices,sp)):hSP.append(writer(f"hSoftmaxPm{r}",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,i-ps,n,f"bw_softmax ({{store}} {sg.pm_tids[r]}) ({{store}} {sy.pm_tids[r]})",f"exact applyNode_bw_softmax_out_g234 {ir.pm_graph_ref} t {r} {n.ins[0]} {n.ins[1]} {n.outs[0]} []"))
    glist="["+", ".join(f"{{store}} {u}" for u in gin.pm_tids)+"]";hG=writer("hAllGather",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,gt.pm_node_indices[0]-ps,gn,f"allGatherPrimDimN 3 4 0 {glist}",f"exact applyNode_allGatherPrimDimN_out {ir.pm_graph_ref} t 0 {_shape_text(list(gin.pm_tids))} {gn.outs[0]} 3")
    vals=lambda rec:"["+", ".join(f"pmFinal {u}" for u in rec.pm_tids)+"]";tl,ol,rl,cl,yl,sl=map(vals,(tin,tout,rpre,cshard,sy,so));Ftxt="[1,4,8,8]";D2txt="[1,4,2,8]";TFtxt="[1,8,4,8]";TD3txt="[1,8,4,2]"
    lines.extend(["set_option maxHeartbeats 500000 in",f"private theorem {segment_id}_sound(smStore pmStore:Store)(hstate:{before.state_id}.Holds smStore pmStore):{after.state_id}.Holds ({smf} smStore) ({pmf} pmStore):=by",f" let smFinal:={smf} smStore",f" let pmFinal:={pmf} pmStore",f" have hframe:{before.state_id}.Holds smFinal pmFinal:=by unfold smFinal pmFinal {smf} {pmf};apply RelationState.Holds.fold_frame {smn} {pmn} smStore pmStore hstate <;> native_decide",f" have hti:{tin.fact_id}.Holds smFinal pmFinal:=hframe _ (by native_decide)",f" change ShardedRel (smFinal {tin.sm_tid}) {tl} 3 [1,4,8,2*{tl}.length] [1,4,8,2] at hti",f" have hts:={htS} smStore"])
    for r in range(4):lines.extend([f" have htp{r}:={htP[r]} pmStore",f" change pmFinal {tout.pm_tids[r]}=transposeAxes 1 2 (pmFinal {tin.pm_tids[r]}) at htp{r}"])
    lines.extend([f" change smFinal {tout.sm_tid}=transposeAxes 1 2 (smFinal {tin.sm_tid}) at hts",f" have htRaw:={tc.lean_theorem} hti",f" have hTrans:{tout.fact_id}.Holds smFinal pmFinal:=by change ShardedRel (smFinal {tout.sm_tid}) {ol} 3 {TFtxt} {TD3txt};rw [hts,"+", ".join(f"htp{r}" for r in range(4))+"];simpa using htRaw",f" have hr:{rpre.fact_id}.Holds smFinal pmFinal:=hframe _ (by native_decide)",f" change ReductionRel (smFinal {rpre.sm_tid}) {rl} {Ftxt} at hr",f" have hrw:={hR} pmStore",f" change pmFinal {rjoin.joined_pm_tid}=allReducePrim 4 0 {rl} at hrw",f" have hrEq:smFinal {rpre.sm_tid}=pmFinal {rjoin.joined_pm_tid}:=(ReductionRel.to_joined_allReduce hr).trans hrw.symm"])
    for r in range(4):lines.extend([f" have hc{r}:={hC[r]} pmStore",f" change pmFinal {cshard.pm_tids[r]}=chunkPrimDimN 2 4 {r} (pmFinal {rjoin.joined_pm_tid}) at hc{r}"])
    lines.extend([f" have hChunks:{cshard.fact_id}.Holds smFinal pmFinal:=by",f"  change ShardedRel (smFinal {cshard.sm_tid}) {cl} 2 {Ftxt} {D2txt}","  refine {full_value:=?_,full_shape:=hr.full_shape,shards_nonempty:=by simp,gather_dim_lt:=by native_decide,shard_shapes:=?_,shape_contract:=by simp only [List.length_cons,List.length_nil];native_decide}","  · let pmTids:List Tid:="+_shape_text(list(cshard.pm_tids)),"    let rankCount:=pmTids.length",f"    have hOrdered:pmTids.map pmFinal=List.ofFn (fun r:Fin rankCount=>chunkPrimDimN 2 rankCount r.1 (pmFinal {rjoin.joined_pm_tid})):=by simp only [pmTids,rankCount,List.map];rw ["+", ".join(f"hc{r}" for r in range(4))+"];rfl",f"    have hpmShape:(pmFinal {rjoin.joined_pm_tid}).shape={Ftxt}:=by rw [←hrEq];exact hr.full_shape",f"    change smFinal {cshard.sm_tid}=allGatherPrimDimN 2 rankCount 0 (pmTids.map pmFinal)","    rw [hOrdered]",f"    rw [{cc.lean_theorem} 2 rankCount (pmFinal {rjoin.joined_pm_tid}) (by native_decide) (by rw [hpmShape];native_decide) (by rw [hpmShape];native_decide)]","    exact hrEq","  · intro z hz;simp only [List.mem_cons,List.not_mem_nil,or_false] at hz;rcases hz with h0|h1|h2|h3 <;> subst z",*(f"    · rw [hc{r},chunkPrimDimN_shape 2 4 {r} (pmFinal {rjoin.joined_pm_tid}) {Ftxt} (by rw [←hrEq];exact hr.full_shape) (by native_decide)];native_decide" for r in range(4)),f" have hy:{sy.fact_id}.Holds smFinal pmFinal:=hframe _ (by native_decide)",f" change ShardedRel (smFinal {sy.sm_tid}) {yl} 2 {Ftxt} {D2txt} at hy",f" have hss:={hSS} smStore",f" change smFinal {so.sm_tid}=bw_softmax (smFinal {sg.sm_tid}) (smFinal {sy.sm_tid}) at hss"])
    for r in range(4):lines.extend([f" have hsp{r}:={hSP[r]} pmStore",f" change pmFinal {so.pm_tids[r]}=bw_softmax (pmFinal {sg.pm_tids[r]}) (pmFinal {sy.pm_tids[r]}) at hsp{r}",f" have hcs{r}:=hChunks.shard_shapes (pmFinal {sg.pm_tids[r]}) (by simp)",f" have hys{r}:=hy.shard_shapes (pmFinal {sy.pm_tids[r]}) (by simp)",f" have hos{r}:(pmFinal {so.pm_tids[r]}).shape={D2txt}:=by rw [hsp{r}];exact bw_softmax_shape_d8_g234 _ _ 1 4 2 hys{r}"])
    lines.extend([f" have hcv:smFinal {cshard.sm_tid}=allGatherPrimDimN 2 4 0 {cl}:=by simpa only [List.map,List.length_cons,List.length_nil] using hChunks.full_value",f" have hyv:smFinal {sy.sm_tid}=allGatherPrimDimN 2 4 0 {yl}:=by simpa only [List.map,List.length_cons,List.length_nil] using hy.full_value",f" have hcomm:={sc.lean_theorem} "+" ".join(f"(pmFinal {u})" for u in sg.pm_tids+sy.pm_tids)+" "+" ".join(f"hcs{r}" for r in range(4))+" "+" ".join(f"hys{r}" for r in range(4)),f" have hsv:smFinal {so.sm_tid}=allGatherPrimDimN 2 4 0 {sl}:=by rw [hss,hcv,hyv,hcomm];rw ["+", ".join(f"←hsp{r}" for r in range(4))+"]",f" have hsvl:smFinal {so.sm_tid}=allGatherPrimDimN 2 {sl}.length 0 {sl}:=by simpa only [List.length_cons,List.length_nil] using hsv",f" have hsfull:(smFinal {so.sm_tid}).shape={Ftxt}:=by rw [hss];exact bw_softmax_shape_d8_g234 _ _ 1 4 8 hy.full_shape",f" have houtS:{so.fact_id}.Holds smFinal pmFinal:=by change ShardedRel (smFinal {so.sm_tid}) {sl} 2 {Ftxt} {D2txt};exact {{full_value:=hsvl,full_shape:=hsfull,shards_nonempty:=by simp,gather_dim_lt:=by native_decide,shard_shapes:=by intro z hz;simp only [List.mem_cons,List.not_mem_nil,or_false] at hz;rcases hz with h0|h1|h2|h3 <;> subst z;exact hos0;exact hos1;exact hos2;exact hos3,shape_contract:=by simp only [List.length_cons,List.length_nil];native_decide}}",f" have hgw:={hG} pmStore",f" change pmFinal {gout.joined_pm_tid}=allGatherPrimDimN 3 4 0 {ol} at hgw",f" have hgEq:smFinal {gin.sm_tid}=pmFinal {gout.joined_pm_tid}:=(ShardedRel.to_joined_allGather hTrans).trans hgw.symm",f" have houtG:{gout.fact_id}.Holds smFinal pmFinal:=by change smFinal {gout.sm_tid}=pmFinal {gout.joined_pm_tid}∧_∧_;refine ⟨hgEq,hTrans.full_shape,?_⟩;rw [←hgEq];exact hTrans.full_shape"," intro fact hfact",f" have hc:fact∈[{cshard.fact_id},{so.fact_id},{gout.fact_id}]++{before.state_id}.facts:=by exact (show {after.state_id}.facts⊆[{cshard.fact_id},{so.fact_id},{gout.fact_id}]++{before.state_id}.facts by native_decide) hfact"," simp only [List.mem_append] at hc"," rcases hc with fresh|old"," · simp only [List.mem_cons,List.not_mem_nil,or_false] at fresh;rcases fresh with rfl|rfl|rfl","   · exact hChunks","   · exact houtS","   · exact houtG"," · exact hframe fact old","",f"private def {segment_id}:ClosedDepSegmentCertificate {ir.sm_graph_ref} {ir.pm_graph_ref} {before.state_id} {after.state_id} where",f" smNodes:={smn}",f" pmNodes:={pmn}",f" sound:=by intro a b h;have z:={segment_id}_sound a b h;unfold {smf} {pmf} at z;exact z",""])
    return "\n".join(lines)
