"""Atomic joined-view/chunks and AllToAll/BW-div renderer."""
from __future__ import annotations


def render_closed_view_alltoall_div_chunks_segment(ir, relation, segment_id: str) -> str:
    try:
        from .composer import _node_text,_render_mixed_final_value,_select_exact_typed_certificate,_shape_text
        from .relation_compiler import JoinedBWViewCertificate,KRankAllToAllRelationCertificate,KRankDivCertificate,KRankFullProducerChunksCertificate
    except ImportError:
        from composer import _node_text,_render_mixed_final_value,_select_exact_typed_certificate,_shape_text
        from relation_compiler import JoinedBWViewCertificate,KRankAllToAllRelationCertificate,KRankDivCertificate,KRankFullProducerChunksCertificate
    rules=("bw-view-joined","alltoall-k-rank-layout-transport","div-sharded-k-rank-dim1","full-producer-chunks-k-rank")
    ths=("TrainVerify.Denote.RelationCompiler.JoinedRel.fw_view","TrainVerify.Denote.allGatherPrimDimN_allToAllPrimWithDims_ofFn","TrainVerify.Denote.bw_div_allGatherPrimDimN_eq_g128","TrainVerify.Denote.allGatherPrimDimN_chunks_ofFn")
    classes=(JoinedBWViewCertificate,KRankAllToAllRelationCertificate,KRankDivCertificate,KRankFullProducerChunksCertificate)
    keys=(lambda c:((c.input_fact,),(c.output_fact,)),lambda c:((c.input_fact,),(c.output_fact,)),lambda c:((c.input_fact,),(c.output_fact,)),lambda c:((c.input_fact,),(c.output_fact,)))
    chain=relation.dependent_chain_plan;seg=next((s for s in chain.segments if s.segment_id==segment_id),None)
    if seg is None or len(seg.transition_ids)!=4:raise ValueError("view/AllToAll/div/chunks requires four transitions")
    tm={t.transition_id:t for t in relation.transition_specs};ts=tuple(tm[x] for x in seg.transition_ids)
    if tuple(t.rule_id for t in ts)!=rules or tuple(t.lean_theorem for t in ts)!=ths:raise ValueError("view/AllToAll/div/chunks typed family mismatch")
    cs=[_select_exact_typed_certificate(relation,t,t.rule_id,th,cls,key) for t,th,cls,key in zip(ts,ths,classes,keys)]
    vc,ac,dc,cc=cs;vt,at,dt,ct=ts;rs={r.source:r for r in chain.relation_facts}
    try:
        vi,vo=rs[vc.input_fact],rs[vc.output_fact];ai,ao=rs[ac.input_fact],rs[ac.output_fact]
        di,do=rs[dc.input_fact],rs[dc.output_fact];ci,co=rs[cc.input_fact],rs[cc.output_fact]
    except KeyError as exc:raise ValueError("view/AllToAll/div/chunks fact missing") from exc
    if vo.source!=cc.input_fact or ao.source!=dc.input_fact:raise ValueError("view/AllToAll/div/chunks internal dependency mismatch")
    states={s.state_id:s for s in chain.states};before,after=states[seg.pre_state_id],states[seg.post_state_id]
    required={vi.fact_id,ai.fact_id};proved={vo.fact_id,ao.fact_id,do.fact_id,co.fact_id}
    if not required<=set(before.fact_ids) or not set(after.fact_ids)<=set(before.fact_ids)|proved:raise ValueError("view/AllToAll/div/chunks liveness mismatch")
    if (vi.kind!="joined" or vi.full_shape!=(1,8,4,8) or vo.kind!="joined" or vo.full_shape!=(1,8,32)
        or ai.kind!="sharded" or ai.gather_dim!=2 or ai.full_shape!=(1,4,8,8) or ai.shard_shape!=(1,4,2,8)
        or ao.kind!="sharded" or ao.gather_dim!=1 or ao.full_shape!=(1,4,8,8) or ao.shard_shape!=(1,1,8,8)
        or do.kind!="sharded" or do.gather_dim!=1 or do.full_shape!=(1,4,8,8) or do.shard_shape!=(1,1,8,8)
        or co.kind!="sharded" or co.gather_dim!=2 or co.full_shape!=(1,8,32) or co.shard_shape!=(1,8,8)
        or any(len(x.pm_tids)!=4 for x in (ai,ao,do,co)) or ac.rank_count!=4 or dc.rank_count!=4 or cc.rank_count!=4):raise ValueError("view/AllToAll/div/chunks metadata mismatch")
    ss,se=seg.sm_range;ps,pe=seg.pm_range;ownedS=tuple(i for t in ts for i in t.sm_node_indices);ownedP=tuple(i for t in ts for i in t.pm_node_indices)
    if len(ownedS)!=len(set(ownedS)) or len(ownedP)!=len(set(ownedP)) or set(ownedS)!=set(range(ss,se)) or not set(ownedP)<=set(range(ps,pe)):raise ValueError("view/AllToAll/div/chunks frame mismatch")
    vnS=ir.sm_nodes[vt.sm_node_indices[0]];vnP=ir.pm_nodes[vt.pm_node_indices[0]];an=tuple(ir.pm_nodes[i] for i in at.pm_node_indices);dnS=ir.sm_nodes[dt.sm_node_indices[0]];dnP=tuple(ir.pm_nodes[i] for i in dt.pm_node_indices);cn=tuple(ir.pm_nodes[i] for i in ct.pm_node_indices)
    if vnS.op!="BW_view" or vnP.op!="BW_view" or vnS.ins[0]!=vi.sm_tid or vnP.ins[0]!=vi.joined_pm_tid or vnS.outs!=[vo.sm_tid] or vnP.outs!=[vo.joined_pm_tid]:raise ValueError("view writer mismatch")
    if tuple(n.rank for n in an)!=(0,1,2,3) or any(n.op!="AllToAllPrim" or tuple(n.ins)!=ai.pm_tids or n.outs!=[ao.pm_tids[r]] or n.params!=[2,1] for r,n in enumerate(an)):raise ValueError("AllToAll writers mismatch")
    if dnS.op!="BW_div" or tuple(dnS.ins[:1])!=(di.sm_tid,) or dnS.outs!=[do.sm_tid] or dnS.params!=[2] or tuple(n.rank for n in dnP)!=(0,1,2,3) or any(n.op!="BW_div" or n.ins[0]!=di.pm_tids[r] or n.outs!=[do.pm_tids[r]] or n.params!=[2] for r,n in enumerate(dnP)):raise ValueError("div writers mismatch")
    if tuple(n.rank for n in cn)!=(0,1,2,3) or any(n.op!="ChunkPrim" or n.ins!=[vo.joined_pm_tid] or n.outs!=[co.pm_tids[r]] or n.params!=[2] for r,n in enumerate(cn)):raise ValueError("chunk writers mismatch")
    smframe=list(ir.sm_nodes[ss:se]);pmframe=list(ir.pm_nodes[ps:pe]);smn,pmn=f"{segment_id}_sm_nodes",f"{segment_id}_pm_nodes";smf,pmf=f"{segment_id}_sm_final",f"{segment_id}_pm_final"
    lines=[f"private def {smn}:List NodeDecl:=[{', '.join(_node_text(n) for n in smframe)}]",f"private def {pmn}:List NodeDecl:=[{', '.join(_node_text(n) for n in pmframe)}]",f"@[irreducible] private def {smf}(s:Store):Store:={smn}.foldl (applyNodeDistributedFaithful {ir.sm_graph_ref}) s",f"@[irreducible] private def {pmf}(s:Store):Store:={pmn}.foldl (applyNodeDistributedFaithful {ir.pm_graph_ref}) s",""]
    def writer(name,graph,initial,fn,nn,frame,pos,node,expr,apply,input_tids=None):
        final=f"({fn} {initial})";th=f"{segment_id}_{name}";lines.extend([f"private theorem {th}({initial}:Store):{final} {node.outs[0]}={expr.format(store=final)}:=by",f"  have hfinal:{final}={nn}.foldl (applyNodeDistributedFaithful {graph}) {initial}:=by unfold {fn};rfl"])
        h=_render_mixed_final_value(name="hout",graph=graph,initial_store=initial,final_store=final,final_equality="hfinal",nodes_name=nn,nodes=frame,position=pos,output_tid=node.outs[0],input_tids=tuple(node.ins if input_tids is None else input_tids),written_tids={u for n in frame for u in n.outs},expression=expr,apply_lines=["rw [applyNodeDistributedFaithful_eq_applyNodeDistributed_of_not_collective (hshuffle:=by native_decide) (hunshuffle:=by native_decide) (hattn:=by native_decide)]","simp [applyNodeDistributed,applyNodeRingAttn]",apply])
        lines.extend(z[2:] if z.startswith("  ") else z for z in h);lines.extend(["  exact hout",""]);return th
    target="[1,8,32]";hVS=writer("hViewSm",ir.sm_graph_ref,"smStore",smf,smn,smframe,vt.sm_node_indices[0]-ss,vnS,f"fw_view {target} ({{store}} {vi.sm_tid})",f"exact applyNode_bw_view_out {ir.sm_graph_ref} t 0 1 [8,32] {vnS.ins[0]} {vnS.ins[1]} {vnS.outs[0]}",(vnS.ins[0],));hVP=writer("hViewPm",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,vt.pm_node_indices[0]-ps,vnP,f"fw_view {target} ({{store}} {vi.joined_pm_tid})",f"exact applyNode_bw_view_out {ir.pm_graph_ref} t {vnP.rank} 1 [8,32] {vnP.ins[0]} {vnP.ins[1]} {vnP.outs[0]}",(vnP.ins[0],))
    al=lambda store:"["+", ".join(f"{store} {u}" for u in ai.pm_tids)+"]";hA=[]
    for r,(i,n) in enumerate(zip(at.pm_node_indices,an)):hA.append(writer(f"hAllToAll{r}",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,i-ps,n,f"allToAllPrimWithDims 4 {r} {al('{store}')} 2 1",f"exact applyNode_allToAllPrimWithDims_out {ir.pm_graph_ref} t {r} {_shape_text(list(ai.pm_tids))} {n.outs[0]} 2 1"))
    hDS=writer("hDivSm",ir.sm_graph_ref,"smStore",smf,smn,smframe,dt.sm_node_indices[0]-ss,dnS,f"bw_div (2:Scalar) ({{store}} {di.sm_tid})",f"exact applyNode_bw_div_out_g128 {ir.sm_graph_ref} t 0 2 {dnS.ins[0]} {dnS.ins[1]} {dnS.outs[0]}",(dnS.ins[0],));hDP=[]
    for r,(i,n) in enumerate(zip(dt.pm_node_indices,dnP)):hDP.append(writer(f"hDivPm{r}",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,i-ps,n,f"bw_div (2:Scalar) ({{store}} {di.pm_tids[r]})",f"exact applyNode_bw_div_out_g128 {ir.pm_graph_ref} t {r} 2 {n.ins[0]} {n.ins[1]} {n.outs[0]}",(n.ins[0],)))
    hC=[]
    for r,(i,n) in enumerate(zip(ct.pm_node_indices,cn)):hC.append(writer(f"hChunk{r}",ir.pm_graph_ref,"pmStore",pmf,pmn,pmframe,i-ps,n,f"chunkPrimDimN 2 4 {r} ({{store}} {vo.joined_pm_tid})",f"rw [show 4={ir.pm_graph_ref}.numRanks by rfl];simpa using applyNode_chunkPrimDimN_out {ir.pm_graph_ref} t {r} {vo.joined_pm_tid} {n.outs[0]} 2"))
    vals=lambda x:"["+", ".join(f"pmFinal {u}" for u in x.pm_tids)+"]";ail,aol,dol,col=map(vals,(ai,ao,do,co));F="[1,4,8,8]";A2="[1,4,2,8]";A1="[1,1,8,8]";VF="[1,8,32]";VS="[1,8,8]"
    lines.extend(["set_option maxHeartbeats 500000 in",f"private theorem {segment_id}_sound(smStore pmStore:Store)(hstate:{before.state_id}.Holds smStore pmStore):{after.state_id}.Holds ({smf} smStore) ({pmf} pmStore):=by",f" let smFinal:={smf} smStore",f" let pmFinal:={pmf} pmStore",f" have hframe:{before.state_id}.Holds smFinal pmFinal:=by unfold smFinal pmFinal {smf} {pmf};apply RelationState.Holds.fold_frame {smn} {pmn} smStore pmStore hstate <;> native_decide",f" have hvi:{vi.fact_id}.Holds smFinal pmFinal:=hframe _ (by native_decide)",f" have hvs:={hVS} smStore",f" have hvp:={hVP} pmStore",f" change smFinal {vo.sm_tid}=fw_view {VF} (smFinal {vi.sm_tid}) at hvs",f" change pmFinal {vo.joined_pm_tid}=fw_view {VF} (pmFinal {vi.joined_pm_tid}) at hvp",f" have hView:{vo.fact_id}.Holds smFinal pmFinal:=by change smFinal {vo.sm_tid}=pmFinal {vo.joined_pm_tid}∧_∧_;rw [hvs,hvp];exact JoinedRel.fw_view {VF} [1,8,4,8] hvi"])
    for r in range(4):lines.extend([f" have hc{r}:={hC[r]} pmStore",f" change pmFinal {co.pm_tids[r]}=chunkPrimDimN 2 4 {r} (pmFinal {vo.joined_pm_tid}) at hc{r}"])
    lines.extend([f" have hChunks:{co.fact_id}.Holds smFinal pmFinal:=by",f"  change ShardedRel (smFinal {co.sm_tid}) {col} 2 {VF} {VS}","  refine {full_value:=?_,full_shape:=hView.2.1,shards_nonempty:=by simp,gather_dim_lt:=by native_decide,shard_shapes:=?_,shape_contract:=by simp only [List.length_cons,List.length_nil];native_decide}","  · let pmTids:List Tid:="+_shape_text(list(co.pm_tids)),"    let rankCount:=pmTids.length",f"    have ho:pmTids.map pmFinal=List.ofFn (fun r:Fin rankCount=>chunkPrimDimN 2 rankCount r.1 (pmFinal {vo.joined_pm_tid})):=by simp only [pmTids,rankCount,List.map];rw ["+", ".join(f"hc{r}" for r in range(4))+"];rfl",f"    have hpms:(pmFinal {vo.joined_pm_tid}).shape={VF}:=hView.2.2",f"    change smFinal {co.sm_tid}=allGatherPrimDimN 2 rankCount 0 (pmTids.map pmFinal)","    rw [ho]",f"    rw [{cc.lean_theorem} 2 rankCount (pmFinal {vo.joined_pm_tid}) (by native_decide) (by rw [hpms];native_decide) (by rw [hpms];native_decide)]","    exact hView.1","  · intro z hz;simp only [List.mem_cons,List.not_mem_nil,or_false] at hz;rcases hz with h0|h1|h2|h3 <;> subst z",*(f"    · rw [hc{r},chunkPrimDimN_shape 2 4 {r} (pmFinal {vo.joined_pm_tid}) {VF} hView.2.2 (by native_decide)];native_decide" for r in range(4)),f" have hai:{ai.fact_id}.Holds smFinal pmFinal:=hframe _ (by native_decide)",f" change ShardedRel (smFinal {ai.sm_tid}) {ail} 2 {F} {A2} at hai"])
    for r in range(4):lines.extend([f" have ha{r}:={hA[r]} pmStore",f" change pmFinal {ao.pm_tids[r]}=allToAllPrimWithDims 4 {r} {ail} 2 1 at ha{r}",f" have has{r}:(pmFinal {ao.pm_tids[r]}).shape={A1}:=by rw [ha{r},allToAllPrimWithDims_shape 4 {r} {ail} 2 1 {A2} (by exact hai.shard_shapes _ (by simp)) (by native_decide)];native_decide"])
    lines.extend([f" have hhead:(({ail}.head?.map (fun t=>t.shape)).getD [])={A2}:=by exact hai.shard_shapes _ (by simp)",f" have hav:smFinal {ai.sm_tid}=allGatherPrimDimN 2 4 0 {ail}:=by simpa only [List.length_cons,List.length_nil] using hai.full_value",f" have hgs:(allGatherPrimDimN 2 4 0 {ail}).shape={F}:=by rw [←hav];exact hai.full_shape",f" have hod:1<(allGatherPrimDimN 2 4 0 {ail}).shape.length:=by rw [hgs];native_decide",f" have hdiv:(allGatherPrimDimN 2 4 0 {ail}).shape.getD 1 0%4=0:=by rw [hgs];native_decide",f" have hordered:{aol}=List.ofFn (fun r:Fin 4=>allToAllPrimWithDims 4 r.1 {ail} 2 1):=by rw ["+", ".join(f"ha{r}" for r in range(4))+"];rfl",f" have hat:allGatherPrimDimN 1 4 0 {aol}=allGatherPrimDimN 2 4 0 {ail}:=by rw [hordered];exact {ac.lean_theorem} 2 1 {ail} (by simp) hod hdiv",f" have hao:smFinal {ao.sm_tid}=allGatherPrimDimN 1 4 0 {aol}:=hav.trans hat.symm",f" have hAOut:{ao.fact_id}.Holds smFinal pmFinal:=by change ShardedRel (smFinal {ao.sm_tid}) {aol} 1 {F} {A1};exact {{full_value:=by simpa only [List.length_cons,List.length_nil] using hao,full_shape:=hai.full_shape,shards_nonempty:=by simp,gather_dim_lt:=by native_decide,shard_shapes:=by intro z hz;simp only [List.mem_cons,List.not_mem_nil,or_false] at hz;rcases hz with h0|h1|h2|h3 <;> subst z;exact has0;exact has1;exact has2;exact has3,shape_contract:=by simp only [List.length_cons,List.length_nil];native_decide}}",f" have hds:={hDS} smStore",f" change smFinal {do.sm_tid}=bw_div (2:Scalar) (smFinal {di.sm_tid}) at hds"])
    for r in range(4):lines.extend([f" have hdp{r}:={hDP[r]} pmStore",f" change pmFinal {do.pm_tids[r]}=bw_div (2:Scalar) (pmFinal {di.pm_tids[r]}) at hdp{r}",f" have hdos{r}:(pmFinal {do.pm_tids[r]}).shape={A1}:=by rw [hdp{r},bw_div_shape_g128];exact hAOut.shard_shapes _ (by simp)"])
    lines.extend([f" have hdcomm:={dc.lean_theorem} (2:Scalar) 1 4 {aol} {A1} (by native_decide) (by simp) (by exact hAOut.shard_shapes _ (by simp)) (by intro i hi;exact hAOut.shard_shapes _ (by simpa using List.get_mem {aol} ⟨i,hi⟩))",f" have hdv:smFinal {do.sm_tid}=allGatherPrimDimN 1 4 0 {dol}:=by rw [hds,hao,hdcomm];simp only [List.map];rw ["+", ".join(f"←hdp{r}" for r in range(4))+"]",f" have hdvl:smFinal {do.sm_tid}=allGatherPrimDimN 1 {dol}.length 0 {dol}:=by simpa only [List.length_cons,List.length_nil] using hdv",f" have hdfull:(smFinal {do.sm_tid}).shape={F}:=by rw [hds,bw_div_shape_g128];exact hAOut.full_shape",f" have houtD:{do.fact_id}.Holds smFinal pmFinal:=by change ShardedRel (smFinal {do.sm_tid}) {dol} 1 {F} {A1};exact {{full_value:=hdvl,full_shape:=hdfull,shards_nonempty:=by simp,gather_dim_lt:=by native_decide,shard_shapes:=by intro z hz;simp only [List.mem_cons,List.not_mem_nil,or_false] at hz;rcases hz with h0|h1|h2|h3 <;> subst z;exact hdos0;exact hdos1;exact hdos2;exact hdos3,shape_contract:=by simp only [List.length_cons,List.length_nil];native_decide}}"," intro fact hfact",f" have hc:fact∈[{vo.fact_id},{ao.fact_id},{do.fact_id},{co.fact_id}]++{before.state_id}.facts:=by exact (show {after.state_id}.facts⊆[{vo.fact_id},{ao.fact_id},{do.fact_id},{co.fact_id}]++{before.state_id}.facts by native_decide) hfact"," simp only [List.mem_append] at hc"," rcases hc with fresh|old"," · simp only [List.mem_cons,List.not_mem_nil,or_false] at fresh;rcases fresh with rfl|rfl|rfl|rfl","   · exact hView","   · exact hAOut","   · exact houtD","   · exact hChunks"," · exact hframe fact old","",f"private def {segment_id}:ClosedDepSegmentCertificate {ir.sm_graph_ref} {ir.pm_graph_ref} {before.state_id} {after.state_id} where",f" smNodes:={smn}",f" pmNodes:={pmn}",f" sound:=by intro a b h;have z:={segment_id}_sound a b h;unfold {smf} {pmf} at z;exact z",""])
    return "\n".join(lines)
