/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 37 (tensor id: 1655)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_37 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_transpose", ins := [1654], outs := [1655], params := [1, 2] },
  ]

def pm_goal_37 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.ChunkPrim", ins := [1654], outs := [3817], params := [2] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [1654], outs := [3818], params := [2] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [1654], outs := [3819], params := [2] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [1654], outs := [3820], params := [2] },
    { rank := 0, op := "OpName.FW_transpose", ins := [3817], outs := [3821], params := [1, 2] },
    { rank := 1, op := "OpName.FW_transpose", ins := [3818], outs := [3822], params := [1, 2] },
    { rank := 2, op := "OpName.FW_transpose", ins := [3819], outs := [3823], params := [1, 2] },
    { rank := 3, op := "OpName.FW_transpose", ins := [3820], outs := [3824], params := [1, 2] },
  ]

def sm_goal_37InitShapes : List (Tid × Shape) := [
  (1654, [1, 1024, 12, 64]),
]

def sm_goal_37InitEnv : ShapeEnv := shapeEnvOfList sm_goal_37InitShapes

def pm_goal_37InitShapes : List (Tid × Shape) := [
  (1654, [1, 1024, 12, 64]),
]

def pm_goal_37InitEnv : ShapeEnv := shapeEnvOfList pm_goal_37InitShapes

def goal_37_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_32, goal_36, goal_737, goal_739, goal_741, goal_743, goal_745, goal_747, goal_749, goal_751, goal_757]
def goal_37_cut_initGoals : List LineageGoal := initGoals ++ goal_37_prereqs

def goal_37_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_37 pm_goal_37 goal_37 sm_goal_37InitEnv pm_goal_37InitEnv goal_37_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

