/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 5 (tensor id: 1610)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_5 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [2559, 1608, 1609], outs := [1610] },
  ]

def pm_goal_5 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [3133, 1608, 1609], outs := [3137] },
    { rank := 1, op := "OpName.FW_layernorm", ins := [3134, 1608, 1609], outs := [3138] },
    { rank := 2, op := "OpName.FW_layernorm", ins := [3135, 1608, 1609], outs := [3139] },
    { rank := 3, op := "OpName.FW_layernorm", ins := [3136, 1608, 1609], outs := [3140] },
  ]

def sm_goal_5InitShapes : List (Tid × Shape) := [
  (1608, [768]),
  (1609, [768]),
  (2559, [1, 1024, 768]),
]

def sm_goal_5InitEnv : ShapeEnv := shapeEnvOfList sm_goal_5InitShapes

def pm_goal_5InitShapes : List (Tid × Shape) := [
  (1608, [768]),
  (1609, [768]),
  (3133, [1, 256, 768]),
  (3134, [1, 256, 768]),
  (3135, [1, 256, 768]),
  (3136, [1, 256, 768]),
]

def pm_goal_5InitEnv : ShapeEnv := shapeEnvOfList pm_goal_5InitShapes

def goal_5_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_737]
def goal_5_cut_initGoals : List LineageGoal := initGoals ++ goal_5_prereqs

def goal_5_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_5 pm_goal_5 goal_5 sm_goal_5InitEnv pm_goal_5InitEnv goal_5_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

