/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 737 (tensor id: 2559)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_737 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [1607], outs := [2559, 2563], params := [2] },
  ]

def pm_goal_737 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [3109], outs := [3133, 3509], params := [2] },
    { rank := 1, op := "OpName.FW_multiref", ins := [3110], outs := [3134, 3510], params := [2] },
    { rank := 2, op := "OpName.FW_multiref", ins := [3111], outs := [3135, 3511], params := [2] },
    { rank := 3, op := "OpName.FW_multiref", ins := [3112], outs := [3136, 3512], params := [2] },
  ]

def sm_goal_737InitShapes : List (Tid × Shape) := [
  (1607, [1, 1024, 768]),
]

def sm_goal_737InitEnv : ShapeEnv := shapeEnvOfList sm_goal_737InitShapes

def pm_goal_737InitShapes : List (Tid × Shape) := [
  (3109, [1, 256, 768]),
  (3110, [1, 256, 768]),
  (3111, [1, 256, 768]),
  (3112, [1, 256, 768]),
]

def pm_goal_737InitEnv : ShapeEnv := shapeEnvOfList pm_goal_737InitShapes

def goal_737_prereqs : List LineageGoal := [goal_2, goal_3, goal_4]
def goal_737_cut_initGoals : List LineageGoal := initGoals ++ goal_737_prereqs

def goal_737_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_737 pm_goal_737 goal_737 sm_goal_737InitEnv pm_goal_737InitEnv goal_737_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

