/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 741 (tensor id: 2574)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_741 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [1610], outs := [2574, 2578, 2582], params := [3] },
  ]

def pm_goal_741 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [3137], outs := [9759, 9761, 9763], params := [3] },
    { rank := 1, op := "OpName.FW_multiref", ins := [3138], outs := [9771, 9773, 9775], params := [3] },
    { rank := 2, op := "OpName.FW_multiref", ins := [3139], outs := [9783, 9785, 9787], params := [3] },
    { rank := 3, op := "OpName.FW_multiref", ins := [3140], outs := [9795, 9797, 9799], params := [3] },
    { rank := 0, op := "OpName.AllGatherPrim", ins := [9759, 9771, 9783, 9795], outs := [2571], params := [1] },
  ]

def sm_goal_741InitShapes : List (Tid × Shape) := [
  (1610, [1, 1024, 768]),
]

def sm_goal_741InitEnv : ShapeEnv := shapeEnvOfList sm_goal_741InitShapes

def pm_goal_741InitShapes : List (Tid × Shape) := [
  (3137, [1, 256, 768]),
  (3138, [1, 256, 768]),
  (3139, [1, 256, 768]),
  (3140, [1, 256, 768]),
]

def pm_goal_741InitEnv : ShapeEnv := shapeEnvOfList pm_goal_741InitShapes

def goal_741_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_737]
def goal_741_cut_initGoals : List LineageGoal := initGoals ++ goal_741_prereqs

def goal_741_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_741 pm_goal_741 goal_741 sm_goal_741InitEnv pm_goal_741InitEnv goal_741_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

