/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 105 (tensor id: 1750)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_105 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [2731, 1748, 1749], outs := [1750] },
  ]

def pm_goal_105 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [5321, 1748, 1749], outs := [5325] },
    { rank := 1, op := "OpName.FW_layernorm", ins := [5322, 1748, 1749], outs := [5326] },
    { rank := 2, op := "OpName.FW_layernorm", ins := [5323, 1748, 1749], outs := [5327] },
    { rank := 3, op := "OpName.FW_layernorm", ins := [5324, 1748, 1749], outs := [5328] },
  ]

def sm_goal_105InitShapes : List (Tid × Shape) := [
  (1748, [768]),
  (1749, [768]),
  (2731, [1, 1024, 768]),
]

def sm_goal_105InitEnv : ShapeEnv := shapeEnvOfList sm_goal_105InitShapes

def pm_goal_105InitShapes : List (Tid × Shape) := [
  (1748, [768]),
  (1749, [768]),
  (5321, [1, 256, 768]),
  (5322, [1, 256, 768]),
  (5323, [1, 256, 768]),
  (5324, [1, 256, 768]),
]

def pm_goal_105InitEnv : ShapeEnv := shapeEnvOfList pm_goal_105InitShapes

def goal_105_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_737, goal_739, goal_741, goal_743, goal_745, goal_747, goal_749, goal_751, goal_753, goal_755, goal_757, goal_759, goal_761, goal_763, goal_765, goal_767, goal_769, goal_771, goal_773, goal_775, goal_777, goal_779, goal_781, goal_783, goal_785, goal_787, goal_789, goal_791, goal_793]
def goal_105_cut_initGoals : List LineageGoal := initGoals ++ goal_105_prereqs

def goal_105_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_105 pm_goal_105 goal_105 sm_goal_105InitEnv pm_goal_105InitEnv goal_105_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

