/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 30 (tensor id: 1645)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_30 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [2602, 1643, 1644], outs := [1645] },
  ]

def pm_goal_30 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_layernorm", ins := [3677, 1643, 1644], outs := [3681] },
    { rank := 1, op := "OpName.FW_layernorm", ins := [3678, 1643, 1644], outs := [3682] },
    { rank := 2, op := "OpName.FW_layernorm", ins := [3679, 1643, 1644], outs := [3683] },
    { rank := 3, op := "OpName.FW_layernorm", ins := [3680, 1643, 1644], outs := [3684] },
  ]

def sm_goal_30InitShapes : List (Tid × Shape) := [
  (1643, [768]),
  (1644, [768]),
  (2602, [1, 1024, 768]),
]

def sm_goal_30InitEnv : ShapeEnv := shapeEnvOfList sm_goal_30InitShapes

def pm_goal_30InitShapes : List (Tid × Shape) := [
  (1643, [768]),
  (1644, [768]),
  (3677, [1, 256, 768]),
  (3678, [1, 256, 768]),
  (3679, [1, 256, 768]),
  (3680, [1, 256, 768]),
]

def pm_goal_30InitEnv : ShapeEnv := shapeEnvOfList pm_goal_30InitShapes

def goal_30_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_737, goal_739, goal_741, goal_743, goal_745, goal_747, goal_749, goal_751]
def goal_30_cut_initGoals : List LineageGoal := initGoals ++ goal_30_prereqs

def goal_30_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_30 pm_goal_30 goal_30 sm_goal_30InitEnv pm_goal_30InitEnv goal_30_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

