/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 31 (tensor id: 1647)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_31 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [2617, 1646], outs := [1647] },
  ]

def pm_goal_31 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [3709, 1646], outs := [3713] },
    { rank := 1, op := "OpName.FW_linear", ins := [3710, 1646], outs := [3714] },
    { rank := 2, op := "OpName.FW_linear", ins := [3711, 1646], outs := [3715] },
    { rank := 3, op := "OpName.FW_linear", ins := [3712, 1646], outs := [3716] },
    { rank := 0, op := "OpName.AllGatherPrim", ins := [3713, 3714, 3715, 3716], outs := [1647], params := [1] },
  ]

def sm_goal_31InitShapes : List (Tid × Shape) := [
  (1646, [768, 768]),
  (2617, [1, 1024, 768]),
]

def sm_goal_31InitEnv : ShapeEnv := shapeEnvOfList sm_goal_31InitShapes

def pm_goal_31InitShapes : List (Tid × Shape) := [
  (1646, [768, 768]),
  (3709, [1, 256, 768]),
  (3710, [1, 256, 768]),
  (3711, [1, 256, 768]),
  (3712, [1, 256, 768]),
]

def pm_goal_31InitEnv : ShapeEnv := shapeEnvOfList pm_goal_31InitShapes

def goal_31_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_737, goal_739, goal_741, goal_743, goal_745, goal_747, goal_749, goal_751, goal_755]
def goal_31_cut_initGoals : List LineageGoal := initGoals ++ goal_31_prereqs

def goal_31_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_31 pm_goal_31 goal_31 sm_goal_31InitEnv pm_goal_31InitEnv goal_31_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

