/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 771 (tensor id: 2664)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_771 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [1680], outs := [2660, 2664, 2668], params := [3] },
  ]

def pm_goal_771 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [4237], outs := [9919, 9921, 9923], params := [3] },
    { rank := 1, op := "OpName.FW_multiref", ins := [4238], outs := [9931, 9933, 9935], params := [3] },
    { rank := 2, op := "OpName.FW_multiref", ins := [4239], outs := [9943, 9945, 9947], params := [3] },
    { rank := 3, op := "OpName.FW_multiref", ins := [4240], outs := [9955, 9957, 9959], params := [3] },
    { rank := 0, op := "OpName.AllToAllPrim", ins := [9921, 9933, 9945, 9957], outs := [4293], params := [1, 2] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [9921, 9933, 9945, 9957], outs := [4294], params := [1, 2] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [9921, 9933, 9945, 9957], outs := [4295], params := [1, 2] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [9921, 9933, 9945, 9957], outs := [4296], params := [1, 2] },
  ]

def sm_goal_771InitShapes : List (Tid × Shape) := [
  (1680, [1, 1024, 768]),
]

def sm_goal_771InitEnv : ShapeEnv := shapeEnvOfList sm_goal_771InitShapes

def pm_goal_771InitShapes : List (Tid × Shape) := [
  (4237, [1, 256, 768]),
  (4238, [1, 256, 768]),
  (4239, [1, 256, 768]),
  (4240, [1, 256, 768]),
]

def pm_goal_771InitEnv : ShapeEnv := shapeEnvOfList pm_goal_771InitShapes

def goal_771_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_737, goal_739, goal_741, goal_743, goal_745, goal_747, goal_749, goal_751, goal_753, goal_755, goal_757, goal_759, goal_761, goal_763, goal_765]
def goal_771_cut_initGoals : List LineageGoal := initGoals ++ goal_771_prereqs

def goal_771_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_771 pm_goal_771 goal_771 sm_goal_771InitEnv pm_goal_771InitEnv goal_771_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

