/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 767 (tensor id: 2649)
-/
import denote.gpt2_small_ly12_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_767 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [1677], outs := [2645, 2649], params := [2] },
  ]

def pm_goal_767 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [4209], outs := [9893, 4613], params := [2] },
    { rank := 1, op := "OpName.FW_multiref", ins := [4210], outs := [9899, 4614], params := [2] },
    { rank := 2, op := "OpName.FW_multiref", ins := [4211], outs := [9905, 4615], params := [2] },
    { rank := 3, op := "OpName.FW_multiref", ins := [4212], outs := [9911, 4616], params := [2] },
  ]

def sm_goal_767InitShapes : List (Tid × Shape) := [
  (1677, [1, 1024, 768]),
]

def sm_goal_767InitEnv : ShapeEnv := shapeEnvOfList sm_goal_767InitShapes

def pm_goal_767InitShapes : List (Tid × Shape) := [
  (4209, [1, 1024, 192]),
  (4210, [1, 1024, 192]),
  (4211, [1, 1024, 192]),
  (4212, [1, 1024, 192]),
]

def pm_goal_767InitEnv : ShapeEnv := shapeEnvOfList pm_goal_767InitShapes

def goal_767_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_737, goal_739, goal_741, goal_743, goal_745, goal_747, goal_749, goal_751, goal_753, goal_755, goal_757, goal_759, goal_761, goal_763]
def goal_767_cut_initGoals : List LineageGoal := initGoals ++ goal_767_prereqs

def goal_767_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_767 pm_goal_767 goal_767 sm_goal_767InitEnv pm_goal_767InitEnv goal_767_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

