/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 310 (tensor id: 1064)
-/
import denote.gpt_ly4_segments.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_310 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_layernorm", ins := [884, 1063, 699, 700], outs := [1064, 882, 883] },
  ]

def pm_goal_310 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_layernorm", ins := [3220, 3201, 699, 700], outs := [3217, 3218, 3219] },
    { rank := 1, op := "OpName.BW_layernorm", ins := [3224, 3202, 699, 700], outs := [3221, 3222, 3223] },
    { rank := 2, op := "OpName.BW_layernorm", ins := [3228, 3203, 699, 700], outs := [3225, 3226, 3227] },
    { rank := 3, op := "OpName.BW_layernorm", ins := [3232, 3204, 699, 700], outs := [3229, 3230, 3231] },
  ]

def sm_goal_310InitShapes : List (Tid × Shape) := [
  (699, [32]),
  (700, [32]),
  (884, [1, 8, 32]),
  (1063, [1, 8, 32]),
]

def sm_goal_310InitEnv : ShapeEnv := shapeEnvOfList sm_goal_310InitShapes

def pm_goal_310InitShapes : List (Tid × Shape) := [
  (699, [32]),
  (700, [32]),
  (3201, [1, 2, 32]),
  (3202, [1, 2, 32]),
  (3203, [1, 2, 32]),
  (3204, [1, 2, 32]),
  (3220, [1, 2, 32]),
  (3224, [1, 2, 32]),
  (3228, [1, 2, 32]),
  (3232, [1, 2, 32]),
]

def pm_goal_310InitEnv : ShapeEnv := shapeEnvOfList pm_goal_310InitShapes

def goal_310_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_56, goal_57, goal_58, goal_59, goal_60, goal_61, goal_62, goal_63, goal_64, goal_65, goal_66, goal_67, goal_68, goal_69, goal_70, goal_71, goal_72, goal_73, goal_74, goal_75, goal_76, goal_77, goal_78, goal_79, goal_80, goal_81, goal_82, goal_83, goal_84, goal_85, goal_86, goal_87, goal_88, goal_89, goal_90, goal_91, goal_92, goal_93, goal_94, goal_95, goal_96, goal_97, goal_98, goal_99, goal_100, goal_101, goal_102, goal_103, goal_104, goal_105, goal_106, goal_245, goal_247, goal_248, goal_250, goal_251, goal_254, goal_256, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_287, goal_289, goal_291, goal_293, goal_295, goal_297, goal_299, goal_301, goal_303, goal_305, goal_307, goal_309, goal_311]
def goal_310_cut_initGoals : List LineageGoal := initGoals ++ goal_310_prereqs

def goal_310_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_310 pm_goal_310 goal_310 sm_goal_310InitEnv pm_goal_310InitEnv goal_310_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

