/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 42 (tensor id: 159)
-/
import denote.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_42 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [121], outs := [159, 163, 167], params := [3] },
  ]

def pm_goal_42 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_multiref", ins := [121], outs := [156, 157, 158], params := [3] },
    { rank := 1, op := "OpName.FW_multiref", ins := [121], outs := [156, 157, 158], params := [3] },
    { rank := 2, op := "OpName.FW_multiref", ins := [121], outs := [156, 157, 158], params := [3] },
    { rank := 3, op := "OpName.FW_multiref", ins := [121], outs := [156, 157, 158], params := [3] },
    { rank := 0, op := "OpName.ChunkPrim", ins := [156], outs := [168], params := [0] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [156], outs := [169], params := [0] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [156], outs := [170], params := [0] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [156], outs := [171], params := [0] },
  ]

def sm_goal_42InitShapes : List (Tid × Shape) := [
  (121, [16, 64, 128]),
]

def sm_goal_42InitEnv : ShapeEnv := shapeEnvOfList sm_goal_42InitShapes

def pm_goal_42InitShapes : List (Tid × Shape) := [
  (121, [16, 64, 128]),
]

def pm_goal_42InitEnv : ShapeEnv := shapeEnvOfList pm_goal_42InitShapes

def goal_42_cut_initGoals : List LineageGoal := initGoals

def goal_42_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_42 pm_goal_42 goal_42 sm_goal_42InitEnv pm_goal_42InitEnv goal_42_cut_initGoals

theorem prove_goal_42_cut : goal_42_stmt_cut := by
  sorry

end TrainVerify.Denote.GeneratedGoals

