/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 3 (tensor id: 23)
-/
import denote.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_3 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_linear", ins := [24, 20, 16], outs := [21, 23] },
  ]

def pm_goal_3 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.ChunkPrim", ins := [20], outs := [26] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [20], outs := [27] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [20], outs := [28] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [20], outs := [29] },
    { rank := 0, op := "OpName.BW_linear", ins := [24, 26, 30], outs := [46, 47] },
    { rank := 1, op := "OpName.BW_linear", ins := [24, 27, 31], outs := [48, 49] },
    { rank := 2, op := "OpName.BW_linear", ins := [24, 28, 32], outs := [50, 51] },
    { rank := 3, op := "OpName.BW_linear", ins := [24, 29, 33], outs := [52, 53] },
  ]

def sm_goal_3InitShapes : List (Tid × Shape) := [
  (16, [128, 128]),
  (20, [128, 128]),
  (24, [128, 128]),
]

def sm_goal_3InitEnv : ShapeEnv := shapeEnvOfList sm_goal_3InitShapes

def pm_goal_3InitShapes : List (Tid × Shape) := [
  (20, [128, 128]),
  (24, [128, 128]),
  (30, [128, 32]),
  (31, [128, 32]),
  (32, [128, 32]),
  (33, [128, 32]),
]

def pm_goal_3InitEnv : ShapeEnv := shapeEnvOfList pm_goal_3InitShapes

def goal_3_cut_initGoals : List LineageGoal := initGoals ++ goal_3_prereqs

def goal_3_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_3 pm_goal_3 goal_3 sm_goal_3InitEnv pm_goal_3InitEnv goal_3_cut_initGoals

theorem prove_goal_3_cut : goal_3_stmt_cut := by
  sorry

end TrainVerify.Denote.GeneratedGoals

