/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 27 (tensor id: 131)
-/
import denote.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_27 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_matmul", ins := [137, 104, 109], outs := [131, 136] },
  ]

def pm_goal_27 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.AllToAllPrim", ins := [256, 257, 258, 259], outs := [348], params := [3, 0] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [256, 257, 258, 259], outs := [349], params := [3, 0] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [256, 257, 258, 259], outs := [350], params := [3, 0] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [256, 257, 258, 259], outs := [351], params := [3, 0] },
    { rank := 0, op := "OpName.BW_matmul", ins := [365, 348, 328], outs := [364, 341] },
    { rank := 1, op := "OpName.BW_matmul", ins := [367, 349, 329], outs := [366, 343] },
    { rank := 2, op := "OpName.BW_matmul", ins := [369, 350, 330], outs := [368, 345] },
    { rank := 3, op := "OpName.BW_matmul", ins := [371, 351, 331], outs := [370, 347] },
    { rank := 0, op := "OpName.AllToAllPrim", ins := [364, 366, 368, 370], outs := [269], params := [3, 0] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [364, 366, 368, 370], outs := [271], params := [3, 0] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [364, 366, 368, 370], outs := [273], params := [3, 0] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [364, 366, 368, 370], outs := [275], params := [3, 0] },
  ]

def sm_goal_27InitShapes : List (Tid × Shape) := [
  (104, [16, 8, 64, 16]),
  (109, [16, 8, 16, 64]),
  (137, [16, 8, 64, 64]),
]

def sm_goal_27InitEnv : ShapeEnv := shapeEnvOfList sm_goal_27InitShapes

def pm_goal_27InitShapes : List (Tid × Shape) := [
  (256, [16, 8, 64, 4]),
  (257, [16, 8, 64, 4]),
  (258, [16, 8, 64, 4]),
  (259, [16, 8, 64, 4]),
  (328, [4, 8, 16, 64]),
  (329, [4, 8, 16, 64]),
  (330, [4, 8, 16, 64]),
  (331, [4, 8, 16, 64]),
  (365, [4, 8, 64, 64]),
  (367, [4, 8, 64, 64]),
  (369, [4, 8, 64, 64]),
  (371, [4, 8, 64, 64]),
]

def pm_goal_27InitEnv : ShapeEnv := shapeEnvOfList pm_goal_27InitShapes

def goal_27_cut_initGoals : List LineageGoal := initGoals ++ goal_27_prereqs

def goal_27_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_27 pm_goal_27 goal_27 sm_goal_27InitEnv pm_goal_27InitEnv goal_27_cut_initGoals

theorem prove_goal_27_cut : goal_27_stmt_cut := by
  sorry

end TrainVerify.Denote.GeneratedGoals

