/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 57 (tensor id: 644)
-/
import trainverify.denote.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_57 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [1008, 643], outs := [644] },
  ]

def pm_goal_57 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [1000, 2285], outs := [2289] },
    { rank := 1, op := "OpName.FW_linear", ins := [1000, 2286], outs := [2290] },
    { rank := 2, op := "OpName.FW_linear", ins := [1000, 2287], outs := [2291] },
    { rank := 3, op := "OpName.FW_linear", ins := [1000, 2288], outs := [2292] },
    { rank := 0, op := "OpName.AllGatherPrim", ins := [2289, 2290, 2291, 2292], outs := [644], params := [2] },
  ]

def sm_goal_57InitShapes : List (Tid × Shape) := [
  (643, [32, 32]),
  (1008, [1, 8, 32]),
]

def sm_goal_57InitEnv : ShapeEnv := shapeEnvOfList sm_goal_57InitShapes

def pm_goal_57InitShapes : List (Tid × Shape) := [
  (1000, [1, 8, 32]),
  (2285, [8, 32]),
  (2286, [8, 32]),
  (2287, [8, 32]),
  (2288, [8, 32]),
]

def pm_goal_57InitEnv : ShapeEnv := shapeEnvOfList pm_goal_57InitShapes

def goal_57_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_26, goal_27, goal_28, goal_29, goal_30, goal_31, goal_32, goal_33, goal_34, goal_35, goal_36, goal_37, goal_38, goal_39, goal_40, goal_41, goal_42, goal_43, goal_44, goal_45, goal_46, goal_47, goal_48, goal_49, goal_50, goal_51, goal_52, goal_53, goal_54, goal_55, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267, goal_269, goal_271, goal_273, goal_275, goal_277, goal_279, goal_281, goal_283, goal_285, goal_291]
def goal_57_cut_initGoals : List LineageGoal := initGoals ++ goal_57_prereqs

def goal_57_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_57 pm_goal_57 goal_57 sm_goal_57InitEnv pm_goal_57InitEnv goal_57_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

