/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 14 (tensor id: 582)
-/
import trainverify.denote.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_14 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_transpose", ins := [581], outs := [582], params := [1, 2] },
  ]

def pm_goal_14 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.ChunkPrim", ins := [581], outs := [1305], params := [3] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [581], outs := [1306], params := [3] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [581], outs := [1307], params := [3] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [581], outs := [1308], params := [3] },
    { rank := 0, op := "OpName.FW_transpose", ins := [1305], outs := [1309], params := [1, 2] },
    { rank := 1, op := "OpName.FW_transpose", ins := [1306], outs := [1310], params := [1, 2] },
    { rank := 2, op := "OpName.FW_transpose", ins := [1307], outs := [1311], params := [1, 2] },
    { rank := 3, op := "OpName.FW_transpose", ins := [1308], outs := [1312], params := [1, 2] },
  ]

def sm_goal_14InitShapes : List (Tid × Shape) := [
  (581, [1, 8, 4, 8]),
]

def sm_goal_14InitEnv : ShapeEnv := shapeEnvOfList sm_goal_14InitShapes

def pm_goal_14InitShapes : List (Tid × Shape) := [
  (581, [1, 8, 4, 8]),
]

def pm_goal_14InitEnv : ShapeEnv := shapeEnvOfList pm_goal_14InitShapes

def goal_14_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_8, goal_13, goal_257, goal_265]
def goal_14_cut_initGoals : List LineageGoal := initGoals ++ goal_14_prereqs

def goal_14_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_14 pm_goal_14 goal_14 sm_goal_14InitEnv pm_goal_14InitEnv goal_14_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

