/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 26 (tensor id: 598)
-/
import trainverify.denote.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_26 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [596, 597], outs := [598] },
  ]

def pm_goal_26 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_linear", ins := [596, 1557], outs := [1561] },
    { rank := 1, op := "OpName.FW_linear", ins := [596, 1558], outs := [1562] },
    { rank := 2, op := "OpName.FW_linear", ins := [596, 1559], outs := [1563] },
    { rank := 3, op := "OpName.FW_linear", ins := [596, 1560], outs := [1564] },
  ]

def sm_goal_26InitShapes : List (Tid × Shape) := [
  (596, [1, 8, 32]),
  (597, [128, 32]),
]

def sm_goal_26InitEnv : ShapeEnv := shapeEnvOfList sm_goal_26InitShapes

def pm_goal_26InitShapes : List (Tid × Shape) := [
  (596, [1, 8, 32]),
  (1557, [32, 32]),
  (1558, [32, 32]),
  (1559, [32, 32]),
  (1560, [32, 32]),
]

def pm_goal_26InitEnv : ShapeEnv := shapeEnvOfList pm_goal_26InitShapes

def goal_26_prereqs : List LineageGoal := [goal_2, goal_3, goal_4, goal_5, goal_6, goal_7, goal_8, goal_9, goal_10, goal_11, goal_12, goal_13, goal_14, goal_15, goal_16, goal_17, goal_18, goal_19, goal_20, goal_21, goal_22, goal_23, goal_24, goal_25, goal_257, goal_259, goal_261, goal_263, goal_265, goal_267]
def goal_26_cut_initGoals : List LineageGoal := initGoals ++ goal_26_prereqs

def goal_26_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_26 pm_goal_26 goal_26 sm_goal_26InitEnv pm_goal_26InitEnv goal_26_cut_initGoals

end TrainVerify.Denote.GeneratedGoals

