name = "trainverify"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Trainverify"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.style.longLine = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Trainverify"

[[lean_lib]]
name = "denote"
roots = ["denote"]
moreLeanArgs = ["--tstack=65536"]
