/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 30 (tensor id: 134)
-/
import denote.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_30 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.BW_transpose", ins := [135, 107], outs := [134] },
  ]

def pm_goal_30 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.ChunkPrim", ins := [107], outs := [300] },
    { rank := 1, op := "OpName.ChunkPrim", ins := [107], outs := [301] },
    { rank := 2, op := "OpName.ChunkPrim", ins := [107], outs := [302] },
    { rank := 3, op := "OpName.ChunkPrim", ins := [107], outs := [303] },
    { rank := 0, op := "OpName.BW_transpose", ins := [317, 300], outs := [316] },
    { rank := 1, op := "OpName.BW_transpose", ins := [319, 301], outs := [318] },
    { rank := 2, op := "OpName.BW_transpose", ins := [321, 302], outs := [320] },
    { rank := 3, op := "OpName.BW_transpose", ins := [323, 303], outs := [322] },
    { rank := 0, op := "OpName.AllGatherPrim", ins := [316, 318, 320, 322], outs := [134] },
  ]

def sm_goal_30InitShapes : List (Tid × Shape) := [
  (107, [16, 64, 8, 16]),
  (135, [16, 8, 64, 16]),
]

def sm_goal_30InitEnv : ShapeEnv := shapeEnvOfList sm_goal_30InitShapes

def pm_goal_30InitShapes : List (Tid × Shape) := [
  (107, [16, 64, 8, 16]),
  (317, [16, 2, 64, 16]),
  (319, [16, 2, 64, 16]),
  (321, [16, 2, 64, 16]),
  (323, [16, 2, 64, 16]),
]

def pm_goal_30InitEnv : ShapeEnv := shapeEnvOfList pm_goal_30InitShapes

def goal_30_cut_initGoals : List LineageGoal := initGoals ++ goal_30_prereqs

def goal_30_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_30 pm_goal_30 goal_30 sm_goal_30InitEnv pm_goal_30InitEnv goal_30_cut_initGoals

theorem prove_goal_30_cut : goal_30_stmt_cut := by
  sorry

end TrainVerify.Denote.GeneratedGoals

