/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 1 (tensor id: 96)
-/
import denote.attn.GeneratedData

open TrainVerify.Denote
open TrainVerify.Denote.Generated

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_1 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_sum", ins := [118], outs := [96] },
  ]

def pm_goal_1 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.AllToAllPrim", ins := [500, 501, 502, 503], outs := [524] },
    { rank := 1, op := "OpName.AllToAllPrim", ins := [500, 501, 502, 503], outs := [525] },
    { rank := 2, op := "OpName.AllToAllPrim", ins := [500, 501, 502, 503], outs := [526] },
    { rank := 3, op := "OpName.AllToAllPrim", ins := [500, 501, 502, 503], outs := [527] },
    { rank := 0, op := "OpName.FW_sum", ins := [524], outs := [528] },
    { rank := 1, op := "OpName.FW_sum", ins := [525], outs := [529] },
    { rank := 2, op := "OpName.FW_sum", ins := [526], outs := [530] },
    { rank := 3, op := "OpName.FW_sum", ins := [527], outs := [531] },
    { rank := 0, op := "OpName.AllReducePrim", ins := [528, 529, 530, 531], outs := [96] },
  ]

def sm_goal_1InitShapes : List (Tid × Shape) := [
  (118, [16, 64, 128]),
]

def sm_goal_1InitEnv : ShapeEnv := shapeEnvOfList sm_goal_1InitShapes

def pm_goal_1InitShapes : List (Tid × Shape) := [
  (500, [16, 16, 128]),
  (501, [16, 16, 128]),
  (502, [16, 16, 128]),
  (503, [16, 16, 128]),
]

def pm_goal_1InitEnv : ShapeEnv := shapeEnvOfList pm_goal_1InitShapes

def goal_1_cut_initGoals : List LineageGoal := initGoals ++ goal_1_prereqs

def goal_1_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_1 pm_goal_1 goal_1 sm_goal_1InitEnv pm_goal_1InitEnv goal_1_cut_initGoals

set_option linter.style.longLine false in
set_option maxHeartbeats 400000 in
-- allGatherPrimDim0 shape mismatch makes hypothesis contradictory (vacuous proof)
theorem prove_goal_1_cut : goal_1_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  exfalso
  -- Extract InitGoalHolds for intermediateGoal_118
  have hInit118 : InitGoalHolds pm_goal_1.numRanks intermediateGoal_118 initSM initPM := by
    apply hInitGoals
    decide
  -- (initSM 118).shape = [16, 64, 128] from InitGoalHolds
  have hshape_sm : (initSM 118).shape = [16, 64, 128] := by
    have := hInit118.1; simp only [intermediateGoal_118] at this; exact this
  -- initSM 118 = reconstruct 4 0 [initPM 500, ..., 503]
  have hrec : initSM 118 = reconstruct pm_goal_1.numRanks 0
      [initPM 500, initPM 501, initPM 502, initPM 503] := by
    have := hInit118.2.2; simp only [intermediateGoal_118] at this; exact this
  -- (initPM 500).shape = [16, 16, 128]
  have hshapes : List.map (fun t => t.shape)
      [initPM 500, initPM 501, initPM 502, initPM 503] =
      [[16, 16, 128], [16, 16, 128], [16, 16, 128], [16, 16, 128]] := by
    have := hInit118.2.1; simp only [intermediateGoal_118] at this; exact this
  have hshape_500 : (initPM 500).shape = [16, 16, 128] := by
    simpa using congrArg List.head? hshapes
  -- reconstruct for 3D = allGatherPrimDim0
  have hrec_3d : reconstruct pm_goal_1.numRanks 0
      [initPM 500, initPM 501, initPM 502, initPM 503] =
      allGatherPrimDim0 pm_goal_1.numRanks 0
        [initPM 500, initPM 501, initPM 502, initPM 503] :=
    reconstruct_cons_cons_3d _ _ _ _ _ 16 16 128 hshape_500
  -- Shape of allGatherPrimDim0: [16*4, 16, 128] = [64, 16, 128]
  have hhead : (Option.map (fun t => t.shape)
      ([initPM 500, initPM 501, initPM 502, initPM 503] : List Tensor).head?).getD []
      = (initPM 500).shape := rfl
  have hshape_gather : (allGatherPrimDim0 pm_goal_1.numRanks 0
      [initPM 500, initPM 501, initPM 502, initPM 503]).shape =
      [64, 16, 128] := by
    unfold allGatherPrimDim0
    rw [hhead, hshape_500]
    simp [pm_goal_1, Tensor.mkShape]
  -- Contradiction: [16, 64, 128] = [64, 16, 128]
  have hcontra : ([16, 64, 128] : Shape) = [64, 16, 128] := by
    calc ([16, 64, 128] : Shape)
        = (initSM 118).shape := hshape_sm.symm
      _ = (reconstruct pm_goal_1.numRanks 0
            [initPM 500, initPM 501, initPM 502, initPM 503]).shape := by
          rw [← hrec]
      _ = (allGatherPrimDim0 pm_goal_1.numRanks 0
            [initPM 500, initPM 501, initPM 502, initPM 503]).shape := by
          rw [hrec_3d]
      _ = [64, 16, 128] := hshape_gather
  exact absurd hcontra (by decide)

end TrainVerify.Denote.GeneratedGoals

