/- Auto-generated by Verdict/graph_to_lean.py
    Goal: 9 (tensor id: 107)
-/
import denote.attn.GeneratedData
import denote.attn.Common

open TrainVerify.Denote
open TrainVerify.Denote.Generated
open TrainVerify.Denote.Common

namespace TrainVerify.Denote.GeneratedGoals

def sm_goal_9 : GraphDecl := by
  refine { numRanks := 1, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_view", ins := [102], outs := [107], params := [16, 64, 8, 16] },
  ]

def pm_goal_9 : GraphDecl := by
  refine { numRanks := 4, nodes := ?_ }
  exact [
    { rank := 0, op := "OpName.FW_view", ins := [102], outs := [107], params := [16, 64, 8, 16] },
    { rank := 1, op := "OpName.FW_view", ins := [102], outs := [107], params := [16, 64, 8, 16] },
    { rank := 2, op := "OpName.FW_view", ins := [102], outs := [107], params := [16, 64, 8, 16] },
    { rank := 3, op := "OpName.FW_view", ins := [102], outs := [107], params := [16, 64, 8, 16] },
  ]

def sm_goal_9InitShapes : List (Tid × Shape) := [
  (102, [16, 64, 128]),
]

def sm_goal_9InitEnv : ShapeEnv := shapeEnvOfList sm_goal_9InitShapes

def pm_goal_9InitShapes : List (Tid × Shape) := [
  (102, [16, 64, 128]),
]

def pm_goal_9InitEnv : ShapeEnv := shapeEnvOfList pm_goal_9InitShapes

def goal_9_cut_initGoals : List LineageGoal := initGoals ++ goal_9_prereqs

def goal_9_stmt_cut : Prop :=
  CoarseLineageHoldsWithInit sm_goal_9 pm_goal_9 goal_9 sm_goal_9InitEnv pm_goal_9InitEnv goal_9_cut_initGoals

set_option linter.unusedSimpArgs false in
theorem prove_goal_9_cut : goal_9_stmt_cut := by
  intro initSM initPM hSmInit hPmInit hInitGoals
  have hInit102 : InitGoalHolds pm_goal_9.numRanks intermediateGoal_102 initSM initPM := by
    apply hInitGoals; simp [goal_9_cut_initGoals, goal_9_prereqs, initGoals]
  have ⟨h102_shape, h102_eq⟩ := initGoalHolds_replicated pm_goal_9.numRanks
    intermediateGoal_102 102 [16, 64, 128] initSM initPM hInit102 rfl rfl rfl
  have hsm : (denoteGraph sm_goal_9 initSM) 107 = fw_view [16, 64, 8, 16] (initSM 102) := by
    simp [sm_goal_9, denoteGraph, List.foldl, applyNode, evalOp, storeSet]
  have hpm : (denoteGraph pm_goal_9 initPM) 107 = fw_view [16, 64, 8, 16] (initPM 102) := by
    simp [pm_goal_9, denoteGraph, List.foldl, applyNode, evalOp, storeSet]
  dsimp only [goal_9_stmt_cut, CoarseLineageHoldsWithInit, goal_9] at *
  simp only [List.map, Piece.tid]
  rw [hsm, hpm, h102_eq]
  refine ⟨?_, ?_, ?_⟩
  · simp [fw_view, Tensor.mkShape]
  · simp [fw_view, Tensor.mkShape]
  · simp [reconstructWithDim]

end TrainVerify.Denote.GeneratedGoals

