import denote.yoco_goals.Pattern_3
open TrainVerify.Denote.GeneratedPatterns
#print axioms fw_all2all_moe_gmm_full_split_commute_2
#print axioms fw_add_allGather0_commute_2_2048_1024
#print axioms fw_mul_allGather0_commute_2_of_broadcast
#print axioms fw_sigmoid_allGather0_commute_2
#print axioms fw_linear_allGather0_commute_2
#print axioms fw_view_allGather0_commute_2
#print axioms fw_swiglu_allGather0_commute_2
#print axioms fw_rms_norm_allGather0_commute_2
#print axioms TrainVerify.Denote.fw_norm_linear_allGather0_commute_2
#check @TrainVerify.Denote.fw_mix_precision_linear_allGather0_commute_2
